### ISSUE TITLE
Retry adb install

### ISSUE THREAD

**Issue by bootstraponline** [calabash/calabash-android#171]
Sometimes adb install fails so retrying a few times would help improve robustness.

> Error: Could not access the Package Manager.  Is the system running?

**Comment by TobiasRoikjer** [comment]
This is a good idea, but I would much rather have Calabash-Android fail fast if something is wrong. Many things can cause the devices to be in that state, and I don't think Calabash is the right tool to manage the lifecycles of the hardware itself.

**Comment by bootstraponline** [comment]
... failing fast when adb flakes out is silly. I agree Calabash isn't the right tool if it's not able to retry failed adb commands.

**Comment by TobiasRoikjer** [comment]
@bootstraponline Calabash does not reboot a device. Therefore I don't think Calabash has the responsibility of handling a device which is not yet done rebooting.

**Comment by bootstraponline** [comment]
I'm talking about adb commands failing due to flakiness (meaning they succeed when run again), which clearly Calabash doesn't care about.

**Comment by TobiasRoikjer** [comment]
I have never experienced that, if you believe the adb install command is unstable, then we should of course retry. If it is only the cause of the device being in a bad state, I don't think Calabash should try to solve it.

**Comment by bootstraponline** [comment]
You've never experienced an adb protocol fault?

**Comment by TobiasRoikjer** [comment]
No I have never experienced that. If ADB is unstable we should retry all commands.

**Comment by bootstraponline** [comment]
> If ADB is unstable we should retry all commands.

That's what [appium does](https://github.com/appium/appium-adb/blob/fe5dce74782267a9ef591c56a5c9bac42fe0d167/lib/adb.js#L167)
