### ISSUE TITLE
sign gem releases

### ISSUE THREAD

**Issue by bootstraponline** [calabash/calabash-android#191]
When the proper way to sign gems is decided, it'd be nice to have signed releases of calabash-android.

- http://solutious.com/blog/2013/02/06/net-ssh-gem-code-signed/

**Comment by TobiasRoikjer** [comment]
@jmoody thoughts?

**Comment by jmoody** [comment]
404 on the link from Jonas.

I have no opinion.

**Comment by bootstraponline** [comment]
The new RubyGems guide is located [here](http://guides.rubygems.org/security/). It discusses the `gem cert` command.

> RubyGems has had the ability to cryptographically sign gems since version 0.8.11. This signing works by using the gem cert command to create a key pair, and then packaging signing data inside the gem itself.
