### ISSUE TITLE
Cannot get the image path via query

### ISSUE THREAD

**Issue by choppergrip** [calabash/calabash-android#231]
Hello,
Now cannot get the image path:

irb(main):007:0> query("\* id:'sticker_image'",:src)
[
    [0] {
                 "error" => "NO accessor for src",
            "methodName" => "src",
        "receiverString" => "android.widget.ImageView@43b51d80",
         "receiverClass" => "android.widget.ImageView"
    }]

Could you add the feature that it was possible to verify the presence image on the screen?

**Comment by lony** [comment]
Did you find a solution @alkor133?
@jonasmaturana what objects could I access?
