### ISSUE TITLE
Is debug.keystore required?

### ISSUE THREAD

**Issue by Inder31** [calabash/calabash-android#241]
Hi,

I am new to calabash-android.I am doing testing of an application.Developer has provided with just an apk file and no debug.keystore file.I read in the blogs that you need to specify the location of debug.keystore file along with password and alias.

So,I want to know whether debug.keystore is required for starting the application testing on calabash.or,is there any other workaround by which we can generate a debug.keystore for that apk and use it
![screen](https://f.cloud.github.com/assets/4308813/447796/74082614-b217-11e2-9079-c9355be7cffa.png)
?

**Comment by muneermuhammed** [comment]
Hi, I am getting 

> /usr/local/bundle/gems/calabash-android-0.7.2/lib/calabash-android/java_keystore.rb:32:in `initialize': Could not list certificates in keystore. Probably because the password was incorrect. (RuntimeError)

while running the test on docker. What should I do to fix it?

**Comment by regianer** [comment]
and after Calabash-android setup ?
Please enter keystore information to use a custom keystore instead of the default
Please enter keystore location
