### ISSUE TITLE
 The app does not start 

### ISSUE THREAD

**Issue by choppergrip** [calabash/calabash-android#278]
1. I start calabash-android console
2. Enter:
   ENV["ADB_DEVICE_ARG"] = "4df1b1021e2b6f4f"
   path1 = File.expand_path("rotate.apk")
   @@app1 = Calabash::Android::Operations::Device.new(
       self, ENV["ADB_DEVICE_ARG"], "45678", path1, test_server_path(path1), 7102)
3. @@app1.start_test_server_in_background

Actual result:
nil  But the app does not start

Expected result:
I did the same with other applications and it works

You can find application and server here:
https://www.dropbox.com/sh/fngqd4itf18fa38/P-3dCc5sYM

**Comment by bigbunny69** [comment]
jonas,

how and where do i add those internet permissions. i am using win7 host with android sdk
