### ISSUE TITLE
call ABase:transition with tap action: Trying to convert a Map without method_name to an operation. {}

### ISSUE THREAD

**Issue by hooway** [calabash/calabash-android#279]
Call the ABase:transition to jump to different page by tapping

mypage.transition( {:tap=>"* marked:'xxx''", :page=>NewPage })	

query failed because: Trying to convert a Map without method_name to an operation. {}

I think the problem is caused by

  tap_options = transition_options[:tap_options] || {}
      touch(uiquery, tap_options)

I have tried touch(uiquery, {} ) directly and get same error.

===logcat output===

 URI: //map
 params: {json={"query":"* marked:'maindriver_hometerminal'","operation":{"method_name":"query","arguments":[{}]}}
 }
 java.lang.IllegalArgumentException: Trying to convert a Map without method_name to an operation. {}

my env: 0.4.7.pre9, ruby 193

**Comment by TobiasRoikjer** [comment]
I'm closing this due to old age. Feel free to reopen is issue persists.
