### ISSUE TITLE
Connection between calabash and AVD device has been lost it show error as "ReceiveTimeoutError: execution expired"

### ISSUE THREAD

**Issue by sanjaykumar5115** [calabash/calabash-android#290]
Dear all,

i am using calabash android for mobile testing on emulator device( not real) 

We are facing one problem - calabash Connectivity between testserver and device is lost and its gives following error after each unsuccessful step as
Quote
irb(main):004:0> query("org.apache.cordova.CordovaWebView")
HTTPClient::ReceiveTimeoutError: execution expired
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
/session.rb:879:in `gets'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
/session.rb:879:in`block in parse_header'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
/session.rb:875:in `parse_header'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
/session.rb:858:in`read_header'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
/session.rb:667:in `get_header'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:1137:in`do_get_header'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:1086:in `do_get_block'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:887:in`block in do_request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:981:in `protect_keep_alive_disconnected'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:886:in`do_request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:774:in `request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/httpclient-2.3.3/lib/httpclient
.rb:684:in`post'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.7.pre9/lib
/calabash-android/operations.rb:321:in `make_http_request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.7.pre9/lib
/calabash-android/operations.rb:281:in`http'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.7.pre9/lib
/calabash-android/operations.rb:586:in `http'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.7.pre9/lib
/calabash-android/operations.rb:702:in`map'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.7.pre9/lib
/calabash-android/operations.rb:129:in `query'
        from (irb):4
        from C:/Ruby193/bin/irb:12:in`<main>'irb(main):005:0> query("org.apache
.cordova.CordovaWexit
Quote
 Ruby gem list

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.0)
actionpack (3.0.0)
activemodel (3.0.0)
activerecord (3.0.0)
activeresource (3.0.0)
activesupport (3.0.0)
arel (1.0.1)
awesome_print (1.1.0)
bigdecimal (1.1.0)
builder (2.1.2)
bundler (1.0.0)
calabash-android (0.4.7.pre9)
capybara (1.1.2)
childprocess (0.1.9)
cucumber (1.3.4)
cucumber-rails (1.3.1)
diff-lcs (1.2.4)
erubis (2.6.6)
ffi (1.0.7 java)
gherkin (2.12.1 x86-mingw32)
httpclient (2.3.3)
i18n (0.4.2)
io-console (0.3)
json (1.5.4)
json_pure (1.0.0)
mail (2.2.7)
mime-types (1.16)
minitest (2.5.1)
multi_json (1.7.7)
multi_test (0.0.1)
nokogiri (1.5.0 x86-mingw32)
polyglot (0.3.1)
rack (1.2.1)
rack-mount (0.6.13)
rack-test (0.5.5)
rails (3.0.0)
railties (3.0.0)
rake (0.9.2.2)
rdoc (3.9.4)
retriable (1.3.3.1)
rubyzip (0.9.9)
selenium-webdriver (2.0.0)
slowhandcuke (0.0.3)
thor (0.14.0)
treetop (1.4.5)
tzinfo (0.3.37)
## xpath (0.1.4)

To resolve this error we need to close own device and restart the same. It happens each time we run the test on app. if we want run the same test on already open session and Calabash hang.  

Please give your suggestion to resolve calabash hang problem and session restart

**Comment by john898** [comment]
@sanjaykumar5115 What was the reason you closed this issue? I am running into this issue right now. Did you ever resolve your problem?

**Comment by sanjaykumar5115** [comment]
I have not closed this issue it might be Github closed it , i am not aware of this.
To solve this, i have used the a workaround as -"instead use of Virtual device, i used the read device"

**Comment by vebhrocks** [comment]
@sanjaykumar5115 : I am facing the kind of issue with real device. The scenario is, when I connect my Android device with laptop, calabash first time runs the script after every next time there is no error but it keep my script on halt. you can refer this  #615 ticket no added on GitHub.
