### ISSUE TITLE
Instrumentation Test Server never ready

### ISSUE THREAD

**Issue by felipecsl** [calabash/calabash-android#295]
Hey guys I'm facing this weird issue after I changed the login screens on my app. BTW [this](https://play.google.com/store/apps/details?id=com.weheartit) is the app I'm testing.

Basically calabash can start the app correctly but the test server never gets into a ready state. I suspect that the `testHook()` method is never being called, since the `HttpServer` `ready` flag is always false.

If I go to `http://127.0.0.1:34782/screenshot` I can see the device screenshot correctly, and if I go to `http://127.0.0.1:34782/ready` I get `false`.

This is the command I'm running:

`calabash-android console bin/MainActivity-debug.apk` 

```
➜  whi-android git:(master) ✗ calabash-android console bin/MainActivity-debug.apk
irb(main):001:0> start_test_server_in_background
RuntimeError: Unable to make connection to Calabash Test Server at http://127.0.0.1:34782/
Please check the logcat output for more info about what happened

    from /Users/felipe/.rvm/gems/ruby-1.9.3-p429@whi-android/gems/calabash-android-0.4.8/lib/calabash-android/operations.rb:532:in `rescue in start_test_server_in_background'
    from /Users/felipe/.rvm/gems/ruby-1.9.3-p429@whi-android/gems/calabash-android-0.4.8/lib/calabash-android/operations.rb:515:in `start_test_server_in_background'
    from /Users/felipe/.rvm/gems/ruby-1.9.3-p429@whi-android/gems/calabash-android-0.4.8/lib/calabash-android/operations.rb:92:in `start_test_server_in_background'
    from (irb):1
    from /Users/felipe/.rvm/rubies/ruby-1.9.3-p429/bin/irb:16:in `<main>'
```

The same thing happens with `calabash-android run`.

The app starts up in the device but then gets stuck in the Splash screen.

The weird thing is that if I manually tap the Log In button in the device, then tap the Email button (to log in using my email/password), then all of a sudden the test server gets ready and everything works. There seems to be something specific with my initial screens that is not letting the test server start.

When the server is stuck, all I get on LogCat is this:

```
09-11 12:12:33.367: I/System.out(22586): params: {json={}
09-11 12:12:33.367: I/System.out(22586): }
09-11 12:12:33.414: I/System.out(22586): URI: //ping
09-11 12:12:33.414: I/System.out(22586): params: {json={}
09-11 12:12:33.414: I/System.out(22586): }
09-11 12:12:33.492: I/System.out(22586): URI: //ready
09-11 12:12:33.492: I/System.out(22586): params: {json={}
09-11 12:12:33.492: I/System.out(22586): }
```

I'm running calabash on OSX 10.8.4, calabash 0.4.8, Android 2.3.6, Ruby 1.9.3.

**Comment by kf6nvr** [comment]
You can disable network monitoring with Mint. See: http://docs.splunk.com/Documentation/MintAndroidSDK/latest/DevGuide/Disablenetworkmonitoring for how and why.

**Comment by doronzRumble** [comment]
thanks @kf6nvr! just had this issue and you post really helped.
small question, in the link it states you can add a url black list to remove from monitoring.
have you tried using it?
i tried entering several urls but was unable to solve the issue and keep netwrok monitoring enabled.

thanks in advance
