### ISSUE TITLE
Calabash-android sign issue

### ISSUE THREAD

**Issue by selve** [calabash/calabash-android#300]
I am having the sign issue. I try all the idea from the web suggestion but no luck can you please help me . I am new to this.

C:\Ruby193\features>calabash-android resign AndroidDemoProject_debug.apk
C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.14/lib/calabash-android/java_keystore.rb:27:in `sign_apk': Could not sign app: C:/Users/S3914~1.KAN/AppData/Local/Temp/d20131004-5412-10ocu2m/unsigned.apk (RuntimeErr
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.14/lib/calabash-android/helpers.rb:89:in`sign_apk'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.14/lib/calabash-android/helpers.rb:83:in `block in resign_apk'
        from C:/Ruby193/lib/ruby/1.9.1/tmpdir.rb:83:in`mktmpdir'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.14/lib/calabash-android/helpers.rb:76:in `resign_apk'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.14/bin/calabash-android:106:in`<top (required)>'
        from C:/Ruby193/bin/calabash-android:23:in `load'
        from C:/Ruby193/bin/calabash-android:23:in`<main>'

**Comment by sreedeep123** [comment]
I have faced the same problem....found a solution for it .

Hope you guys have Android ADT SDK bundle in your machine 
In that Go to Eclipse -- Open the eclipse tool/work space > Windows > Preferences >  Android > Build 
In this it should have default debug key store path and fingerprints ........otherwise you can get this error while resign .apk

**Comment by jjacquet** [comment]
This helped by changing the password to andoird and and using the latest gem install calabash-android --pre

After calabash-android resign <apk> and calabash-android build <apk> work perfectly and no errors are shown. When I use  calabash-android run /test.apk i get the following error

"App did not start `block in start_test_server_in_background'"

**Comment by vebhrocks** [comment]
I'm facing this issue on Ubuntu with my application new build(.apk). not able to figure out what to do? Is there any way to back on track? earlier it is working Resign and Run commands but now its giving the below error when I run Resign command : 

calabash-android resign my_app.apk
ERROR: failed opening '/tmp/d20150914-3091-hydelk/unsigned.apk' as Zip file
/var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: /tmp/d20150914-3091-hydelk/unsigned.apk (RuntimeError)
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:157:in `sign_apk'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:112:in `block in resign_apk'
	from /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:106:in `resign_apk'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/bin/calabash-android:114:in `<top (required)>'
	from /usr/local/bin/calabash-android:23:in `load'
	from /usr/local/bin/calabash-android:23:in `<main>'

**Comment by muthurajbharathi** [comment]
hi i am trying to do Calabash resign with my custom keystore not with default keystore which is present in

/home/user/.android.

means the situation is like user will upload apk and his keystore on some web application, i will pick that keystore and do calabash resignin... please help me out.

**Comment by elPartizan** [comment]
Hi, my problem is:

`MacBook-Air-Ila:calabash elpartizan$ calabash-android resign app-debug.apk 
/Library/Ruby/Gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: /var/folders/jf/scsb5s8x1zd5259pg90k96100000gn/T/d20171116-2172-1ua813f/unsigned.apk (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:164:in `sign_apk'
	from /Library/Ruby/Gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:119:in `block in resign_apk'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /Library/Ruby/Gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:113:in `resign_apk'
	from /Library/Ruby/Gems/2.3.0/gems/calabash-android-0.9.0/bin/calabash-android:133:in `<top (required)>'
	from /usr/local/bin/calabash-android:22:in `load'
	from /usr/local/bin/calabash-android:22:in `<main>'
`

**Comment by CharuPratima** [comment]
I am getting the below error when executing android-calabash build command. Can anyone suggest
 uninitialized constant Zip::Entry::Pathname (NameError)
