### ISSUE TITLE
Update to "Running Calabash Android" wiki page

### ISSUE THREAD

**Issue by full-of-foo** [calabash/calabash-android#301]
Inform users that another prerequisite, for both running a suite and a entering console session for a given droid app, is that one must add the following inside of the manifest tag, after your application tag: 
(<)uses-permission android:name="android.permission.INTERNET(/>)

(FYI - Github sanitises any 'open-close tag' text, hence why I have wrapped the tag in parens)

**Comment by TobiasRoikjer** [comment]
https://github.com/calabash/calabash-android#problems-starting-the-tests

The wiki should be open to public edits.
