### ISSUE TITLE
Double Tap UI Element Feature 

### ISSUE THREAD

**Issue by jescriba** [calabash/calabash-android#331]
No current functionality for double tapping a ui element. 
The following doesn't suffice: 

``` ruby
2.times do 
  touch "Button"
end
```

**Comment by TheChell** [comment]
Is there any way to speed up the time in between taps? When I use this step it performs a different action than the one I want (and the one that's performed when I manually double tap on the device). I'm not sure if there is an easy way to make the tapping faster?
