### ISSUE TITLE
There is no reliable way to do 'assert_text' with i18n

### ISSUE THREAD

**Issue by raulriera** [calabash/calabash-android#335]
It seems you can't assert text from the resources. Which makes testing a bit of a pain because I need to copy and paste what I have on my resources on the tests

**Comment by dannyroa** [comment]
Is this possible now with Calabash? (e.g. use R.string.sample_string).

**Comment by dannyroa** [comment]
It looks like there is a function to get value of a string resource.

https://github.com/calabash/calabash-android/blob/e2da2817809edf38256a55093dc1d3835c9c6410/ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/actions/l10n/WaitForElement.java

I can't figure out how to use wait_for_element_exists though.

https://github.com/calabash/calabash-android/blob/e2da2817809edf38256a55093dc1d3835c9c6410/ruby-gem/lib/calabash-android/wait_helpers.rb

**Comment by sherbhachu** [comment]
I don't quite get the question here.....are you trying to test a strings
file, en, fr, de, etc using i18n with calabash and do some text asserts? If
you are, then yes, it's possible, I have an app that is in English and
German and it works ok.

**Comment by dannyroa** [comment]
Yes. That's what I'm trying to do.

It looks like perform_action('wait_for_l10n_element', 'sample_string') works but I can't figure out how to tweak the timeout.

**Comment by sherbhachu** [comment]
perform_action('wait_for_l10n_element', 'sample_string', :timeout => 10) ?

**Comment by dannyroa** [comment]
If `perform_action('wait_for_l10n_element', 'sample_string', :timeout => 10)`
I get an error:

`Action 'wait_for_l10n_element' unsuccessful: String resource ID #0x0 (RuntimeError)`

But `perform_action('wait_for_l10n_element', 'signin_failed_toast'` works.

**Comment by sherbhachu** [comment]
How about wrapping it in a wait for block?


wait_for(:timeout => 10 { perform_action('wait_for_l10n_element',
'signin_failed_toast')})

You could probably add the retry count too

I'm pretty sure the wait_for_l10n_element method does not natively
support passing in a timeout

**Comment by dannyroa** [comment]
Tried it. It seems to work.

Thanks!

**Comment by sherbhachu** [comment]
No probs, have a look through the documentation, it's all there mate :)
