### ISSUE TITLE
Cannot get Calabash-Android 0.4.18 to work with Ruby 2.0.0

### ISSUE THREAD

**Issue by svenroy** [calabash/calabash-android#342]
Hello,

My colleagues successfully used this combination to write our tests and they work fine:

cucumber (1.2.5)
calabash-android (0.4.3)
gherkin (2.11.8)
ruby (1.8.7) 

However, we're upgrading and the tests do not work with this combination:

cucumber (1.3.10)
ruby (2.0.0)
gherkin (2.12.2)
calabash-android (0.4.18)

I receive the following errors:

Given my app is running                                                                                                        
    Given I set TestSessionToken to "hrn_token"                                                                                    
    Then I wait for 10 seconds                                                                                                     
    Given I wait to see text "Welcome"    
                                                                         
      Step unsuccessful: Time out while waiting for text:Welcome (RuntimeError)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
      ./features/step_definitions/calabash_steps.rb:41:in `/^I wait to see text "([^\"]*)"$/'
      features/shared_features/010_welcomescreen/000_test.feature:13:in `Given I wait to see text "Welcome"'

On further tests i begin to receive KeepAliveDisconnected/timeout errors:

Given I wait to see text "Welcome" 

      HTTPClient::KeepAliveDisconnected (HTTPClient::KeepAliveDisconnected)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
      ./features/step_definitions/calabash_steps.rb:41:in `/^I wait to see text "([^\"]*)"$/'
      features/shared_features/010_welcomescreen/999_moveon.feature:9:in `Given I wait to see text "Welcome"'

Thanks

**Comment by TobiasRoikjer** [comment]
The USB connection to your device is most likely unstable when getting `HTTPClient::KeepAliveDisconnected`, or the app has crashed (see adb logcat for a stack trace). Closing old issue.
