### ISSUE TITLE
HTTP Disconnect Error when running in Simulator

### ISSUE THREAD

**Issue by gregeng** [calabash/calabash-android#359]
`HTTPClient::KeepAliveDisconnected (HTTPClient::KeepAliveDisconnected) (RuntimeError)`

This error is consistently causing my tests to fail. I have not been able to discern a repeatable pattern at a specific step. It does not seem specific to a particular app.

I never seem to get this error when deploying the tests to a local connected device.

Here is my current set-up:

`calabash-android (0.4.20)`
`calabash-common (0.0.1)`
`cucumber (1.3.10)`
`calabash-cucumber (0.9.167)`
`gherkin (2.12.2)`

GenyMotion - 1.3.0 (I also tried on 2.0, and 2.1)
Virtual Device : Galaxy Nexus 4.3 API 18

Note: some of my colleagues have very similar set-ups but do not run into this same issue.

@jescriba
@chazbites
@kingces95
@22austinroos90

**Comment by phamxuanha90** [comment]
Hi all,
I recently run into an error "HTTPClient::KeepAliveDisconnected: An existing connection was forcibly closed by the remote host.". 
Do you have any ideas about it?

**Comment by narendra-sphinx** [comment]
Hi Team, 
I'm using calabash-android version 0.5.12 (Updated today) @jonasmaturana & @krukow - Observe "HTTP Disconnect" issue.

Error - 
execution expired (HTTPClient::ConnectTimeoutError)

**Comment by m-davalos** [comment]
Has anyone found a workaround to the HTTPClient::KeepAliveDisconnected:  (HTTPClient::KeepAliveDisconnected) error?

**Comment by narendra-sphinx** [comment]
unfortunately not yet :(

**Comment by TobiasRoikjer** [comment]
@m-davalos @narendra-sphinx t is likely that your application has crashed if you see this message. See the adb logcat for details

**Comment by m-davalos** [comment]
It turned out to be a bad touch command. I was sending 'touch('android:id/button3')' when I sent 'touch("* marked:'No'")' the HTTPClient::KeepAliveDisconnected: (HTTPClient::KeepAliveDisconnected) error no longer displayed.

**Comment by TobiasRoikjer** [comment]
Closing old issue.
Calabash no longer crashes when given a wrongly formatted query.
