### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dalewking** [calabash/calabash-android#365]
Probably related to #206, but if I try running like this:

```
calabash-android run /some/path/to/the/apk
```

It fails to run and you get the dreaded Invalid byte sequence in UTF-8 error.

But if the APK is in the current directory and you just pass the file name it works.

I hacked in a print statement to cucumber and the reason for the error is that in the first case it is trying to parse the APK as a feature file!

**Comment by jakubbloksa** [comment]
Hi, I have similar problem.
When I am trying to run tests from cmd with:
`calabash-android.bat run apkpath --name product-tests -p android`

It starts the testing... 
Most of the times all of the tests pass, but other times it fails during testing with "Invalid byte sequence in UTF-8" error. 
Can the problem be the additional --name parameter?

Version of my calabash-android is 0.7.3
