### ISSUE TITLE
Can't find a way to enter text in V7 AppCompat search view

### ISSUE THREAD

**Issue by dalewking** [calabash/calabash-android#369]
Have a V7 AppCompat Action bar with a search view added. Can't seem to find any way to actually enter text in it once it is expanded. Have tried about all of the enter text steps defined and they all report similarly:

    Then I enter "text" into "Search Documents" 
      Action 'enter_text_into_named_field' unsuccessful: No view found with content description: 'Search Documents' (RuntimeError)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'

**Comment by TobiasRoikjer** [comment]
Closing. Use `enter_text(query, text)`
