### ISSUE TITLE
Methods not loaded in console. RVM and 0.4.22.pre1

### ISSUE THREAD

**Issue by gregeng** [calabash/calabash-android#371]
`calabash-android` methods are not being loaded into the irb console when using rvm.

I am getting the following error messages

```
2.0.0-p247 :001 > reinstall_apps
NameError: undefined local variable or method `reinstall_apps' for main:Object
    from (irb):1
    from /Users/gregeng/.rvm/rubies/ruby-2.0.0-p247/bin/irb:12:in `<main>'
```

```
2.0.0-p247 :002 > start_test_server_in_background
NameError: undefined local variable or method `start_test_server_in_background' for main:Object
    from (irb):2
    from /Users/gregeng/.rvm/rubies/ruby-2.0.0-p247/bin/irb:12:in `<main>'
```

**More about my environment:**
rvm version:
`rvm 1.25.14 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
`
ruby version:
`ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.2]
`
calabash-android gem version:
`0.4.22.pre1`

@jescriba @kingces95 @chazbites

**Comment by SRowley90** [comment]
I am getting this error now running:

calabash-android: 0.5.5
Ruby Version: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
rvm: rvm 1.26.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

This was working a couple of weeks ago but now I have the same error as described above since updating calabash.

I'm new to ruby and calabash so please forgive me for any naivety.

**Comment by jmoody** [comment]
@SRowley90 Is this a cross-platform project (iOS and Android)?

If so, there might be a conflict in awesome_print version which will cause a `require` statement to fail silently.

**Comment by SRowley90** [comment]
@jmoody It is, but i'm running them independently. I imagine there may be some cross dependancies though regarding the gems used.

**Comment by jmoody** [comment]
@SRowley90 

Are you using bundler?  If you are not already, I recommend that you start. [1]

If bundler is not an option, try uninstalling awesome_print and installing awesome_print 1.2

```
$ gem update --system
$ gem uninstall -Vax --force --no-abort-on-dependent awesome_print
$ gem install awesome_print --version 1.2
```

My recommendation is to use bundler and update to calabash-ios to 0.12.2.

```
# A sample Gemfile
source 'https://rubygems.org'

gem 'calabash-android', '0.5.5'
gem 'calabash-cucumber', '0.12.2'

# Create a Gemfile.lock
$ bundle update

# Run your ruby commands in the context of bundle exec
$ bundle exec calabash-android console
```

- [1] https://github.com/calabash/calabash-ios/wiki/B2-Updating-your-run-loop-version#use-bundler

**Comment by SRowley90** [comment]
Thank you very much for your help. That works perfectly.
