### ISSUE TITLE
Android path's

### ISSUE THREAD

**Issue by nfagen** [calabash/calabash-android#400]
I ran the calabash-android commands with verbose logging. I noticed that calabash-android doesn't like the space in the path to the Android SDK even when the path is escaped appropriately "Android\ Studio"'. I changed the application name to "AndroidStudio" and everything works. I also had to change my .bash_profile to account for the path changes.

From:
export ANDROID_HOME=/Applications/Android\ Studio.app/sdk
export PATH=/Applications/Android\ Studio.app/sdk/platform-tools:$PATH

To:
export ANDROID_HOME=/Applications/AndroidStudio.app/sdk
export PATH=$PATH:/Applications/AndroidStudio.app/sdk/platform-tools

I could run the automation fine on devices and simulators with no issues before these changes. It was only affecting when trying to use the console. It wouldn't allow me to even run any calabash-android commands in console until the space was removed and paths were changed. 

calabash-android (0.4.20)
calabash-common (0.0.1)
calabash-cucumber (0.9.168)
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.3.0]

Regards,

Nick

**Comment by TobiasRoikjer** [comment]
Closing old issue.
This should be fixed.
