### ISSUE TITLE
performAction('press_l10n_element', l10nkey) problems

### ISSUE THREAD

**Issue by dreguerahw** [calabash/calabash-android#403]
When using <b>performAction('press_l10n_element', l10nkey)</b> 
and <b>l10nkey == translation</b>, 
then element is not pressed.

Example:
```xml
<string formatted="false" name="rooms">Rooms</string>
```

**Comment by TobiasRoikjer** [comment]
We should fix it using something like this https://github.com/calabash/calabash-android/pull/413
