### ISSUE TITLE
/usr/local/bin/ruby: No such file or directory -- cucumber (LoadError)

### ISSUE THREAD

**Issue by helabenkhalfallah** [calabash/calabash-android#405]
Hello,

When i run calabash-android from Jenkins i got this error:
/usr/local/bin/ruby: No such file or directory -- cucumber (LoadError)

Jenkins, calabash,gem,ruby.. are installed on centOS.

Below is my configuration:

which ruby
/usr/local/bin/ruby

whereis ruby
ruby: /usr/bin/ruby /usr/lib/ruby /usr/lib64/ruby /usr/local/bin/ruby /usr/local/lib/ruby /usr/share/man/man1/ruby.1.gz

which gem
/usr/local/bin/gem

which cucumber
/usr/local/bin/cucumber

which rvm
/usr/local/rvm/bin/rvm

gem list

*** LOCAL GEMS ***
actionmailer (4.1.1)
actionpack (4.1.1)
actionview (4.1.1)
activemodel (4.1.1)
activerecord (4.1.1)
activesupport (4.1.1)
arel (5.0.1.20140414130214)
awesome_print (1.2.0)
bigdecimal (1.2.3)
builder (3.2.2)
bundler (1.5.3)
calabash-android (0.4.21)
coderay (0.9.8)
cucumber (1.3.15)
diff-lcs (1.2.5)
erubis (2.7.0)
escape (0.0.4)
gherkin (2.12.2)
hike (1.2.3)
hoe (3.8.1)
httpclient (2.3.4.1)
i18n (0.6.9, 0.4.2)
iconv (1.0.4)
io-console (0.4.2)
json (1.8.1)
mail (2.5.4)
mime-types (1.25.1)
minitest (5.3.3, 4.7.5)
multi_json (1.10.0)
multi_test (0.1.1)
mysql (2.9.1)
polyglot (0.3.4)
psych (2.0.4, 2.0.2)
rack (1.5.2, 1.1.0)
rack-test (0.6.2)
rails (4.1.1)
railties (4.1.1)
rake (10.1.0, 0.8.3)
rdoc (4.1.0)
RedCloth (4.2.9)
rest-client (1.6.7)
retriable (1.3.3.1)
rubygems-update (2.2.2, 1.8.25)
rubytree (0.5.2)
rubyzip (0.9.9)
slowhandcuke (0.0.3)
sprockets (2.12.1)
sprockets-rails (2.1.3)
syck (1.0.1)
test-unit (2.1.0.0)
thor (0.19.1)
thread_safe (0.3.3)
tilt (1.4.1)
treetop (1.4.15)
tzinfo (1.1.0)
xamarin-test-cloud (0.9.30)

**Comment by TobiasRoikjer** [comment]
Closing old issue.
In general, we recommend installing a tool like rbenv to manage your Ruby installation, and running everything using bundler (`bundle exec`) - which you seen to be doing.
