### ISSUE TITLE
Scroll Web View With Metrics to an element without id

### ISSUE THREAD

**Issue by MikiPopovic** [calabash/calabash-android#408]
Hi everyone!

I'm new to calabash and automation, but i find this tool very nice for testing. I've resolved most of problems I had in automating my App, but I can't find the way to scroll through Web View With Metrics inside my app. Most of elements on page don't have id, so for other steps I used xpath search to find elements and test them.

How can I scroll to a certain element on Web View With Metrics using xpath or Regexp searches?

I've tried this:

performAction('scroll_to','xpath','//*[contains(text(), \"Voice alerts\")]')

, but I get error:

RuntimeError: Action 'scroll_to' unsuccessful: java.lang.Throwable: A WebView method was called on t
hread 'Thread-800'. All WebView methods must be called on the same thread. (Expected Looper Looper (
main, tid 1) {429bb3f8} called on null, FYI main Looper is Looper (main, tid 1) {429bb3f8})
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.21/lib/calabash-android/operat
ions.rb:278:in `block in perform_action'
        from C:/Ruby193/lib/ruby/1.9.1/timeout.rb:69:in`timeout'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.21/lib/calabash-android/operat
ions.rb:267:in `perform_action'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.21/lib/calabash-android/operat
ions.rb:52:in`performAction'
        from (irb):117
        from C:/Ruby193/bin/irb:12:in `<main>'

Xpath and Regexp searches work fine for other test steps. For example:

query("WebViewWithMetrics xpath:'//_[contains(text(), \"#{webtext}\")]'")
query("WebViewWithMetrics css:'_'").find { |x| x["textContent"] =~ Regexp.new(webtext)}

When I tried this method to scroll to a element that has id:
performAction('execute_javascript',"(document.getElementById('#{id}')).scrollIntoView(true)")

web view started reloading, but without end. Page couldn't be refreshed.

Please help!

Miki

**Comment by inkadnb** [comment]
I haven't been able to get this to work. Has anyone else had better luck? I simply can't seem to get scrolling to work in webViews, checking whether elements exist, clicking on them etc works fine. However, using the same xpath for scrolling simply doesn't work.
