### ISSUE TITLE
View query returns no results for ARM emulator

### ISSUE THREAD

**Issue by mgrebenets** [calabash/calabash-android#418]
Hi all.

I am trying to run UI automation tests on Android emulator.

When I run tests on emulator that uses `Intel x86 Atom System Image` it all works as expected.

When I try the same on emulator that uses `ARM EABI v7a System Image`, all the `query` calls return no results (empty array). For example `query("*")` returns nothing.
I know that test server works, I can still get successful responses from the app through backdoors.

It also works fine with Genymotion, but Genymotion use x86 image too.

I have latest Android SDK, all components up to date.

Is it only me or this is a know issue with ARM images?

**Comment by MarcPer** [comment]
Happens to me also. I've managed to make it work by running reinstall_apps on the calabash console, followeb by start_test_server_in_background.I run the ARM emulator on a CI server, so I can't actually see the screen to know what is going on, but after waiting for a few seconds, the query will return layout components correctly.
