### ISSUE TITLE
`main_activity': 'launchable-activity' not found in aapt output  (RuntimeError)

### ISSUE THREAD

**Issue by HishamHosni** [calabash/calabash-android#420]
It seems that the .apk file uses < acitivity-alias >, instead of < activity > and i have a project that i don't have the source code of the project. calabash can't find the launchable-activity due to this....

Any help, Please?

**Comment by mraviteja** [comment]
Hi Guys,

I'm have this problem  when run the tests with calabash. How to solve it?

The command:
calabash-android run MyApk.apk

/var/lib/gems/1.9.1/gems/calabash-android-0.5.8/lib/calabash-android/helpers.rb:50:in `rescue in main_activity': No launchable activity found in AndroidManifest (RuntimeError)
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.8/lib/calabash-android/helpers.rb:25:in `main_activity'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.8/bin/calabash-android-run.rb:20:in `calabash_run'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.8/bin/calabash-android:85:in `<top (required)>'
	from /usr/local/bin/calabash-android:19:in `load'
	from /usr/local/bin/calabash-android:19:in `<main>'

pleas help me how to resolve this issue.

**Comment by engenhariaSI** [comment]
Im stuck there too...solutions?
