### ISSUE TITLE
custom keystore without password or alias not working

### ISSUE THREAD

**Issue by kamstrup** [calabash/calabash-android#424]
Setting a custom keystore with 'calabash-android setup' and leaving the password and alias blank (because there are none) is not working.

*calabash-android run* tries to issue the command
```
/usr/bin/keytool" -list -v -alias "" -keystore "/Users/kamstrup/.local/share/Xamarin/Mono for Android/debug.keystore" -storepass "" "-J"-Dfile.encoding=utf-8"
```
but the keytool tool on OSX does not accept empty -alias or -storepass args. They must be entirely left out.

**Comment by TobiasRoikjer** [comment]
Closing old issue.
This has been fixed (a long time ago) :)
