### ISSUE TITLE
scroll_up, scroll_down do not work

### ISSUE THREAD

**Issue by NM-Clio** [calabash/calabash-android#426]
In the `calabash-android console`, the `scroll_up` and `scroll_down` replacements in v0.5 for `performAction('scroll_up')` and `performAction('scroll_down')` respectively, do _not_ work.

These are the errors I see:
`Embed is a Cucumber method and is not available in this console.`
`Calabash::Android::WaitHelpers::WaitError: Timed out waiting...`

**Comment by bloomzCode** [comment]
@NM-Clio please check this out , how to scroll on nested scroll view : https://www.youtube.com/watch?v=zKVk4d4FgBI
