### ISSUE TITLE
NameError: "undefined local variable or method `eisa_ap' for main:Object" when we run "reinstall_apps" after run the console command

### ISSUE THREAD

**Issue by E20027843** [calabash/calabash-android#437]
Hi,

I am getting below error while running "reinstall_apps" command.
I am using win 8 & calabash version is 0.4.21 , request you please  assist me.

F:\calabash-testing>calabash-android console robobook.apk
DL is deprecated, please use Fiddle
**\* WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
irb(main):001:0> reinstall_apps
NameError: undefined local variable or method `eisa_ap' for main:Object
        from (irb):1
        from C:/Ruby200-x64/bin/irb:12:in`<main>'
irb(main):002:0> start_test_server_in_background
NameError: undefined local variable or method `eisa_ap' for main:Object
        from (irb):2
        from C:/Ruby200-x64/bin/irb:12:in`<main>'
irb(main):003:0>

**Comment by akshaychoudhari358** [comment]
I am getting issue while running below command:
**irb(main):004:0> reinstall_apps**
Traceback (most recent call last):
        2: from C:/Ruby25-x64/bin/irb.cmd:19:in `<main>'
        1: from (irb):4
NameError (undefined local variable or method `reinstall_apps' for main:Object)

Any input will be helpful.
