### ISSUE TITLE
Does calabsh-android provide a way to touch link  only in the TextView?

### ISSUE THREAD

**Issue by diaocow** [calabash/calabash-android#446]

**Comment by TobiasRoikjer** [comment]
@diaocow Something like this
```ruby
def tap_text_position(query, text_to_find)
  wait_for_element_exists(query)

  text = query(query).first['text']
  index = text.index(text_to_find) + text_to_find.length/2
  hor = query(query, :getLayout, getPrimaryHorizontal: index).first.to_i
  line = query(query, :getLayout, getLineForOffset: index).first
  ver = query(query, :getLayout, getLineBaseline: line).first.to_i

  touch(query, x: 0, y: 0, offset: {x: hor, y: ver})
end
```

**Comment by wellavelino** [comment]
@TobiasRoikjer  Are you thinking of adding this method to a release? For spannable elements, this method is essential.

**Comment by TobiasRoikjer** [comment]
@wellavelino Perhaps that would be a good idea, but I do not know if this works consistently enough to add it to the framework.

**Comment by wellavelino** [comment]
@TobiasRoikjer I've testing this method in a lot of scenarios always with sucess, maybe i can submit a pull request with tests of this method. I modified him to apply on iOS tests with sucess

**Comment by TobiasRoikjer** [comment]
@wellavelino Sure, that would be great.
