### ISSUE TITLE
 App did not start (RuntimeError)

### ISSUE THREAD

**Issue by Vinish123** [calabash/calabash-android#456]
Got this error message from cmd.

App did not start (RuntimeError)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.1/lib/calabash-androi
d/operations.rb:532:in block in start_test_server_in_background' C:/Ruby200/lib/ruby/gems/2.0.0/gems/retriable-1.3.3.1/lib/retriable/retriable. rb:31:inperform'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/retriable-1.3.3.1/lib/retriable/retriable.
rb:59:in retriable' C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.1/lib/calabash-androi d/operations.rb:531:instart_test_server_in_background'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.1/lib/calabash-androi
d/operations.rb:110:in start_test_server_in_background' C:/Users/ileafsolutions/Desktop/features/support/app_life_cycle_hooks.rb:5:inBefore'
When I press "ggjhg" # calabash-android-0.5.1/lib/c
alabash-android/steps/press_button_steps.rb:17
Then I see "Under Construction" # calabash-android-0.5.1/lib/c
alabash-android/steps/assert_steps.rb:5

Also got Error response from Logcat.

08-22 06:39:05.459: E/AndroidRuntime(929): FATAL EXCEPTION: Thread-80
08-22 06:39:05.459: E/AndroidRuntime(929): java.lang.RuntimeException: java.lang.ClassNotFoundException: com.nexercise.client.android.activities.SplashActivity
08-22 06:39:05.459: E/AndroidRuntime(929): at sh.calaba.instrumentationbackend.InstrumentationBackend.getActivity(InstrumentationBackend.java:52)
08-22 06:39:05.459: E/AndroidRuntime(929): at sh.calaba.instrumentationbackend.InstrumentationBackend$1.run(InstrumentationBackend.java:93)
08-22 06:39:05.459: E/AndroidRuntime(929): Caused by: java.lang.ClassNotFoundException: com.nexercise.client.android.activities.SplashActivity
08-22 06:39:05.459: E/AndroidRuntime(929): at java.lang.Class.classForName(Native Method)
08-22 06:39:05.459: E/AndroidRuntime(929): at java.lang.Class.forName(Class.java:217)
08-22 06:39:05.459: E/AndroidRuntime(929): at java.lang.Class.forName(Class.java:172)
08-22 06:39:05.459: E/AndroidRuntime(929): at sh.calaba.instrumentationbackend.InstrumentationBackend.getActivity(InstrumentationBackend.java:49)
08-22 06:39:05.459: E/AndroidRuntime(929): ... 1 more
08-22 06:39:05.459: E/AndroidRuntime(929): Caused by: java.lang.NoClassDefFoundError: com/nexercise/client/android/activities/SplashActivity
08-22 06:39:05.459: E/AndroidRuntime(929): ... 5 more
08-22 06:39:05.459: E/AndroidRuntime(929): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nexercise.client.android.activities.SplashActivity" on path: /system/framework/android.test.runner.jar:/data/app/com.nexercise.client.android.test-1.apk:/data/app/com.nexercise.client.android-1.apk
08-22 06:39:05.459: E/AndroidRuntime(929): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
08-22 06:39:05.459: E/AndroidRuntime(929): at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
08-22 06:39:05.459: E/AndroidRuntime(929): at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
08-22 06:39:05.459: E/AndroidRuntime(929): ... 5 more

Please help me to solve this issue

Thanks in Advance.

**Comment by sotic** [comment]
Add <uses-permission android:name="android.permission.INTERNET" /> in your AndroidManifest.xml

**Comment by liaogz82** [comment]
I have the same issue but I have already added the uses-permission in the `AndroidManifest.xml`. The issue is I am running behind a proxy server where the proxy will identify every single MAC address. Is there a way out?
