### ISSUE TITLE
Using set_gps_coordinates without ACCESS_MOCK_LOCATION crashes the entire app.

### ISSUE THREAD

**Issue by john7doe** [calabash/calabash-android#459]
E/AndroidRuntime( 2122): FATAL EXCEPTION: Thread-153
E/AndroidRuntime( 2122): Process: X, PID: 2122
E/AndroidRuntime( 2122): java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION secure setting
E/AndroidRuntime( 2122): 	at android.os.Parcel.readException(Parcel.java:1465)
E/AndroidRuntime( 2122): 	at android.os.Parcel.readException(Parcel.java:1419)
E/AndroidRuntime( 2122): 	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:944)
E/AndroidRuntime( 2122): 	at android.location.LocationManager.addTestProvider(LocationManager.java:1205)
E/AndroidRuntime( 2122): 	at sh.calaba.instrumentationbackend.actions.location.FakeGPSLocation$LocationProviderThread.run(FakeGPSLocation.java:58)
W/ActivityManager(  465): Error in app X running instrumentation ComponentInfo{X/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}:
W/ActivityManager(  465):   java.lang.SecurityException
W/ActivityManager(  465):   java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION secure setting
I/ActivityManager(  465): Force stopping X appid=10057 user=0: finished inst
I/ActivityManager(  465): Killing 2122:X/u0a57 (adj 0): stop X

**Comment by TobiasRoikjer** [comment]
Closing issue, this was fixed a while ago :)
