### ISSUE TITLE
TextView is ignored in the Query results when the size of the text in TextView is big

### ISSUE THREAD

**Issue by srideviaishwariya** [calabash/calabash-android#474]
I have a Dialog with TextView which has around 4500 characters, when I do a query on this dialog the I can see all objects of the dialog except the TextView. But If I reduce the number of characters in the TextView then the TextView shows up in the query.

Is there are maximum limit on the size of text in the android Widgets?

**Comment by neofreko** [comment]
+1

**Comment by narendra-sphinx** [comment]
Face similar issue, But in my case textView is having 512 characters

**Comment by TobiasRoikjer** [comment]
I am unable to reproduce this. What terminal are you using? I've tried with a view that has 27780 characters

**Comment by jmoody** [comment]
I believe that the problem is the _center_ of the view is not visible - it is not a question of the number of characters.

**Comment by TobiasRoikjer** [comment]
If it is a questions of visibility, use `query("all ... ")`
