### ISSUE TITLE
Two-point tap doesn't work properly.

### ISSUE THREAD

**Issue by k5n** [calabash/calabash-android#486]
Version: calabash-android 0.5.2
PC: Windows 7
Android: 2.3 Gingerbread
Ruby: 1.9.3

I tried below with various parameters and then finally two-point tap worked.
But pan was also performed at the same time.

```
m1 = Gesture.tap({x: 10, y: 10, time: 0.1})
m2 = Gesture.tap({x: 40, y: 40, time: 0.1})
execute_gesture(Gesture.with_parameters(m1 + m2, {query_string: 'DecorView'}))
```

Expected result: Only two-point tap work.
Actual result: Pan and two-point tap are performed.

**Comment by TobiasRoikjer** [comment]
@k5n I cannot reproduce, is this still an issue?

**Comment by TobiasRoikjer** [comment]
Closed due to inactivity
