### ISSUE TITLE
start_test_server_in_background do not launch app

### ISSUE THREAD

**Issue by asabhijitshelar** [calabash/calabash-android#487]
Hi,

I have downloaded apk for https://play.google.com/store/apps/details?id=com.tcf.phone&hl=en

I have used http://apps.evozi.com/apk-downloader/ to download apk

I have resign and reinstall it on android device as well as emulator. 
start_test_server_in_background
nil

But App did not get start but it is get installed properly

**Comment by TobiasRoikjer** [comment]
Using the newest version of Calabash-Android I can successfully launch the application and interact with it. I assume from your newest issue that you are using an old version of Calabash-android (0.4.6), and I believe this to be the cause.

**Comment by asabhijitshelar** [comment]
Which calabash-version you are using?

**Comment by TobiasRoikjer** [comment]
@asabhijitshelar 0.5.5. I'm using OSX, but neither the Ruby version nor the OS should matter.
