### ISSUE TITLE
sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type

### ISSUE THREAD

**Issue by fryclukasz** [calabash/calabash-android#505]
I'm using v0.5.5 and when I do: `query("android.webkit.WebView css:'*'")`
I get:
Embed is a Cucumber method and is not available in this console.
RuntimeError: map android.webkit.WebView css:'*', query failed because: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [map type; class java.util.HashMap, [simple type, class java.lang.Object] -> [simple type, class java.lang.Object]] from JSON String; no single-String constructor/factory method

	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.2/lib/calabash-android/operations.rb:810:in `screenshot_and_raise'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.2/lib/calabash-android/operations.rb:1171:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.2/lib/calabash-android/operations.rb:188:in `query'
	from (irb):8
	from /usr/bin/irb:12:in `<main>'

**logcat**
I/System.out(12835): URI: //map
I/System.out(12835): params: {json={"query":"android.webkit.WebView css:'*'","operation":{"method_name":"query","arguments":[]}}
I/System.out(12835): }
I/System.out(12835): isDomQuery: css
W/System.err(12835): sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [map type; class java.util.HashMap, [simple type, class java.lang.Object] -> [simple type, class java.lang.Object]] from JSON String; no single-String constructor/factory method
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:379)
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:268)
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:244)
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2765)
W/System.err(12835): 	at sh.calaba.org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1903)
W/System.err(12835): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$2.call(UIQueryUtils.java:288)
W/System.err(12835): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$1.run(UIQueryUtils.java:237)
W/System.err(12835): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:1855)
W/System.err(12835): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err(12835): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(12835): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(12835): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err(12835): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(12835): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(12835): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err(12835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**How I can interact with this WebView?**

**Comment by TobiasRoikjer** [comment]
@fryclukasz Is this still happening?

**Comment by DineshKumar7** [comment]
Hai even I am getting the same problem on querying the webview elements.

**Comment by doronzRumble** [comment]
same here... i'm using calabash version 0.5.7 on both client and server and my app is a hybrid app.
@TobiasRoikjer if you need, i can send you the APK

**Comment by TobiasRoikjer** [comment]
@doronzRumble Upgrade to the newest version of calabash

**Comment by TobiasRoikjer** [comment]
If the issues persists I would love to get the apk

**Comment by doronzRumble** [comment]
just did, thanks @TobiasRoikjer

**Comment by doronzRumble** [comment]
issue does not persist for now thanks again @TobiasRoikjer

**Comment by TobiasRoikjer** [comment]
@doronzRumble Alright, I'll close this issue

**Comment by TobiasRoikjer** [comment]
If anyone can reproduce on the latest version, please comment on this issue
