### ISSUE TITLE
Consider upgrading Calabash httpclient to use 2.4.x rather than 2.3.x

### ISSUE THREAD

**Issue by sherbhachu** [calabash/calabash-android#506]
I am doing some work on making API calls and such to apps and services in the background, prior to test setup, etc.

One of the things I am hitting on some, not all servers, are errors around SSL connections being reset and such when doing https:// POST and GET

Errno::ECONNRESET

etc,

See the following SO links and such as examples..(first one most appropriate)

https://github.com/nahi/httpclient/issues/202#issuecomment-59154062
http://stackoverflow.com/questions/1807355/broken-pipe-errnoepipe
http://stackoverflow.com/questions/15966446/errnoeconnreset-connection-reset-by-peer-ssl-connect
http://railsapps.github.io/openssl-certificate-verify-failed.html

Much of these issues are related to the use, or actually, not much use of SSLv3 due to the POODLE issue.

By default, HTTPClient will always try to use this version of SSL when making connections.

I have sneakily modified my Gemfile.lock and modified the dependency of calabash-android to use ...
httpclient (~> 2.4.0) and the issue of connecting to these 3rd party and local services is somewhat, mostly resolved. I did also have to add this...

def http_client
      @http = HTTPClient.new
      @http.ssl_config.options |= OpenSSL::SSL::OP_NO_SSLv3
      @http
    end

to ensure it sneakily didn't use SSLv3

Is there a specific reason we are using a 2 year old version of HttpClient? Its on version 2.5.x now.

**Comment by TobiasRoikjer** [comment]
Updated in 3dc71c5450482c671576c3bf059a85c2cb9b893b
