### ISSUE TITLE
Unable to start calabash-android on 0.4.20

### ISSUE THREAD

**Issue by asabhijitshelar** [calabash/calabash-android#516]
Hi,

I need to update calabash-android0.4.6 to 0.4.20
I have added ANDROID_HOME, JAVA_HOME and 0.4.6 works well.
But when I update calabash-android to 0.4.20 then it will give me error 

irb(main):001:0> reinstall_apps
error: device not found
- waiting for device -

I have already given commands
calabash-andorid gen
calabash-andorid resign sample.apk
calabash-andorid console sample.apk

What is the issue?

**Comment by sherbhachu** [comment]
I would suggest you check the status of your ADB and ensure its available.

**Comment by TobiasRoikjer** [comment]
As @sherbhachu mentioned, this is due to ADB either not recognising the device, or the device not being connected. Running `calabash-android run <apk> -r` will output the location of ADB (2015-01-06 14:40:40 - Android SDK found at: xxx). Is the location correct?

**Comment by asabhijitshelar** [comment]
On adb devices it will list device name
D:\USER\TestingApk>adb devices
List of devices attached
A15     offline

**Comment by sherbhachu** [comment]
I think thats your answer, offline.

**Comment by asabhijitshelar** [comment]
D:\AbhijitUTSAndroid\TestingApk>adb devices
List of devices attached
A15     device

D:\AbhijitUTSAndroid\TestingApk>calabash-android console com.att.myWireless.apk
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansic
on/) to get coloured output on Windows
irb(main):001:0> reinstall_apps
error: device not found
- waiting for device -

**Comment by TobiasRoikjer** [comment]
@asabhijitshelar Is there any reason why you are not upgrading to the latest version of calabash-android? what is the result of running `D:\User\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb devices`?

**Comment by asabhijitshelar** [comment]
Yes because we have dependecy and all our framework is using commands which are there in 0.4 but may be deprecated in 0.5

**Comment by TobiasRoikjer** [comment]
Could you please open a calabash console and execute the following commands:
```ruby
puts Env.adb_path
p `#{Env.adb_path} devices`
p `#{Env.adb_path} devices`.split("\n")
p `#{Env.adb_path} devices`.split("\n").index{ |x| x =~ /List of devices attached/ } + 1
```

and paste the output of the various commands.

**Comment by asabhijitshelar** [comment]
D:\User\TestingApk>calabash-android console com.att.myWireless.apk
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansi
on/) to get coloured output on Windows
irb(main):001:0> puts Env.adb_path
"D:\User\adt-bundle-windows-x86-20130522\sdk/platform-tools/adb.ex
"
nil
irb(main):002:0> p `#{Env.adb_path} devices`
"List of devices attached \nA15\tdevice\n\n"
"List of devices attached \nA15\tdevice\n\n"
irb(main):003:0> p `#{Env.adb_path} devices`.split("\n")
["List of devices attached ", "A15\tdevice"]
[
    [0] "List of devices attached ",
    [1] "A15\tdevice"
]

irb(main):005:0> p `#{Env.adb_path} devices`.split("\n").index{ |x| x =~ /List of devices attached/ } + 1
1

**Comment by TobiasRoikjer** [comment]
I see no reason why Calabash should not work. `connected_devices` should contain your device.
Running `puts default_device.adb_command` will return a string like "<path>/adb -s A15". Please execute that command in you shell followed by install -r <apk>. For example "adb -s A15 install com.att.myWireless.apk". What is the output, does it succeed?

**Comment by asabhijitshelar** [comment]
irb(main):002:0> puts default_device.adb_command
"D:\AbhijitUTSAndroid\adt-bundle-windows-x86-20130522\sdk/platform-tools/adb.exe
" -s SERIAL
nil
irb(main):003:0>

**Comment by TobiasRoikjer** [comment]
@asabhijitshelar Please follow the exact instructions :)

**Comment by TobiasRoikjer** [comment]
@asabhijitshelar The path `D:\AbhijitUTSAndroid\adt-bundle-windows-x86-20130522\sdk/platform-tools/adb.exe` is different from `D:\User\adt-bundle-windows-x86-20130522\sdk\platform-tools`. My guess is that $ANDROID_HOME is probably not set correctly, or that Calabash-Android 0.4.20 has a bug. However, Calabash-Android 0.4.20 is so old that we can't really support it.

**Comment by TobiasRoikjer** [comment]
One thing that might solve it is the kill the current adb process and run the calabash console

**Comment by asabhijitshelar** [comment]
Hi,
I have updated calabash-android to 0.5
It may be due to ADB_DEVICE_ARG = SERIAL environment variable.

On Wed, Jan 7, 2015 at 2:34 PM, Tobias Røikjer <notifications@github.com>
wrote:

> One thing that might solve it is the kill the current adb process and run
> the calabash console
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/calabash/calabash-android/issues/516#issuecomment-68994945>
> .
>



-- 
Thanks & Regards,
*Abhijit Shelar*
(8983729507)
(Skype: abhijit.shelar1)

*Internet Communications cannot be guaranteed to be secure or error-free as
information could be delayed, intercepted, corrupted, lost, or contain
viruses. I am not accept any liability for any errors, omissions, viruses
or computer problems experienced by any recipient as a result of this
e-mail.*

**Comment by TobiasRoikjer** [comment]
If you have specified a device serial using ADB_DEVICE_ARG, and the device with that serial is not connected it is expected behaviour not to just pick a random device.
