### ISSUE TITLE
'invalid byte sequence in CP949 (ArgumentError)' is raised, when i run "calabash-android run someapk.apk" on window(32)

### ISSUE THREAD

**Issue by dookim** [calabash/calabash-android#518]
this is error logs. i dont know why..

2015-01-12 13:19:06 - JDK found on PATH.
2015-01-12 13:19:06 - JDK found at: C:\Program Files\Java\jdk1.7.0_71
2015-01-12 13:19:06 - Android SDK found at: C:\Users\user\Desktop\development\ad
t-bundle-windows-x86-20140702\sdk
No test server found for this combination of app and calabash version. Recreatin
g test server.
2015-01-12 13:19:06 - "\Program Files\Java\jdk1.7.0_71\bin/keytool.exe" -v -prin
tcert -J"-Dfile.encoding=utf-8" -file "C:/Users/user/AppData/Local/Temp/d2015011
2-3576-s1i992/META-INF/CERT.RSA"
C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calabash-android/h
elpers.rb:159:in `scan': invalid byte sequence in CP949 (ArgumentError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:159:in `extract_md5_fingerprint'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:151:in `block (2 levels) in fingerprint_from_apk'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:137:in `chdir'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:137:in `block in fingerprint_from_apk'
        from C:/Ruby21/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:136:in `fingerprint_from_apk'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/bin/calab
ash-android-build.rb:2:in `calabash_build'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/lib/calab
ash-android/helpers.rb:92:in `build_test_server_if_needed'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/bin/calab
ash-android-run.rb:16:in `calabash_run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.5/bin/calab
ash-android:85:in `<top (required)>'
        from C:/Ruby21/bin/calabash-android:23:in `load'
        from C:/Ruby21/bin/calabash-android:23:in `<main>'

**Comment by njection** [comment]
Downgrade your Ruby to 2.0.0

**Comment by TobiasRoikjer** [comment]
I'm closing this because of its age. If it is still happening, then please free to open a new issue.
