### ISSUE TITLE
Query output is sequenced changed in lollipop Android OS 5.0

### ISSUE THREAD

**Issue by asabhijitshelar** [calabash/calabash-android#520]
Hi,

In calabash-android 0.5 query output looks in this fashion for android OS 4.4
{
"id"=>"", 
"textContent"=>"Jordan\u00A0", 
"nodeName"=>"DIV", 
"class"=>"ui-block-a", "html"=>"html tags ", 
"rect"=>{
"center_y"=>519.0, 
"center_x"=>192.0, "height"=>88, 
"width"=>113, 
"bottom"=>192, 
"left"=>8, 
"right"=>121, 
"y"=>312.0, "x"=>24.0, 
"top"=>104}, 
"nodeType"=>"ELEMENT_NODE", 
"webView"=>nil},

But for Android OS 5.0 lollipop emulator
1)
[{"rect"=>{"height"=>1776, "width"=>1080, "y"=>0, "x"=>0, "center_x"=>540, "center_y"=>888}, "enabled"=>true, "class"=>"com.android.internal.policy.impl.PhoneWindow$DecorView", "tag"=>nil, "description"=>"com.android.internal.policy.impl.PhoneWindow$DecorView{1de93b22 V.E..... R....... 0,0-1080,1776}", "id"=>nil, "contentDescription"=>nil}

2)
{"class"=>"android.widget.RadioButton", "tag"=>nil, "description"=>"android.widget.RadioButton{1bddac2b VFED..C. ........ 0,0-544,144 #7f0500ca app:id/oneway}", "id"=>"oneway", "text"=>"ONE WAY", "rect"=>{"height"=>144, "width"=>544, "y"=>219, "x"=>0, "center_x"=>272, "center_y"=>291}, "enabled"=>true, "contentDescription"=>nil}, 

Why it is changed in Android OS 5.0 emulator? It is consistent for 4.4 android OS.
Observed that in 5.0 emulator rect and class are first while before it follow sequence from id
Is it fixable or for lollipop there is changed in sequence?

**Comment by sherbhachu** [comment]
Can you check if your .irbc file has awesome-print?

should have some lines like...

require 'awesome_print'
AwesomePrint.irb!
