### ISSUE TITLE
Ruby Calabash-android prompt need to quit and again need to open

### ISSUE THREAD

**Issue by asabhijitshelar** [calabash/calabash-android#521]
irb(main):015:1> query("webView css:'*'")[9]
gives output
irb(main):016:1> query("webView css:'*'")[7]
gives output
x=query("webView css:'*'").find{|x| x[\"textContent\"] == 'AT&T Mobile Share2'}
(no output) It will show ruby prompt again
irb(main):015:1> query("webView css:'*'")[9]
no output
irb(main):016:1> query("webView css:'*'")[7]
no output
irb(main):017:1> query("webView css:'*'")
no output

If I restart prompt then again it works fine. Why I need to quit ruby prompt and login it again.
i need to give command calabash-android console sample.apk

It is happen to webview more often than native application.

**Comment by TobiasRoikjer** [comment]
query("webView css:''") is not a valid css selector and may cause unexpected behaviour in your webview. `*` is probably the wildcard you are looking for.

**Comment by asabhijitshelar** [comment]
Actually it is query("webView css:'*'")  It has star in between two single quotes
