### ISSUE TITLE
App did not start

### ISSUE THREAD

**Issue by asabhijitshelar** [calabash/calabash-android#522]
calabash-android 0.5.5
httpclient 0.9.6 -- upgrade to 2.3.4.1 before that upgrade to 2.6.0.1 again downgrade to 2.3.4.1

Sometimes following error occur
irb(main):001:0> start_test_server_in_background
RuntimeError: App did not start
        from C:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.5/lib
/calabash-android/operations.rb:609:in `block in start_test_server_in_background
'
        from C:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/retriable-1.3.3.1/lib/retr
iable/retriable.rb:31:in `perform'
        from C:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/retriable-1.3.3.1/lib/retr
iable/retriable.rb:53:in `retriable'
        from C:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.5/lib
/calabash-android/operations.rb:608:in `start_test_server_in_background'
        from C:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.5/lib
/calabash-android/operations.rb:125:in `start_test_server_in_background'
        from (irb):1
        from C:/Ruby/Ruby193/bin/irb:12:in `<main>'

Output of logcat is:-

I/ActivityManager(  268): Force stopping package com.att.myWireless uid=10069
I/ActivityManager(  268): Killing proc 10774:com.att.myWireless/10069: force sto
p
W/ActivityManager(  268): Crash of app com.att.myWireless running instrumentatio
n ComponentInfo{com.att.myWireless.test/sh.calaba.instrumentationbackend.Calabas
hInstrumentationTestRunner}
I/ActivityManager(  268): Force stopping package com.att.myWireless uid=10069
I/ActivityManager(  268): Start proc com.att.myWireless for added application co
m.att.myWireless: pid=10902 uid=10069 gids={3003, 1015, 1023, 1006}
D/dalvikvm(10892): GC_CONCURRENT freed 99K, 82% free 463K/2560K, paused 0ms+0ms
D/ActivityThread(10902): setTargetHeapUtilization:0.25
D/ActivityThread(10902): setTargetHeapIdealFree:8388608
D/ActivityThread(10902): setTargetHeapConcurrentStart:2097152
I/System.out(10902): Calabash did not load Mono. This is only a problem if you a
re trying to test a Mono application
W/dalvikvm(10902): threadid=1: thread exiting with uncaught exception (group=0x4
0a86390)
E/AndroidRuntime(10902): FATAL EXCEPTION: main
E/AndroidRuntime(10902): java.lang.RuntimeException: Exception thrown in onCreat
e() of ComponentInfo{com.att.myWireless.test/sh.calaba.instrumentationbackend.Ca
labashInstrumentationTestRunner}: java.lang.RuntimeException: java.net.BindExcep
tion: bind failed: EADDRINUSE (Address already in use)
E/AndroidRuntime(10902):        at android.app.ActivityThread.handleBindApplicat
ion(ActivityThread.java:3955)
E/AndroidRuntime(10902):        at android.app.ActivityThread.access$1300(Activi
tyThread.java:126)
E/AndroidRuntime(10902):        at android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1188)
E/AndroidRuntime(10902):        at android.os.Handler.dispatchMessage(Handler.ja
va:99)
E/AndroidRuntime(10902):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10902):        at android.app.ActivityThread.main(ActivityThrea
d.java:4456)
E/AndroidRuntime(10902):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime(10902):        at java.lang.reflect.Method.invoke(Method.java:5
11)
E/AndroidRuntime(10902):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:787)
E/AndroidRuntime(10902):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:554)
E/AndroidRuntime(10902):        at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime(10902): Caused by: java.lang.RuntimeException: java.net.BindExc
eption: bind failed: EADDRINUSE (Address already in use)
E/AndroidRuntime(10902):        at sh.calaba.instrumentationbackend.actions.Http
Server.instantiate(HttpServer.java:71)
E/AndroidRuntime(10902):        at sh.calaba.instrumentationbackend.CalabashInst
rumentationTestRunner.onCreate(CalabashInstrumentationTestRunner.java:26)
E/AndroidRuntime(10902):        at android.app.ActivityThread.handleBindApplicat
ion(ActivityThread.java:3952)
E/AndroidRuntime(10902):        ... 10 more
E/AndroidRuntime(10902): Caused by: java.net.BindException: bind failed: EADDRIN
USE (Address already in use)
E/AndroidRuntime(10902):        at libcore.io.IoBridge.bind(IoBridge.java:89)
E/AndroidRuntime(10902):        at java.net.PlainSocketImpl.bind(PlainSocketImpl
.java:150)
E/AndroidRuntime(10902):        at java.net.ServerSocket.<init>(ServerSocket.jav
a:100)
E/AndroidRuntime(10902):        at java.net.ServerSocket.<init>(ServerSocket.jav
a:69)
E/AndroidRuntime(10902):        at sh.calaba.instrumentationbackend.actions.Nano
HTTPD.<init>(NanoHTTPD.java:224)
E/AndroidRuntime(10902):        at sh.calaba.instrumentationbackend.actions.Http
Server.<init>(HttpServer.java:84)
E/AndroidRuntime(10902):        at sh.calaba.instrumentationbackend.actions.Http
Server.instantiate(HttpServer.java:69)
E/AndroidRuntime(10902):        ... 12 more
E/AndroidRuntime(10902): Caused by: libcore.io.ErrnoException: bind failed: EADD
RINUSE (Address already in use)
E/AndroidRuntime(10902):        at libcore.io.Posix.bind(Native Method)
E/AndroidRuntime(10902):        at libcore.io.ForwardingOs.bind(ForwardingOs.jav
a:39)
E/AndroidRuntime(10902):        at libcore.io.IoBridge.bind(IoBridge.java:87)
E/AndroidRuntime(10902):        ... 18 more
W/ActivityManager(  268): Error in app com.att.myWireless running instrumentatio
n ComponentInfo{com.att.myWireless.test/sh.calaba.instrumentationbackend.Calabas
hInstrumentationTestRunner}:
W/ActivityManager(  268):   libcore.io.ErrnoException
W/ActivityManager(  268):   libcore.io.ErrnoException: bind failed: EADDRINUSE (
Address already in use)
I/ActivityManager(  268): Force stopping package com.att.myWireless uid=10069
I/ActivityManager(  268): Killing proc 10902:com.att.myWireless/10069: force sto
p
E/rmt_storage(  173): rmt_storage write event
E/rmt_storage(  173): rmt_storage events processing done
E/rmt_storage(  173): unblock rmt_storage client thread
E/rmt_storage(  173): BEGIN: rmt_storage_client_thread
E/rmt_storage(  173): write: fd = 0xc, buf = 0x40293000,num_sector = 6143
E/rmt_storage(  173): rmt_storage fop(1): bytes transferred = 3145216
E/rmt_storage(  173): write: fd = 0xc, buf = 0x40592e00,num_sector = 1
E/rmt_storage(  173): rmt_storage fop(1): bytes transferred = 512
E/rmt_storage(  173): END: rmt_storage_client_thread
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e5d, Prog: 31000000, Vers: d17
ed9ea, Proc: 00000014
D/QCRIL_RPC(  106): Enter qcril_cm_srvsys_event_callback
D/QCRIL_RPC(  106): Exit qcril_cm_srvsys_event_callback
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e5d
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e5d
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e5d
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e5d
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e5d
D/QCRIL_RPC(  106): Enter qcril_sms_cfg_event_callback
D/QCRIL_RPC(  106): Exit qcril_sms_cfg_event_callback
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e5e, Prog: 31000003, Vers: cf0
d42a3, Proc: 00000003
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e5e
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e5e
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e5e
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e5e
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e5e
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e5f, Prog: 31000003, Vers: cf0
d42a3, Proc: 00000003
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e5f
D/QCRIL_RPC(  106): Enter qcril_sms_cfg_event_callback
D/QCRIL_RPC(  106): Exit qcril_sms_cfg_event_callback
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e5f
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e5f
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e5f
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e5f
W/SignalStrength(  434): SignalStrength before validate=SignalStrength: 9 255 -1
 -1 -1 -1 -1 99 -32767 -32767 -32767 -32767 cdma
W/SignalStrength(  434): SignalStrength after validate=SignalStrength: 9 255 -12
0 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 -32767 cdma
D/QCRIL_RPC(  106): Enter qcril_cm_phonesvc_command_callback
D/QCRIL_RPC(  106): Exit qcril_cm_phonesvc_command_callback
D/QCRIL_RPC(  106): Enter qcril_cm_event_command_callback
D/QCRIL_RPC(  106): Exit qcril_cm_event_command_callback
D/QCRIL_RPC(  106): Enter qcril_cm_phonesvc_event_callback
D/QCRIL_RPC(  106): Exit qcril_cm_phonesvc_event_callback
I/ONCRPC  (  106): Setup RPC Call for task 40340420
I/ONCRPC  (  106): oncrpc_xdr_call_msg_start: Prog: 30000000, Ver: f4fc28c3, Pro
c: 000000b8
I/ONCRPC  (  106): xdr_std_msg_send_call: Sent Xid: 2d9, Prog: 30000000, Ver: f4
fc28c3, Proc: 000000b8
I/ONCRPC  (  106): xdr_std_msg_send_call: Received Reply Xid: 2d9, Prog: 3000000
0, Ver: f4fc28c3, Proc: 000000b8
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e60, Prog: 31000000, Vers: d17
ed9ea, Proc: 00000005
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e60
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e60
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e60
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e60
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e60
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e61, Prog: 31000000, Vers: d17
ed9ea, Proc: 00000011
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e61
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e61
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e61
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e61
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e61
I/ONCRPC  (  106): Setup RPC Call for task 40340420
I/ONCRPC  (  106): oncrpc_xdr_call_msg_start: Prog: 30000000, Ver: f4fc28c3, Pro
c: 000000b8
I/ONCRPC  (  106): xdr_std_msg_send_call: Sent Xid: 2da, Prog: 30000000, Ver: f4
fc28c3, Proc: 000000b8
D/QCRIL_RPC(  106): Enter qcril_cm_phonesvc_command_callback
D/QCRIL_RPC(  106): Exit qcril_cm_phonesvc_command_callback
D/QCRIL_RPC(  106): Enter qcril_cm_event_command_callback
D/QCRIL_RPC(  106): Exit qcril_cm_event_command_callback
D/QCRIL_RPC(  106): Enter qcril_cm_phonesvc_event_callback
D/QCRIL_RPC(  106): Exit qcril_cm_phonesvc_event_callback
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e62, Prog: 31000000, Vers: d17
ed9ea, Proc: 00000005
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e62
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e62
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e62
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e62
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e62
I/ONCRPC  (  106): xdr_std_msg_send_call: Received Reply Xid: 2da, Prog: 3000000
0, Ver: f4fc28c3, Proc: 000000b8
I/Diag_Lib(  106): rpc_handle_rpc_call: for Xid: 2e63, Prog: 31000000, Vers: d17
ed9ea, Proc: 00000011
I/Diag_Lib(  106): rpc_handle_rpc_call: Find Status: 0 Xid: 2e63
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 2e63
I/ONCRPC  (  106): oncrpc_xdr_reply_msg_start: Prog: 00000000, Ver: 00000000, Pr
oc: 00000000 Xid: 00002e63
I/ONCRPC  (  106): oncrpc_msg_reply: Prog: 00000000, Ver: 00000000, Proc: 000000
00 Xid: 00002e63
I/ONCRPC  (  106): oncrpc_proxy_handle_cmd_rpc_call: Dispatch returned for xid:
2e63
I/MSimTelephonyRegistry(  268): notifyServiceState: 0 home TATA DOCOMO  405037
EDGE CSS not supported -1 -1 mDataState=0 RoamInd=-1 DefRoamInd=-1 EmergOnly=fal
se
D/yanghong(  341): onServiceStateChanged,data-radio=2,sub=0
W/SignalStrength(  341): getLTELevel - rsrp:2147483647 snr:2147483647 rsrpIconLe
vel:-1 snrIconLevel:-1
W/SignalStrength(  341): getLTELevel - rssi:99 rssiIconLevel:0
W/SignalStrength(  341): getGsmLevel=3
W/SignalStrength(  341): getLevel=3
D/yanghong(  341): radio=2
D/yanghong(  341): updateAttachedNetwork,radio=2 type=1 sub=0
D/StatusBar.MSimNetworkController(  341): updateTelephonySignalStrength: subscri
ption =0
D/StatusBar.MSimNetworkController(  341): updateDataNetType subscription =0mData
NetType =2
D/StatusBar.MSimNetworkController(  341): updateDataIcon subscription =0
D/StatusBar.MSimNetworkController(  341): updateDataIcon dataSub =0
D/StatusBar.MSimNetworkController(  341): updateDataIcon  when SimState =UNKNOWN

D/StatusBar.MSimNetworkController(  341): updateDataIcon  when gsm mMSimState =U
NKNOWN
D/StatusBar.MSimNetworkController(  341): updateDataIcon when mMSimDataConnected
 =false
D/StatusBar.MSimNetworkController(  341): refreshViews subscription =0mMSimDataC
onnected =false
D/StatusBar.MSimNetworkController(  341): refreshViews mMSimDataActivity =0
D/StatusBar.MSimNetworkController(  341): refreshViews: SUB:0 - Data not connect
ed!! Set no data type icon
V/MSimPhoneApp(  434): Action intent recieved:android.intent.action.SERVICE_STAT
E

**Comment by TobiasRoikjer** [comment]
bind failed: EADDRINUSE (Address already in use)  means that someone else is already listening on the port. Try rebooting your device or change the test-server port
