### ISSUE TITLE
Errno::EACCES Permission Denied 

### ISSUE THREAD

**Issue by mbnetobr** [calabash/calabash-android#525]
Hi Guys,

I'm have this problem with permission when run the tests with calabash. You have ideias?

The command:
calabash-android run MyApk.apk --tags @MyTag

The log error:
C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.2/lib/calabash-android/helpers.rb:28:in ``': Permission denied - "C:/Android/android-sdk/platform-tools/aapt" dump xmltree "C:/Users/MyPath/MyApk.apk" AndroidManifest.xml (Errno::EACCES)
 from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.2/lib/calabash-android/helpers.rb:28:in `rescue in main_activity'
 from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.2/lib/calabash-android/helpers.rb:17:in `main_activity'
 from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.2/bin/calabash-android-run.rb:20:in `calabash_run'
 from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.2/bin/calabash-android:85:in `<top (required)>'
 from C:/Ruby193/bin/calabash-android:23:in `load'
 from C:/Ruby193/bin/calabash-android:23:in `<main>'

**Comment by TobiasRoikjer** [comment]
@mbnetobr It seems like a misconfiguration with the file permissions. Does executing `"C:/Android/android-sdk/platform-tools/aapt" dump xmltree "C:/Users/MyPath/MyApk.apk" AndroidManifest.xml` in your cmd fail as well? If so, it is not a problem with Calabash, but your andorid-ask installation.

**Comment by TobiasRoikjer** [comment]
Closed due to inactivity
