### ISSUE TITLE
Unable to run apk using calabash

### ISSUE THREAD

**Issue by mcmug8** [calabash/calabash-android#526]
Please help, I am not able to run apk using calabash. Below is the error. Thank you!

2015-01-31 01:52:40 - JDK found on PATH.
2015-01-31 01:52:40 - JDK found at: C:\Program Files\Java\jdk1.8.0_31
2015-01-31 01:52:40 - Android SDK found at: C:\Users\timtim\AppData\Local\Androi
d\sdk
No test server found for this combination of app and calabash version. Recreatin
g test server.
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry.rb:470:in `=
=': undefined method `dos_equals' for nil:NilClass (NoMethodError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry
_set.rb:61:in `=='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry
_set.rb:61:in `=='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:334:in `!='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:334:in `commit_required?'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:300:in `commit'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:325:in `close'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:101:in `open'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:138:in `foreach'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:140:in `block (2 levels) in fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:137:in `chdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:137:in `block in fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:136:in `fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/bin/
calabash-android-build.rb:2:in `calabash_build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:92:in `build_test_server_if_needed'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/bin/
calabash-android-run.rb:16:in `calabash_run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/bin/
calabash-android:85:in `<top (required)>'
        from C:/Ruby200-x64/bin/calabash-android:23:in `load'
        from C:/Ruby200-x64/bin/calabash-android:23:in `<main>'

**Comment by phamxuanha90** [comment]
I guess you don't have any test server for your application, to create new one, use this command: calabash-android build <your_apk_name,apk>. Hope it would help.
Regards.

**Comment by mcmug8** [comment]
Hi,

Thank you for helping. I am now facing a new error. Seems like still complaining about undefined methoddos_equals' for nil:NilClass (NoMethodError). Do I need to prepare the apk with calabash before it works?

Thanks,


error:

 undefined method `dos_equals' for nil:NilClass (NoMethodError)
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entr
t.rb:61:in `=='
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entr
t.rb:61:in `=='
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file
334:in `!='
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file
334:in `commit_required?'
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file
300:in `commit'
     from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file
325:in `close'

**Comment by TobiasRoikjer** [comment]
@mcmug8 It seems like an issue in rubyzip. You could try downgrading rubyzip or search fork known issues on windows running your version

**Comment by tpetsas** [comment]
Did you find what was the issue?
