### ISSUE TITLE
Support for Webdialog

### ISSUE THREAD

**Issue by Scorcherer** [calabash/calabash-android#527]
I am testing an app which needs facebook login. and facebook has upgraded its sdk so it provides webdialog instead of webview. While doing query("webView css:'*'") i am getting an empty array

**Comment by TobiasRoikjer** [comment]
I think you are misunderstanding the query syntax. If the class has changed from webView to webDialog, `query("webView css:'*'")` matches nothing. You should use `query("webdialog css:'*'")` instead.

**Comment by Scorcherer** [comment]
thanks for the reply but i tried that too i am getting empty array

**Comment by TobiasRoikjer** [comment]
Whats is the result of running  `query("*")` and what does `current_activity` return.

**Comment by Scorcherer** [comment]
`current_activity` return "LoginActivity" and output of `query("*")`
`[
    [0] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "com.android.internal.policy.impl.PhoneWindow$DecorView",
                      "rect" => {
            "center_y" => 592,
            "center_x" => 360,
              "height" => 1184,
                   "y" => 0,
               "width" => 720,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "com.android.internal.policy.impl.PhoneWindow$DecorView{423715e8 V.E..... R....... 0,0-720,1184}"
    },
    [1] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "android.widget.LinearLayout",
                      "rect" => {
            "center_y" => 592,
            "center_x" => 360,
              "height" => 1184,
                   "y" => 0,
               "width" => 720,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "android.widget.LinearLayout{4237e220 V.E..... ........ 0,0-720,1184}"
    },
    [2] {
                        "id" => "content",
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "android.widget.FrameLayout",
                      "rect" => {
            "center_y" => 617,
            "center_x" => 360,
              "height" => 1134,
                   "y" => 50,
               "width" => 720,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "android.widget.FrameLayout{4237fec0 V.E..... ........ 0,50-720,1184 #1020002 android:id/content}"
    },
    [3] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "android.widget.FrameLayout",
                      "rect" => {
            "center_y" => 617,
            "center_x" => 360,
              "height" => 1134,
                   "y" => 50,
               "width" => 720,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "android.widget.FrameLayout{423961f8 V.E..... ........ 0,0-720,1134}"
    },
    [4] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "android.widget.LinearLayout",
                      "rect" => {
            "center_y" => 617,
            "center_x" => 360,
              "height" => 1134,
                   "y" => 50,
               "width" => 720,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "android.widget.LinearLayout{423693f8 V.E..... ........ 0,0-720,1134}"
    },
    [5] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => "Web View",
                     "class" => "com.facebook.widget.WebDialog$3",
                      "rect" => {
            "center_y" => 617,
            "center_x" => 360,
              "height" => 1074,
                   "y" => 80,
               "width" => 660,
                   "x" => 30
        },
                       "tag" => nil,
               "description" => "com.facebook.widget.WebDialog$3{42371f58 VFED..C. .F...... 30,30-690,1104}"
    },
    [6] {
                        "id" => nil,
                   "enabled" => true,
        "contentDescription" => nil,
                     "class" => "android.widget.ImageView",
                      "rect" => {
            "center_y" => 79,
            "center_x" => 29,
              "height" => 59,
                   "y" => 50,
               "width" => 58,
                   "x" => 0
        },
                       "tag" => nil,
               "description" => "android.widget.ImageView{42ab41f0 V.ED..C. ........ 0,0-58,59}"
    }
]`

**Comment by TobiasRoikjer** [comment]
The class of the new web dialog is not WebDialog, it is com.facebook.widget.**WebDialog$3** the **$3** is important. You can match it by its class, but I would go for a matching content description: `query("* marked:'Web View' css:'*'")`
