### ISSUE TITLE
https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/canned_steps.md

### ISSUE THREAD

**Issue by RefuX** [calabash/calabash-android#535]
Why are the canned steps different from the iOS ones? Or why are the iOS steps different than the Android ones?

https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/features/step_definitions/calabash_steps.rb

**Comment by jmoody** [comment]
Cross-posted.

Find the answer here.

**Why are the Calabash iOS and Calabash Android pre-defined steps different?** [#701](https://github.com/calabash/calabash-ios/issues/701)
