### ISSUE TITLE
ClearAppData deletes all AccountManager accounts

### ISSUE THREAD

**Issue by jhansche** [calabash/calabash-android#538]
Invoking `clear_app_data` (which invokes the `ClearAppData` instrumentation runner) causes the app to delete all known accounts on the device -- not just the accounts that belong to the application.  This can be problematic when 1) you're testing against a personal device (ask me how I discovered this ¬_¬), or 2) you need to test situations where Google accounts exist on the device, which *most* real-user devices will have.

I propose that:

1. ClearAppData **should not** touch the AccountManager at all (or should only delete the accounts that match the app's package name);  and
2. A *separate* `InstrumentationTestRunner` is created and invoked that takes an argument for the `accountType`, and only deletes the accounts via [`getAccountsByType(accountType)`](http://developer.android.com/reference/android/accounts/AccountManager.html#getAccountsByType(java.lang.String))

This approach also allows you to delete multiple account types, or override the account type that you want to delete.  I.e., my application's Authenticator account type *does not match* my application's package name.  But I do not want the TestRunner to delete all other accounts, like Google and Facebook, etc.

Many uses of the AccountManager require requesting the `MANAGE_ACCOUNTS` permission, and this results in the AccountManager happily letting the TestRunner call `removeAccount()`, even for accounts that the application does not own or manage.

**Comment by TobiasRoikjer** [comment]
@jhansche I appreciate your proposals. I agree that ClearAppData should never remove 3rd party accounts, but the implementation might be hard. @jmoody Do you have any input on a similar feature for iOS? As far as I remember, we can remove the app sandbox and reset the simulators.

One approach might be to discard that action all together, and instead use the adb call `adb shell pm clear <package>`. This method does not exist in Android < 2.3 though, which means that Froyo (2.2) would not be fully supported, as it is now. 

As for the ability to delete multiple accounts, I believe that having a separate endpoint which, given an account type (package), will delete that particular one. This would make the test-server more generic, and it would have less data to bookkeep.

**Comment by sherbhachu** [comment]
I believe this may be a regression with the 0.5x version of Calabash-Android, or something to do with the Android SDK itself, I have devices that I used to run this command on all the time and my google contacts, etc would all still be there, his was certainly true with Android 2x.-4.x when running calabash-android 0.4.x

But I do see the same behaviour that @jhansche has mentioned...but I cant say it happens all the time, but its certainly frequent.

There is a downside of removing the package...you'll need to re-install the app between tests, which is considerably slower than clearing the app data.

**Comment by TobiasRoikjer** [comment]
@sherbhachu In Android 2.x it was not necessarily possible to delete an account (for instance, a device has to be reset completely if you want to remove a Google Account). If we look at the code for ClearAppData.java, we can see the following:
```java
            final AccountManager manager = AccountManager.get(getTargetContext());
            final Account[] accounts = manager.getAccounts();

            for (Account account : accounts) {
                try {
                    manager.removeAccount(account, null, null);
                } catch (Exception e) {
                    System.out.println("Unable to remove " + account.name + " of type " + account.type);
                }
```

It currently uses `manager.getAccounts` which "Lists all accounts of any type registered on the device." The file has not been changed since Dec. 2012.

**Comment by jmoody** [comment]
> Do you have any input on a similar feature for iOS? As far as I remember, we can remove the app sandbox and reset the simulators.

For physical devices, no.  For simulators, we have a way to:

1.  reset all the simulators.
2.  reset a specific simulator.

With respect to simulators:  as of Xcode 6, we haven't been able to reset an app's content and data because there is no logical mapping from an app's bundle to its sandbox (content and data).

For devices, users must manually manage the app (and its data) or use a third-party tool like `libimobiledevice`.

**Comment by jhansche** [comment]
Due to this behavior, I have removed all calls to `clear_app_data`, and replaced them with calls to `adb shell pm clear <package_name>`.  For my use case, I don't need to support Froyo, so I am okay with `pm clear` being 2.3+.

I skip reinstall as often as possible, because it is so slow (my APK is almost 20MB), so I actually test if the app is installed before using `reinstall_apps`.  The side effect of keeping my app's accounts on the device are minimal, so so far that hasn't been an issue either;  but I'm sure at some point I'm going to want to test the state of having no app accounts, and/or having a specific set of accounts listed.  For now, my approach is working.

**Comment by TobiasRoikjer** [comment]
@jhansche I see. You should be able to use `pm clear` for now by using
```ruby
`#{default_device.adb_command} shell pm clear #{package_name(default_device.app_path))}`
```

**Comment by jhansche** [comment]
@TobiasRoikjer yup, that's what I'm doing currently

**Comment by TobiasRoikjer** [comment]
@jhansche As an update to this, you can use the [ClearAppData2](https://github.com/calabash/calabash-android/blob/master/ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/ClearAppData2.java) activity instead. It only clears the app-owned accounts

**Comment by jhansche** [comment]
@TobiasRoikjer what are the chances that will become the default behavior for {{clear_app_data}}?

**Comment by TobiasRoikjer** [comment]
@jhansche It is the default behaviour in Calabash 2.0, I don't think it will change for 0.x

**Comment by TobiasRoikjer** [comment]
@jhansche Did ClearAppData2 work well for you?

**Comment by jhansche** [comment]
@TobiasRoikjer I haven't tried it, as we have been skipping the `clear_app_data` call and instead use the equivalent of `adb shell pm clear <package>` between scenarios.  The downside is that also clears any previously granted permissions (in Marshmallow), so we also have to re-grant permission either using `pm` or testing the actual permission flow.

I never did get a chance to look into switching to the other activity.  Would it just involve overriding the `clear_app_data` method to send it to a different instrumentation command, or does it also require rebuilding the test server APK?

I don't work much on the Android test suite these days, but I can pass along information to those who are, and report back

**Comment by TobiasRoikjer** [comment]
@jhansche Yes, exactly. You could overwrite the method like this (or do something similar)
```ruby
module Calabash; module Android; module Operations; class Device
  def clear_app_data
    cmd = "#{adb_command} shell am instrument #{package_name(@test_server_path)}/sh.calaba.instrumentationbackend.ClearAppData2"
    raise "Could not clear data" unless system(cmd)
  end
end; end; end; end
```

**Comment by darkash** [comment]
I have tried this option, it also deletes all AccountManager accounts, not sure if this is a behavior caused by using custom rom or the newer android OS as it does not happen on my other older device which still runs jelly bean.

clearappdata2 doesnt seem to fix the issue as well, so I just work it around by disabling clear_app_data and replace it with reinstall_apps. This might prolong the test time, but it may worth the effort for anyone stumbling across this problem like me.
