### ISSUE TITLE
WebView support in Lollipop

### ISSUE THREAD

**Issue by ehro** [calabash/calabash-android#539]
When I perform a query (in a WebView, of course) like "query("webView css:'*'")" using Android 5.0.1 the result is "[]".

Previous versions (Android <5.0) work fine.

Please, can you update Calabash libraries to recognize these identifiers?

**Comment by sherbhachu** [comment]
Are you saying that you could never get this to work on Lollipop at all?

**Comment by ehro** [comment]
I tried in Nexus 4 (5.0.1). It seems that there's no support to Lollipop.

**Comment by sherbhachu** [comment]
Hmm, I have a working project using a Genymotion simulator (version 5.0.0)
... you might want to give that a shot? You could be right, something
introduced in 5.0.1 has possibly broken something.

**Comment by ehro** [comment]
Unfortunately, using Genymotion (Nexus 5 - 5.0.0) and the same app, show the same result.

My app has a button that calls Facebook API (WebView). I want to automate Facebook logon from Calabash.

**Comment by TobiasRoikjer** [comment]
@ehro The most likely scenario is that the simple name of your web view is **not** WebView. You are most likely running into an issue with your class specifiers like #527. Try executing `query("android.webkit.WebView")`. Does this give any results?

**Comment by sherbhachu** [comment]
Could you try using UIAutomator viewer tool, that comes with the android-sdk and visually inspect the UI, as Tobias says, WebView may not even exist, not sure if doing query("*") would tell you what types of views exist , in terms of 'webviews'

**Comment by ehro** [comment]
@sherbhachu UIAutomator doesn't show the specifics "WebView" elements that I'm looking for, only the class "android.webkit.WebView".

@TobiasRoikjer You're right! Your query returns the class com.facebook.widget.WebDialog$3 (how describred in #527)

When I typed query("* marked:'Web View' css:'*'") I was able to inspect the elements.

@TobiasRoikjer  and @sherbhachu, thank you for your help!

**Comment by icolina15** [comment]
I have tried using query("android.webkit.WebView") and it returns an array but what I want to do is to enter text to the username and password field in the facebook dialog. Any help would be much appreciated.

**Comment by bguina** [comment]
@icolina15
> enter_text("android.webkit.WebView css:'input[name=\"email\"]'", email)
> enter_text("android.webkit.WebView css:'input[name=\"pass\"]'", pass)
> touch "android.webkit.WebView css:'button[name=\"login\"]'"

**Comment by icolina15** [comment]
@bguina Thank you for your help!
