### ISSUE TITLE
Not able to run multiple application in the same device  

### ISSUE THREAD

**Issue by disha-sharma** [calabash/calabash-android#542]
hi
i am trying to launch 2 application one after another. first application(.apk1) is launched successfully. but the secound one doesn't. 
no error message is generated and the .apk2 is installed in the device. but it is not able to start.

**Comment by sherbhachu** [comment]
post the code you are executing and the error messages.

**Comment by disha-sharma** [comment]
I have calabash-android-java1.5.0
Here is my code-
public boolean launchapp(String apk) {
 try {
	System.out.println("Start");
	 AndroidConfiguration androidConfiguration = new AndroidConfiguration();
    	androidConfiguration.setSerial("emulator-5554");
                AndroidRunner androidRunner = new AndroidRunner(apk,
			  androidConfiguration);
	androidRunner.setup(); 
	AndroidApplication application = androidRunner.start();
                return true;
}catch (CalabashException e) {		
                e.printStackTrace();
                return false;
}
}

I am calling this method twice one after another passing different arguement(.apk path)

**Comment by disha-sharma** [comment]
no error message is genarated. for 1st application it is getting launched successfully. but 2nd application is getting launched.

**Comment by sherbhachu** [comment]
I am wondering if you may have only a single driver instance, or something
to that affect.

I am assuming both apks have different package names, etc?

If you have two command terminals and run the calabash-android console
xxxx.apk in each, is that working?

Is the launch error occuring when you are trying to run cucumber/RSpec
tests?

**Comment by TobiasRoikjer** [comment]
@disha-sharma Calabash-Java is not developed or maintained by the Calabash team. You should create an issue in the relevant github page. I believe it is [this one](https://github.com/vishnukarthikl/calabash-android-java)
