### ISSUE TITLE
get_activity_name fails if the launch activity immediately starts a different activity before Solo (robotium) is initialized

### ISSUE THREAD

**Issue by jhansche** [calabash/calabash-android#546]
The issue is similar to that described in https://code.google.com/p/robotium/issues/detail?id=179. I haven't tried the workaround suggested in that issue, but the latest comment also suggests that the way it works has been changed as of 5.2.1.  Calabash currently uses robotium-solo version 4.3.1, which was released in 2013.

This causes tests to fail if using something like `wait_for_activity(..)` to wait until the expected 2nd activity is launched.  On the screen/emulator, you can see the expected activity, and using `adb shell dumpsys window windows` also shows the expected activity.  Yet `get_activity_name` still returns the initial launch activity.  Sometimes it works, but very often it is failing.

**Comment by jhansche** [comment]
I tried using the workaround in the linked robotium issue, but that did not actually fix the issue.

So the next attempt is going to be updating robotium to 5.3.1.  I've tried dozens of times to reproduce the bug (still trying), and so far have not run into it.

**Comment by jhansche** [comment]
Turns out even with Robotium 5.3.1, I am still seeing the same behavior -- much more pronounced on an emulator (x86 Lollipop) than on a device.

I created a sample Android project at <https://github.com/MeetMe/robotium-179> and added the information to the robotium link at the top of this issue.  The sample project has a "LaunchActivity" that starts "SecondActivity" during onResume().  The only step in the feature is to `I wait for the "SecondActivity" screen to appear`.  The step times out and fails because `get_activity_name` continues to report "LaunchActivity" even though "SecondActivity" is visible on screen.

**Comment by TobiasRoikjer** [comment]
@jhansche Thank you very much for investigating this so extensively and reporting your findings, we really appreciate support from the community! Is the method `current_activity` sufficient? We should probably remove the action `get_activity_name` as it is redundant. 

I have noticed that Robotium has a hard time retrieving the right activity, which we need sometimes to grab a context in the test server. We have used workarounds in places that needed it.

**Comment by jhansche** [comment]
@TobiasRoikjer I hadn't noticed that `current_activity` existed, but yes, that's almost identical to the line that I use for my `get_focused_activity`.  That one does work.  Just the Robotium/Solo approach does not work in the scenario above (launch activity starts a new activity before the robotium instrumentation is fully initialized).

**Comment by jhansche** [comment]
Also see #341

**Comment by jhansche** [comment]
@TobiasRoikjer was this actually fixed?  wait_for_activity() still uses the broken get_activity_name.  If your suggestion is to use `current_activity`, why isn't the `wait_for_activity()` using it...?

**Comment by jhansche** [comment]
Here's an excerpt of some of the overrides we use:
```
      # Replaces {Calabash::Android::Operations#current_activity} with one that enforces UTF-8 encoding.
      def current_activity
        `#{default_device.adb_command} shell dumpsys window windows`
                                                                    .force_encoding('UTF-8')
                                                                    .each_line
                                                                    .grep(/mFocusedApp.+[\.\/]([^.\s\/\}]+)/) { $1 }
                                                                    .first
      end

      # Waits until the current activity is something other than `activity_name`.
      #
      # @param activity_name [String]
      # @param options [Hash]
      def wait_for_not_activity(activity_name, options = {})
        options[:timeout_message] ||= "Timeout waiting for activity #{activity_name} to go away"

        wait_for(options) do
          current_activity.force_encoding("UTF-8") != activity_name
        end

        log "Not on #{activity_name} anymore; new activity: #{current_activity}"
      end

      # Replaces the {Calabash::Android::WaitHelpers#wait_for_activity} method with a version that
      # uses {Calabash::Android::Operations#current_activity} instead of `get_activity_name`.
      #
      # @param activity_name [String]
      # @param options [Hash]
      def wait_for_activity(activity_name, options = {})
        options[:timeout_message] ||= "Timeout waiting for activity #{activity_name}"
        wait_for_any_activity [activity_name], options
      end

      # Waits for the current activity to match any of the given names.
      #
      # @param activity_names [Array<String>]
      # @param options [Hash]
      def wait_for_any_activity(activity_names, options = {})
        options[:timeout_message] ||= "Timeout waiting for one of activities: #{activity_names}"
        c = 0

        wait_for(options) do
          c += 1
          log "Still waiting...  current activity = #{current_activity}" if c % 5 == 0
          # Wait for the current activity to be one of the activity_names
          activity_names.include? current_activity.force_encoding("UTF-8")
        end
      end
```

**Comment by TobiasRoikjer** [comment]
@jhansche No, wait_for_activity still uses the "wrong" method. We should fix that.
