### ISSUE TITLE
screenshot_embed into method's class its not visible at format html

### ISSUE THREAD

**Issue by gitwillian** [calabash/calabash-android#552]
I'm passing the screenshot_embed into method's class, but the screenshot it don't visible at format html. My example code:

class MyClass
	include Calabash::Android::Operations	 
	def my_method()			
	  screenshot_embed({:prefix => "reports/", :name =>"screenshot_evidence", :label =>"..."})
      end
end

When its out of the class, its ok!

**Comment by TobiasRoikjer** [comment]
@gitwillian Please always supply what version of Calabash you are using, this issue should already be fixed in the most recent release.

**Comment by gitwillian** [comment]
version: 5.4

tks

**Comment by TobiasRoikjer** [comment]
@gitwillian please update to 0.5.8

**Comment by gitwillian** [comment]
@TobiasRoikjer now its ok... thanks
