### ISSUE TITLE
Could not remove the keyguard issue on first test

### ISSUE THREAD

**Issue by tejasv02** [calabash/calabash-android#553]
I am using calabash Android with Genymotion (Galaxy S5) 

I have a test suite with 5 tests, When I execute to tests on GO server.
my first test keeps failing to remove key gaurd, rest of the tests seem ok 
calabash-android version 0.5.7

Adding relevant logs below:

Starting: Intent { act=android.intent.action.MAIN cmp=com.xxx.test/sh.calaba.instrumentationbackend.WakeUp }
 Could not remove the keyguard (RuntimeError)
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/calabash-android-0.5.7/lib/calabash-android/operations.rb:559:in `block in wake_up'
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/calabash-android-0.5.7/lib/calabash-android/operations.rb:558:in `wake_up'
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/calabash-android-0.5.7/lib/calabash-android/operations.rb:582:in `start_test_server_in_background'
 /Users/go/.rvm/gems/ruby-2.2.0@global/gems/calabash-android-0.5.7/lib/calabash-android/operations.rb:125:in `start_test_server_in_background'
 /Applications/GoAgent-3.app/pipelines/MOBILE.SANITY/source/ui-automation/features/android/support/app_life_cycle_hooks.rb:20:in `Before'

**Comment by TobiasRoikjer** [comment]
I suggest disabling keyguard on your devices entirely. The general purpose ways of unlocking devices are limited.
