### ISSUE TITLE
Clicking elements in a Crosswalk webview not working - for specific devices

### ISSUE THREAD

**Issue by istvanbb** [calabash/calabash-android#562]
I am trying to click an element in a Crosswalk webview:
```ruby
touch("org.xwalk.core.internal.XWalkContent css:'button' {textContent CONTAINS 'Show more'}")
```
Execution of the code is successful, but the clicking does not happen. If I query the same element, the query is successful. I tried also perform_action('touch_coordinate',x,y), the click is also lost.

I am using Calabash 0.5.8. I know that Calabash is supporting Crosswalk from 0.5.6. I have no problems with queries, but it seems that touch events are not working still.

**Comment by istvanbb** [comment]
I just realised that the problem occurs for specific devices.
I created a sample app and sample test: https://github.com/madarasz/XWalkCalabash

I'm using Genymotion emulators and my results are:
* Google Nexus 6 - 5.1.0 - API 22 - **FAILS**
* Google Nexus 9 - 5.0.0 - API 21 - **FAILS**
* Google Nexus 5 - 5.0.0 - API 21 - **PASSES**
* Samsung Galaxy S5 - 4.4.4 - API 19 - **PASSES**
* Motorola Moto X - 4.4.4 - API 19 - **FAILS**
* Samsung Galaxy S4 - 4.3 - API 18 - **PASSES**
* HTC EVO - 4.2.2 - API 17 - **FAILS**
* Samsung Galaxy S3 - 4.1.1 - API 16 - **FAILS**

These passes/fails are consistent, I have repeated the tests several times, got the same results.

**Comment by TobiasRoikjer** [comment]
@istvanbb Thank you very much for your investigation. Could you compile an apk and add it to the repository (or upload it somewhere) as well?

**Comment by madarasz** [comment]
Yep, I uploaded it.

**Comment by TobiasRoikjer** [comment]
@madarasz Your query uses 'button' as the class. Running the app, the class of the 'Show more' text is 'a' (a link). You should turn on visual touches in the developer options, and see if Calabash touches the screen.

**Comment by madarasz** [comment]
@TobiasRoikjer Please note that my initial one-liner example and the sample app I provided is different.
I click an 'a' link in the Calabash code: https://github.com/madarasz/XWalkCalabash/blob/master/features/step_definitions/calabash_steps.rb#L12
This matches the 'a' link in the html code: https://github.com/madarasz/XWalkCalabash/blob/master/app/src/main/assets/index.html#L14

Could you recheck? Thank you!
(the visual touch option is a nice idea tough, I will try it out)

**Comment by TobiasRoikjer** [comment]
@madarasz This issue should have been fixed in 0.5.9. Can you verify this is the case?

**Comment by madarasz** [comment]
It works, thank you!

**Comment by TobiasRoikjer** [comment]
@madarasz Great. I'll close this issue

**Comment by lummyare** [comment]
Hi i just found this link and i have been having same issue all along.
Can any of you guys help me with any sample repo for XWalk or links to how i can query the calabash andorid using XWalkView. I really need your help please help me out
