### ISSUE TITLE
Having an android:enabled="false" activity before the enabled one returns error

### ISSUE THREAD

**Issue by tfcardoso** [calabash/calabash-android#565]
Apparently there is a problem with the parser. If we have a disabled activity before the enabled one it doesn't work.

So this scheme on AndroidManifest.xml returns error:
   
    <activity android:enabled="false" android:excludeFromRecents="true" android:icon="@drawable/c_cp_icon_launcher" android:label="XXXX" android:name="com.XXXXXX.MainActivity" android:noHistory="true" android:screenOrientation="nosensor" android:taskAffinity="com.XXXXX">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:configChanges="keyboardHidden|orientation|screenSize" android:launchMode="singleTop" android:name="com.XXXXXX" android:screenOrientation="portrait">
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT"/>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

If we switch the order of activities then its works properly.

Error is:

    irb(main):001:0> reinstall_apps
    1117 KB/s (26345656 bytes in 23.021s)
    1308 KB/s (556200 bytes in 0.415s)
    nil
    irb(main):002:0> start_test_server_in_background

    RuntimeError: Unable to make connection to Calabash Test Server at http://127.0.0.1:34780/
    Please check the logcat output for more info about what happened

	from /home/tester/.rvm/gems/ruby-2.0.0-p247/gems/calabash-android-0.4.20/lib/calabash-android/operations.rb:525:in `rescue in start_test_server_in_background'
	from /home/tester/.rvm/gems/ruby-2.0.0-p247/gems/calabash-android-0.4.20/lib/calabash-android/operations.rb:508:in `start_test_server_in_background'
	from /home/tester/.rvm/gems/ruby-2.0.0-p247/gems/calabash-android-0.4.20/lib/calabash-android/operations.rb:93:in `start_test_server_in_background'
	from (irb):2
	from /home/tester/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'
    irb(main):003:0>

**Comment by TobiasRoikjer** [comment]
@tfcardoso This is interesting. Does the logcat output anything?

**Comment by TobiasRoikjer** [comment]
@tfcardoso Also, could you please post the output of ENV['MAIN_ACTIVITY'] ?

**Comment by tfcardoso** [comment]
from logcat:

    W/ActivityManager(  511): Error in app com.XXXX running instrumentation ComponentInfo{com.XXXX.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}:
    W/ActivityManager(  511):   java.lang.RuntimeException
    W/ActivityManager(  511):   java.lang.RuntimeException: Unable to resolve activity for: Intent { flg=0x10000000 cmp=com.XXXX/com.XXXX.phone.activity.MainActivity (has extras) }
    I/ActivityManager(  511): Force stopping package com.XXXX appid=10007 user=0

Replacing real package name...When can I see ENV['MAIN_ACTIVITY']?

**Comment by TobiasRoikjer** [comment]
In the console

**Comment by tfcardoso** [comment]
it identifies the wrong main activity. It mentions the one that was in enabled="false"

**Comment by TobiasRoikjer** [comment]
@tfcardoso good.  Please write
```ruby
ARGV << '-v'
main_activity(ENV['APP_PATH'])
```

What does it output?

**Comment by tfcardoso** [comment]
irb(main):002:0> ARGV << '-v'
    [
        [0] "--readline",
        [1] "--prompt-mode",
        [2] "simple",
        [3] "-v"
    ]

And for the second command, it returns same activity as before (the disabled one)

**Comment by TobiasRoikjer** [comment]
@tfcardoso It's not the returned output. It should output something in the console as a log

**Comment by tfcardoso** [comment]
Then I doing something wrong. This is exactly what appears on console

    irb(main):003:0> ARGV << '-v'
    [
        [0] "--readline",
        [1] "--prompt-mode",
        [2] "simple",
        [3] "-v"
    ]
    irb(main):004:0> reinstall_apps
    2015-04-22 15:01:52 - connected_devices: ["HT238W102620"]
    2015-04-22 15:01:52 - "/home/tester/android/adt-bundle-linux-x86_64-20130522/sdk/platform-tools/adb" -s HT238W102620 forward tcp:34780 tcp:7102
    2015-04-22 15:01:53 - 
    2015-04-22 15:01:53 - Uninstalling: com.XXX
    2015-04-22 15:01:55 - Success
    2015-04-22 15:01:55 - Installing: /home/tester/test-automation/tests/basic-test/XXX.apk
    1304 KB/s (26345656 bytes in 19.715s)
    2015-04-22 15:02:25 - 	pkg: /data/local/tmp/XXX.apk
    Success
    2015-04-22 15:02:27 - Uninstalling: com.vodafone.messaging.test
    2015-04-22 15:02:28 - Success
    2015-04-22 15:02:28 - Installing: test_servers/6e995d639c63aa23af4419cd91847f31_0.4.20.apk
    1312 KB/s (556200 bytes in 0.413s)
    2015-04-22 15:02:31 - 	pkg: /data/local/tmp/6e995d639c63aa23af4419cd91847f31_0.4.20.apk
    Success
    nil
    irb(main):005:0> main_activity(ENV['APP_PATH'])
    "com.XXX.XX.phone.activity.MainActivity"
    irb(main):006:0>

**Comment by TobiasRoikjer** [comment]
@tfcardoso what version of Calabash android are you using?

**Comment by TobiasRoikjer** [comment]
@tfcardoso Also, it seems your output was not properly censored. If you want to avoid leaking info, you can email me instead. I will delete this message.

**Comment by tfcardoso** [comment]
A very old one :) 0.4.20 Current tests are not prepared for newest version.

About the current issue, I updated calabash-android to latests, but it was still happening. After I downgraded it again.

**Comment by TobiasRoikjer** [comment]
@tfcardoso You should run the newest version of Calabash unless something prevents you from doing that. The output should appear in the newest version of calabash

**Comment by tfcardoso** [comment]
Tobias reach the conclusion that it is the android tool aapt that it is not updated. 

So will close. Thanks for support
