### ISSUE TITLE
Chromium ContentView support

### ISSUE THREAD

**Issue by xander-filonenko** [calabash/calabash-android#568]
Do you have any plans adding Chromium ContentView support?

Our app is fork from Chromium. To fully cover it with automation tests, we need to work with JellyBeanContentView as with regular WebView. The issue is that org.chromium.content.browser.JellyBeanContentView doesn't inherit from android.webkit.WebView, so it's not recognised as valid WebView:
```
irb(main):023:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass)
[
    [0] "org.chromium.content.browser.JellyBeanContentView"
]
irb(main):024:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass, :getSuperclass)
[
    [0] "org.chromium.content.browser.ContentView"
]
irb(main):025:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass, :getSuperclass, :getSuperclass)
[
    [0] "android.widget.FrameLayout"
]
irb(main):026:0> query("org.chromium.content.browser.JellyBeanContentView css:'a'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map org.chromium.content.browser.JellyBeanContentView css:'a', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.chromium.content.browser.JellyBeanContentView is not recognized a valid web view.
```

**Comment by TobiasRoikjer** [comment]
@xander-filonenko Is the method to evaluate javascript works, we could easily support your webview type. Is it possible for you to send me a sample project that uses this webview class?

**Comment by Omont** [comment]
Hi Guys, 
Did you have a chance how to fix it? have exactly the same problem
