### ISSUE TITLE
Query for Button no longer works when using 22.1.1 support library widgets

### ISSUE THREAD

**Issue by zmarkan** [calabash/calabash-android#571]
It's because they revamped the support library to add tinting etc. It is now an instance of AppCompatButton.

https://chris.banes.me/2015/04/22/support-libraries-v22-1-0/

Changing queries to use android.widget.Button works for now, but it's less readable.

**Comment by TobiasRoikjer** [comment]
@zmarkan Querying for a class in Calabash-Android works in two ways:

- If given a simple name (e.g. the name 'button' from the fully qualified name 'com.example.button'), Calabash returns all views that have that simple name (case insensitive). 
```
query("button") => ['com.example.Button', 'android.widget.Button']
```

- If given a fully qualified name, Calabash-Android returns any views that are instances of that class, **or  inherit from that class**
```
query("android.widget.Button") => [AppCompatButton, CompoundButton, RadioButton etc.]
```

Using classnames is generally not the best approach if your views are uniquely identified, which is great is possible. Consider reducing the clutter by unique identifying your views by giving them a unique id or contentDescription, and use the wildcard token to avoid filtering by class name.
E.g.
```
query("* marked:'my-identifier'")
```

**Comment by TobiasRoikjer** [comment]
@zmarkan I am closing this issue for now. Feel free to comment if you believe this is not expected behaviour.

**Comment by zmarkan** [comment]
Ok, thanks for this explanation @TobiasRoikjer. It's probably worth updating the readme/ruby api documentation to reflect this, as I suppose other people could have similar issues.
