### ISSUE TITLE
Reports dont load screenshots when directory default is changed

### ISSUE THREAD

**Issue by mbnetobr** [calabash/calabash-android#572]
When i'm change directory of the reports, screenshots are not loaded.

My run commmand:

calabash-android run apks/my.apk --tags @mytag --format html --out reports/mytag.html

The report is visible with layout brokened when link to open screenshot is tapped

ps: I'm think the problem occurs only on windows

**Comment by TobiasRoikjer** [comment]
This is a Cucumber problem. Cucumber is the default runner for a Calabash test. I suggest reporting this issue in the Cucumber Ruby repository.
