### ISSUE TITLE
Potential memory leak in CalabashInstrumentationTestRunner

### ISSUE THREAD

**Issue by jhansche** [calabash/calabash-android#574]
This leak was discovered by [LeakCanary](https://github.com/square/leakcanary/issues/93#issuecomment-102175312)

```
LaunchActivity has leaked:
In local.myapp:1.0:1.
* local.myapp.activity.LaunchActivity has leaked:
* GC ROOT thread android.app.Instrumentation$InstrumentationThread.<Java Local> (named 'Instr: sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner')
* leaks local.myapp.activity.LaunchActivity instance

* Reference Key: 0c2aa3f1-01a3-46a0-9b05-69bce43c152f
* Device: samsung samsung SM-G900H k3gxx
* Android Version: 4.4.2 API: 19
* Durations: watch=5009ms, gc=230ms, heap dump=1214ms, analysis=20690ms
```

Workaround to suppress reporting the leak every time:
```java
AndroidExcludedRefs.createAndroidDefaults()
                .thread("Instr: sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner")
                .instanceField("sh.calaba.instrumentationbackend.InstrumentationBackend", "mActivity")
                .build()
```

**Comment by TobiasRoikjer** [comment]
@jhansche Can you comment further on this?

**Comment by jhansche** [comment]
There's not really much to add...  The `InstrumentationBackend#mActivity` field ends up leaking the initial launch activity, because it doesn't recognize that the activity has changed -- possibly because the activity changes immediately.  So it keeps a reference to that activity even after the activity has finished.  Seems like it may be due to (and potentially fixed by?) #341 -- but you just recently closed that as a non-issue.  

Ultimately it's not really a big deal because it's only leaking during instrumentation runs;  but a leak is a leak, so that's why I reported it at all.

**Comment by TobiasRoikjer** [comment]
@jhansche Ah, if that PR fixes the issue I'm entirely up for merging it.

**Comment by jmoody** [comment]
PR referenced by this issue:

**Create Solo before starting first activity** #341

has been closed (not merged).

Can we close this issue?

**Comment by TobiasRoikjer** [comment]
Fixed with complete changes to the calabash  life cycle in 0.8.0.pre1
