### ISSUE TITLE
How to trigger touch on Android's dialog (not from the app)

### ISSUE THREAD

**Issue by ozexpert** [calabash/calabash-android#577]
Hi, my application shows a dialog when connecting to VPN. 
On Lollipop, it shows a dialog (confirmation box) with "CANCEL" or "OK" button. 

I need to trigger "OK" button. However, when `query("*")`, I get empty list when the dialog pops up. 
Is there a way to detect the dialog from Android and perform a touch event?

**Comment by ozexpert** [comment]
Dialog is similar to this... 

![image](https://cloud.githubusercontent.com/assets/787164/7825897/38fcd61a-03c7-11e5-8c6f-f28f0be891cb.png)

However, on Android < 5.x version, it shows a checkbox to trust the application.

**Comment by TobiasRoikjer** [comment]
@ozexpert Calabash-Android does not support interacting directly with any 3rd party app. There are multiple ways of doing this, but it is a solution not using Calabash.

A 'hacky' solution (which I do not necessarily recommend) is to dump the view hierarchy using uiautomator, locating the coordinates of the OK button, and pressing them using `adb shell tap x y`

**Comment by ozexpert** [comment]
So how can i trigger "adb shell tab x y" inside of calabash (cucumber)? can you give me an example code?

**Comment by shimatai** [comment]
@ozexpert You should add the following code to your calabash_steps.rb

`Then (/^I tap in (\d+) (\d+)$/) do |x, y|`
`  system("#{default_device.adb_command} shell input tap #{x} #{y}");`
`end`

So all you gotta do is to declare a sentence in your feature file, for example:

`Then I tap in 60 415`
