### ISSUE TITLE
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encodi ng::CompatibilityError)

### ISSUE THREAD

**Issue by if1else0** [calabash/calabash-android#581]
With version 0.5.10.pre2, when I run script on Windows 7, it had errors, but it worked fine on mac, could you have a look and fix it, thanks. @TobiasRoikjer 

error messages as below:

  * features/android/pages/mine_setting_page.rb
  * features/android/pages/qa_home_page.rb
  * features/android/pages/qa_personalinfo_page.rb
  * features/android/pages/qa_question_answer_add_page.rb
  * features/android/pages/qa_questiondetail_page.rb
  * features/android/pages/qa_questionsadd_page.rb
  * features/android/pages/qa_questionscontactstree_page.rb
  * features/android/pages/qa_questionsinvite_page.rb
  * features/android/pages/qa_search_page.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/common_steps.rb
  * features/step_definitions/home_steps.rb
  * features/step_definitions/login_steps.rb
  * features/step_definitions/qa_homepage_steps.rb
  * features/step_definitions/qa_questionsadd_steps.rb
  * features/step_definitions/qa_questionscontractstree_steps.rb
  * features/step_definitions/qa_questionsinvite_steps.rb

Features:
WARNING: cannot load such file -- 2.1/gherkin_lexer_en
Couldn't load 2.1/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/bin/../lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/diff-lcs-1.2.5/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/gherkin-2.12.2
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_test-0.1.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.7/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/escape-0.0.4/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.10.pre2/lib
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/site_ruby
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/vendor_ruby
C:/Ruby21-x64/lib/ruby/2.1.0
C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32. Reverting to Ruby lexer.
WARNING: cannot load such file -- 2.1/gherkin_lexer_zh_cn
Couldn't load 2.1/gherkin_lexer_zh_cn
The $LOAD_PATH was:
lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/bin/../lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/diff-lcs-1.2.5/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/gherkin-2.12.2
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_test-0.1.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.7/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/escape-0.0.4/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.10.pre2/lib
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/site_ruby
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/vendor_ruby
C:/Ruby21-x64/lib/ruby/2.1.0
C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32. Reverting to Ruby lexer.
WARNING: cannot load such file -- 2.1/gherkin_lexer_en
Couldn't load 2.1/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/bin/../lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/diff-lcs-1.2.5/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/gherkin-2.12.2
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/multi_test-0.1.2/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/slowhandcuke-0.0.3/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.7/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/escape-0.0.4/lib
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.10.pre2/lib
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/site_ruby
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0
C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0/x64-msvcrt
C:/Ruby21-x64/lib/ruby/vendor_ruby
C:/Ruby21-x64/lib/ruby/2.1.0
C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32. Reverting to Ruby lexer.
  * features/qa_questionsadd.feature
Parsing feature files took 0m0.071s

Using the android profile...
#language: zh-CN
功能: 问答社区-发布问题
  这里主要提供多学应用问答社区提问模块的场景定义
  这里还可以添加其他你想添加的内容，只要不是关键字就可以了

  @automated
  场景: WDTW_1-功能入口                          # features\qa_questionsadd.feat
ure:7
2015-06-02 14:26:53 - connected_devices: ["192.168.56.101:5555"]
2015-06-02 14:26:53 - "D:\android-sdk/platform-tools/adb.exe" -s 192.168.56.101:
5555 forward tcp:34778 tcp:7102
2015-06-02 14:26:53 -
2015-06-02 14:26:53 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:26:53 - Uninstalling: com.eln.base.test
2015-06-02 14:26:54 - Success

2015-06-02 14:26:54 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:26:54 - Uninstalling: com.eln.base
2015-06-02 14:26:56 - Success

2015-06-02 14:26:56 - Installing: test_servers/2f265b20a2dda494e13cee33df14d4db_
0.5.10.pre2.apk
2301 KB/s (562271 bytes in 0.238s)
2015-06-02 14:26:58 -   pkg: /data/local/tmp/2f265b20a2dda494e13cee33df14d4db_0.
5.10.pre2.apk

Success

2015-06-02 14:26:58 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:26:58 - Installing: D:/Qa/bdd_dev_branch/AUT/v13.apk
4544 KB/s (11071206 bytes in 2.379s)
2015-06-02 14:27:03 -   pkg: /data/local/tmp/v13.apk

Success

2015-06-02 14:27:03 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:27:04 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:27:04 - Trying to find launchable activity
2015-06-02 14:27:04 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:27:04 - Found launchable activity 'com.eln.base.ui.LoginAct'
2015-06-02 14:27:04 - Found tools directory at 'D:/android-sdk/build-tools/21.1.
1'
2015-06-02 14:27:04 - Starting test server using:
2015-06-02 14:27:04 - "D:\android-sdk/platform-tools/adb.exe" -s 192.168.56.101:
5555 shell am instrument -e target_package com.eln.base -e main_activity com.eln
.base.ui.LoginAct -e test_server_port 7102 -e class sh.calaba.instrumentationbac
kend.InstrumentationBackend com.eln.base.test/sh.calaba.instrumentationbackend.C
alabashInstrumentationTestRunner
2015-06-02 14:27:04 - Checking if instrumentation backend is ready
2015-06-02 14:27:04 - Is app running? true
2015-06-02 14:27:04 - Instrumentation backend not yet ready
2015-06-02 14:27:07 - Checking if instrumentation backend is ready
2015-06-02 14:27:07 - Is app running? true
2015-06-02 14:27:07 - Instrumentation backend is ready!
2015-06-02 14:27:07 - Checking client-server version match...
2015-06-02 14:27:07 - Action: version - Params:
2015-06-02 14:27:08 - Result:'{"bonusInformation":[],"message":"0.5.10.pre2","su
ccess":true}'
2015-06-02 14:27:08 - Client and server versions match (client: 0.5.10.pre2, ser
ver: 0.5.10.pre2). Proceeding...
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encodi
ng::CompatibilityError)
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
egexp_argument_matcher.rb:7:in `match'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
egexp_argument_matcher.rb:7:in `arguments_from'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
b_step_definition.rb:89:in `arguments_from'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
b_language.rb:52:in `block in step_matches'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
b_language.rb:51:in `map'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/r
b_language.rb:51:in `step_matches'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:157:in `block in matches'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:156:in `map'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:156:in `matches'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:144:in `step_match_without_cache'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:138:in `step_match'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:6
9:in `step_match'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_inv
ocation.rb:83:in `find_step_match!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_inv
ocation.rb:56:in `invoke'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_inv
ocation.rb:38:in `accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:106:in `block in visit_step'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:170:in `broadcast'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:105:in `visit_step'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_col
lection.rb:19:in `block in accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_col
lection.rb:18:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_col
lection.rb:18:in `accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:100:in `block in visit_steps'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:170:in `broadcast'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:99:in `visit_steps'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:15:in `block in execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:8
3:in `block (2 levels) in with_hooks'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:9
9:in `before_and_after'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:8
2:in `block in with_hooks'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:120:in `call'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:120:in `block (3 levels) in around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/language_sup
port/language_methods.rb:9:in `block in around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/language_sup
port/language_methods.rb:97:in `call'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/language_sup
port/language_methods.rb:97:in `execute_around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/language_sup
port/language_methods.rb:8:in `around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:119:in `block (2 levels) in around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:123:in `call'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime/supp
ort_code.rb:123:in `around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:9
4:in `around'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:8
1:in `with_hooks'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:13:in `execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario
.rb:32:in `block in accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario
.rb:79:in `with_visitor'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario
.rb:31:in `accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:58:in `block in visit_feature_element'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:170:in `broadcast'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:57:in `visit_feature_element'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.
rb:38:in `block in accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.
rb:37:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.
rb:37:in `accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:27:in `block in visit_feature'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:170:in `broadcast'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:26:in `visit_feature'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/features
.rb:28:in `block in accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/features
.rb:17:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/features
.rb:17:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/features
.rb:27:in `accept'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:21:in `block in visit_features'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:170:in `broadcast'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_wal
ker.rb:20:in `visit_features'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:4
9:in `run!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:
47:in `execute!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/cucumber-1.3.19/bin/cucumber:13:in `<top
(required)>'
C:/Ruby21-x64/bin/cucumber:23:in `load'
C:/Ruby21-x64/bin/cucumber:23:in `<main>'

D:\Qa\bdd_dev_branch>

**Comment by TobiasRoikjer** [comment]
@if1else0 Please do not tag any unrelated people in your issues. The Calabash team monitors these issues anyway :)

**Comment by if1else0** [comment]
@TobiasRoikjer   Got it.

**Comment by TobiasRoikjer** [comment]
This is a cucumber issue. Try update your version of Cucumber. It is outside the scope of Calabash.
