### ISSUE TITLE
Does calabash support rhomobile application

### ISSUE THREAD

**Issue by motobhakta** [calabash/calabash-android#582]
Does this support rhomobile application? I have tried to run with a sample rhomobile application.
But its getting crashed on launch.

Below is the crash log

I/ActivityManager(  622): Process com.rhomobile.appgallerytest (pid 22733) has died.
W/ActivityManager(  622): Crash of app com.rhomobile.appgallerytest running instrumentation ComponentInfo{com.rhomobile.appgallerytest.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}
I/ActivityManager(  622): Force stopping com.rhomobile.appgallerytest appid=10217 user=0: finished inst
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=29)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=28)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=29)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Diag_Lib(22756): qpLogDiagInit ==>
E/Diag_Lib(22756): qpLogDiagInit <== result : 1
E/Diag_Lib(22756): [IMS_QMID] |imsqmiserver.c | 493 | QMID#$$#0#QMI DAEMON STARTED
E/Diag_Lib(22756): [IMS_QMID] |imsqmiserver.c | 503 | ims-qmi-daemon main entry getgid: 3e9
E/Diag_Lib(22756): [IMS_QMID] |imsqmiserver.c | 509 | ims-qmi-daemon: Failed to get the socket fd from init script, name ims_qmid
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=30)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=29)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=28)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)
E/Sensors (  622): Event: type=3(ABS=3,SYN=0 ), code=40 (EVT_L=40), value=26)
E/Sensors (  622): Event: type=0(ABS=3,SYN=0 ), code=0 (EVT_L=40), value=0)

**Comment by TobiasRoikjer** [comment]
@motobhakta Please post your Calabash-Android version.

**Comment by motobhakta** [comment]
calabash-android (0.5.9)

**Comment by TobiasRoikjer** [comment]
@motobhakta where can I download the sample app? Which device are you testing on?

**Comment by motobhakta** [comment]
You can find a sample rhomobile app available at https://drive.google.com/file/d/0B2xWdk8ImJVSNURENlE5T25Memc/view?usp=sharing

I have tried it on Moto G device.
Mostly below command fails to start application.

"/Users/home/android/android-sdk/sdk//platform-tools/adb" -s TA2342234 shell am instrument -e target_package com.rhomobile.calabash -e main_activity com.rhomobile.rhodes.RhodesActivity -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend com.rhomobile.calabash.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
  App did not start (RuntimeError)

**Comment by TobiasRoikjer** [comment]
Calabash does not current support this type of application.
