### ISSUE TITLE
JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY 

### ISSUE THREAD

**Issue by Goginenni** [calabash/calabash-android#586]
Operations on web view doesn't work if Android has latest 'Android System Webview' apk. Calabash-android report the following error,

W/System.err(14472): Caused by: java.lang.RuntimeException: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token
W/System.err(14472):  at [Source: java.io.StringReader@3c5095b7; line: 1, column: 1]
W/System.err(14472):    at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$MapWebContainer.call(UIQueryUtils.java:337)
W/System.err(14472):    at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$MapWebContainer.call(UIQueryUtils.java:290)
W/System.err(14472):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(14472):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err(14472):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(14472):    at android.os.Looper.loop(Looper.java:135)
W/System.err(14472):    at android.app.ActivityThread.main(ActivityThread.java:5312)
W/System.err(14472):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14472):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(14472):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
W/System.err(14472):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
W/System.err(14472): Caused by: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token
W/System.err(14472):  at [Source: java.io.StringReader@3c5095b7; line: 1, column: 1]
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:212)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:246)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2765)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1903)

the workaround for this error is downgrade the Android System Webview to the previous version.

1. Go to Settings -> App
2. Tap on Android System WebView
3. Tap on Uninstall Updates.

**Comment by sapieneptus** [comment]
Resolved by #592, available via the latest ruby gem (`0.5.12.pre1`).
