### ISSUE TITLE
Could not list certificates in keystore issue

### ISSUE THREAD

**Issue by gitamsinghkaystha** [calabash/calabash-android#588]
hi i m trying to setup calabash on my windows 7, x-64 machine..

this is my command prompt write up:

C:\Users\gitam.kaystha\calabashg>calabash-android resign Gaana_Uninstall.apk -v
2015-06-15 18:33:28 - JDK found on PATH.
2015-06-15 18:33:28 - JDK found at: C:\Program Files\Java\jdk1.7.0_21
2015-06-15 18:33:28 - Android SDK found at: C:\Android\sdk
2015-06-15 18:33:28 - Resign apk
2015-06-15 18:33:29 - Found tools directory at 'C:/Android/sdk/build-tools/21.1.
2'
2015-06-15 18:33:29 - Found tools directory at 'C:/Android/sdk/build-tools/21.1.
2'
2015-06-15 18:33:29 - Keystore location specified in .calabash_settings.
2015-06-15 18:33:29 - Reading keystore data from keystore file 'D:/key'
2015-06-15 18:33:29 - "\Program Files\Java\jdk1.7.0_21\bin/keytool.exe" -list -v
 -alias gaana -keystore D:/key -storepass times@123 "-J"-Dfile.encoding=utf-8""
"-J"-Duser.language=en-US""
2015-06-15 18:33:31 - Could not list certificates in keystore. Probably because
the password was incorrect.
C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/calabash-android
/java_keystore.rb:32:in `initialize': Could not list certificates in keystore. P
robably because the password was incorrect. (RuntimeError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/java_keystore.rb:108:in `new'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/java_keystore.rb:108:in `keystore_from_settings'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/java_keystore.rb:87:in `get_keystores'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/helpers.rb:133:in `sign_apk'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/helpers.rb:112:in `block in resign_apk'
        from C:/Ruby200/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/lib/cal
abash-android/helpers.rb:106:in `resign_apk'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.10/bin/cal
abash-android:114:in `<top (required)>'
        from C:/Ruby200/bin/calabash-android:23:in `load'
        from C:/Ruby200/bin/calabash-android:23:in `<main>'

this is my folder structure:

![image](https://cloud.githubusercontent.com/assets/3761131/8160466/78de30b4-138d-11e5-93a8-3011ad6c5769.png)
 
and my keystore is in the d drive

**Comment by TobiasRoikjer** [comment]
The keystore file 'D:/key' seems invalid. What are the contents of .calabash_settings?
