### ISSUE TITLE
Calabash Android - I'm struggling to fix - undefined method `embed' for "447590087100":String (NoMethodError)

### ISSUE THREAD

**Issue by americapires1** [calabash/calabash-android#590]
Hi, my name is America Pires and I'm new to Calabash android. Calabash-android version 0.5.5
I have the fallowing on my feature, step definitions and on my EnterNumberScreen class as shown below. This was working before (it would populate the phone number text filed with the number on the feature, however, now i keep getting the error as shown further down below).
I have tried so many things but I'm stuck on this error. 
Any advice would be much appreciated. 

Thank you.

Feature 

 @1.01
  Scenario Outline: Enter valid phone number      
    When I enter <valid_phone_number>   # this is line 9
  Examples:Valid phone numbers
    | valid_phone_number |
    | 07590087100        |

Step Definition 

When(/^I enter (.*)$/) do |valid_phone_number| 
  valid_number = EnterNumberScreen.new(valid_phone_number) 
  valid_number.enter_phone_number(valid_phone_number)       # this is line 8
end

Method on my EnterNumberScreen Class

    def enter_phone_number_field
         "* id:'register_enternumber_edittext'"
       end

  def enter_phone_number(phone_number) 
    wait_for_elements_exist(enter_phone_number_field,timeout:2)      # this is line 36
    keyboard_enter_text(phone_number)
  end

ERROR

Examples: Valid phone numbers
      | valid_phone_number |
      | 447590087100       |
      undefined method `embed' for "447590087100":String (NoMethodError)
      ./features/Classes/enter_number_class.rb:36:in `enter_phone_number'
      ./features/Step_definitions/enter_number_steps.rb:8:in `/^I enter (.*)$/'
      features/Features/enter_number.feature:9:in `When I enter <valid_phone_number>'

**Comment by TobiasRoikjer** [comment]
@americapires1 Please always remember to inform us of your calabash version. We cannot possibly debug anything without this information :)

**Comment by americapires1** [comment]
Hi TobiasRoikjer,
Thank you...
The Calabash-android version is 0.5.5

**Comment by TobiasRoikjer** [comment]
@americapires1 Have you tried updating to the latest version?

**Comment by americapires1** [comment]
Nope. I will do that and see.

**Comment by americapires1** [comment]
Hi TobiasRoikjer, 

I have updated my calabash to 0.5.10 
And the error persists this time it says: Timeout waiting for elements: * id:'register_enternumber_edittext' (Calabash::Android::WaitHelpers::WaitError).

However, I have just figured out what the problem was.....

I had only one element on feature:
Examples:Valid phone numbers
| valid_phone_number |
| 07590087100 |

and used    wait_for_elements_exist() rather than wait_for_element_exists()

Thank you TobiasRoikjer, at least with the updated calabash version gave me a clear error message.

**Comment by americapires1** [comment]
Hi TobiasRoikjer,

Its very weird as when i changed wait_for_elements_exist() to wait_for_element_exists() it passed, however the second time when i run it, it went back to the same error as above (Timeout waiting for elements: * id:'register_enternumber_edittext' (Calabash::Android::WaitHelpers::WaitError).

Not sure what is wrong.

**Comment by TobiasRoikjer** [comment]
I'm assuming that particular element did not appear?

**Comment by americapires1** [comment]
Yes it (07590087100 ) did not appear on the screen. 

and i get:

Timeout waiting for elements: * id:'register_enternumber_edittext' (Calabash::Android::WaitHelpers::WaitError)
      ./features/Classes/enter_number_class.rb:31:in `enter_phone_number'
      ./features/Step_definitions/enter_number_steps.rb:8:in `/^I enter (.*)$/'
      features/Features/enter_number.feature:9:in `When I enter <valid_phone_number>'

**Comment by americapires1** [comment]
I query * id:'register_enternumber_edittext'  and its correct, corresponds to the right text field.

**Comment by TobiasRoikjer** [comment]
@americapires1 Could you please post all relevant code?

**Comment by americapires1** [comment]
Hi Tobias, 
Sorry for late reply, i was off.

Thank you so much for your support. I really appreciate it. For some reason after a month I have just reinstall the app and restarted the server and when run the apk file it worked fine and did not give me any more error, so not sure what was happening. Maybe after updating the calabash version to to 0.5.10, I should have reinstalled the app I guess.
