### ISSUE TITLE
org.chromium.content.browser.JellyBeanContentView

### ISSUE THREAD

**Issue by Omont** [calabash/calabash-android#593]
Hi guys have simillar problem to #568
Our app is fork from Chromium. To fully cover it with automation tests, we need to work with JellyBeanContentView as with regular WebView. The issue is that org.chromium.content.browser.JellyBeanContentView doesn't inherit from android.webkit.WebView, so it's not recognised as valid WebView:

irb(main):023:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass)
[
    [0] "org.chromium.content.browser.JellyBeanContentView"
]
irb(main):024:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass, :getSuperclass)
[
    [0] "org.chromium.content.browser.ContentView"
]
irb(main):025:0> query("org.chromium.content.browser.JellyBeanContentView", :getClass, :getSuperclass, :getSuperclass)
[
    [0] "android.widget.FrameLayout"
]
irb(main):026:0> query("org.chromium.content.browser.JellyBeanContentView css:'a'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map org.chromium.content.browser.JellyBeanContentView css:'a', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.chromium.content.browser.JellyBeanContentView is not recognized a valid web view

Also i've tried to manage with 

query("webView", :stringByEvaluatingJavaScriptFromString => 'org.chromium.content.browser.JellyBeanContentView')

but as a result it gives me empty array
can you help me with it?

**Comment by TobiasRoikjer** [comment]
Can you send an example of an app using this kind of webview?

**Comment by Omont** [comment]
any custom app based on chromium browser.
For example if i used query "*" for chrome browser i'm able to see
                     "class" => "org.chromium.content.browser.ContentView",
                       "tag" => nil,
               "description" => "org.chromium.content.browser.ContentView{7408668 VFE...C. .F......
0,0-1440,2304}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 2304,
               "width" => 1440,
                   "y" => 88,
                   "x" => 0,
            "center_x" => 720,
            "center_y" => 1240
        },
                   "enabled" => true,
        "contentDescription" => "\u0412\u0435\u0431-\u0432\u0435\u0440\u0441\u0456\u044F"
    },

Unable to attach it as it's more then 10 MB (actually 32 MB)

**Comment by Omont** [comment]
able to share via dropbox
https://www.dropbox.com/s/3bu4kktg7e4u786/chrome.apk?dl=0

**Comment by Omont** [comment]
any progress?

**Comment by TobiasRoikjer** [comment]
@Omont The view org.chromium.content.browser.ContentView in your example app has no method to load a URL or evaluate Java Script.
