### ISSUE TITLE
Formatter affects success of test cases

### ISSUE THREAD

**Issue by Maxiplexi** [calabash/calabash-android#597]
Hi,

I'm using **calabash-android 0.5.12** on **ruby 2.2.0**.

I have a feature file that looks like this:

```gherkin
Feature: Login feature

  Background:
    Given I am on the Login page

  Scenario: Successful login
    When I enter valid credentials
    Then I should be able to login successfully

  Scenario Outline: Cannot login with password less the 2 characters
    When I enter a <password> that is less than 2 characters long
    Then I should not be able to login

    Examples:
    |password|
    |a       |
    |b       |
```

The Background step calls `@current_page = page.await(LoginPage)` and then the steps in the scenarios call methods specific to @current_page (instance variable used here to illustrate).

This all works perfectly when using the `--format 'Slowhandcuke::Formatter'` option. However, the first example of the Scenario Outline always fails when some other formatter such as `--format pretty` or `--format 'Cucumber::Formatter::Html'` is used.

The error is that the background step is not executed completely, so `@current_page.class` is NilClass when the first example is executed, but it is successfully set to LoginPage by the time the second example is executed. This only occurs for Scenario Outlines. When I replace this with multiple Scenarios, they all run without a hitch.

Could we please look into this issue further? Or, if anyone has advice on how to get around this problem, please let me know.

Thank you.

**Comment by bret** [comment]
From your description, this seems like it would be an issue with cucumber and its formatters and not really related to Calabash. Can you reproduce the issue (not calling the background step) using just Cucumber?

**Comment by TobiasRoikjer** [comment]
This is a cucumber issue
