### ISSUE TITLE
Could not execute command to start test server <RuntimeError>

### ISSUE THREAD

**Issue by alpersilistre** [calabash/calabash-android#599]
I install calabash with guide on [Xamarin site](http://developer.xamarin.com/guides/testcloud/calabash/configuring/windows/installing-gems/). I install calabash gems manually and at the 8 step, I came across an issue on installing calabash. Then I solve it with --verbose at the end of the command. Then I face with gherkin issue like [this post](https://github.com/cucumber/gherkin/issues/320#issuecomment-119602221) I managed to solve it and now when I start my test, I follow a error and my test will fail immediately. I give INTERNET permission.

![error](https://cloud.githubusercontent.com/assets/6996763/8593470/aa3bfa36-2640-11e5-9697-0228c443fb54.jpg)

I have Wİndows 8.1 pro and using latest ruby and gems. 

I will be happy if anyone can help me on this. Thank you.

Edit : It is same if I use calabash-android build <apk> before running.

**Comment by TobiasRoikjer** [comment]
@alpersilistre Please post the relevant part of `adb logcat`. It should tell you why it failed.

**Comment by alpersilistre** [comment]
@TobiasRoikjer Can you be more specific about relevant part of adb logcat.I have no knowledge about it. Where should I look ?
Thank you.

**Comment by Rulta** [comment]
@alpersilistre Cucumber is not compatible with Ruby 2.2 yet.

**Comment by alpersilistre** [comment]
I manage to start calabash finally on Ruby 2.1.6. Thanks for responds.
