### ISSUE TITLE
Request for Uiquery Documentation.

### ISSUE THREAD

**Issue by iMerica** [calabash/calabash-android#605]
Typically in Ruby public interfaces, complex method parameters like `uiquery` would be a hash of key/value params. Since Calabash uses a string for `uiquery`, it would be very helpful if there were docs on how it should be constructed.  Including a list of all possible filters and parameters.

Currently the documentation is very light. From the [Query section](https://github.com/calabash/calabash-android/blob/master/documentation/ruby_api.md#query):

>
> query(uiquery, *args)

> Query returns an array of its results. The query function gives powerful query capability from your test code. You can find views and other application objects, and make assertions about them or extract data from them.

> Calabash Android tries to return results that carry useable information by default. For view objects this includes coordinates, class and contentdescription:

> irb(main):002:0> query("button index:1")
=> [{"id"=>"save", "enabled"=>true, "contentDescription"=>nil, "class"=>"android.widget.Button", "text"=>"Save

The uiquery `button index:1` is used, but it's not defined anywhere. What else can we do other than `button`? Should the structure be: `<thing> <filter>:<filter_option> ` ? As long as *some* documentation is hosted on this repo, it should be complete and include everything people need to know to use this tool. Otherwise it's more helpful to link to the most exhaustive docs available.

**Comment by iMerica** [comment]
It turns out there was documentation for this hidden in the Wiki, but there were no links to get to it. I've submitted  https://github.com/calabash/calabash-android/pull/607 to address this.

**Comment by TobiasRoikjer** [comment]
Closed with PR merge.
