### ISSUE TITLE
Cucumber, calabash and separation of concerns.

### ISSUE THREAD

**Issue by iMerica** [calabash/calabash-android#606]
Hey guys,

Cucumber is a BDD tool for automating acceptances tests. It's agnostic about what code gets executed in its steps. For the most part it only cares about parsing features, running necessary test code (steps files) and reporting results. You can use it to test HTTP backends using `rest-client` or automate browser interactions using the `selenium` gem. It's always clear where cucumber ends and the test code begins.

Calabash's unique value proposition is that it handles all things related to native device automation (taps, touches, swipes, input etc on iOS and Android). Calabash has however included Cucumber into itself. This is mostly helpful except for one thing: It's not clear where cucumber ends and calabash begins and vice versa.

What happens when we run this?

     calabash-android run path/to/my.apk features -t  @foobar

We know that cucumber eventually executes the test code for scenario `@foobar`, but what happens before that? Any supporting documentation you guys can add about this topic would be greatly appreciated for both using this tool and contributing back to this codebase.

Kind regards,

Michael

**Comment by TobiasRoikjer** [comment]
@iMerica We have started explaining Calabash as 

 > Calabash is an API written in Ruby that enables you to automate Android and iOS mobile devices & simulators, and native or hybrid apps.

However,
 > The Calabash gem also contains CLI tools to ease automation

For Android, this includes:
 - A console
 - A way of resigning an APK
 - A way of build a test-server for an APK
And some Cucumber specific helpers such as:
 - A way of generating a cucumber skeleton
 - A way of running a cucumber test

`calabash-android run <apk> [params]` is basically equivalent to running

```
calabash-android build <apk>
APP_PATH=<apk> TEST_APP_PATH=<ts_path> cucumber [params]
```

**Comment by TobiasRoikjer** [comment]
We are even talking about removing the cucumber dependency from calabash in 2.0
https://github.com/calabash/calabash/pull/88

**Comment by iMerica** [comment]
Very cool @TobiasRoikjer :+1:
