### ISSUE TITLE
sliding down the notification bar in calabash android

### ISSUE THREAD

**Issue by suresh02** [calabash/calabash-android#608]
how to slide down the notification bar in android mobile using calabash android

**Comment by suresh02** [comment]
Please do comment i am struck in the middle

**Comment by TobiasRoikjer** [comment]
Calabash is a tool designed to test your own application, not 3rd party (like the notification bar). It is generally not a good idea to UI test an OS component, as it is rendered vastly differently by the OS.

You can use commands like `adb -s x dumpsys notification` to view the notifications the OS is showing.
