### ISSUE TITLE
Reproducible: Calabash query is unreliable on Samsung Galaxy S5 running Android 5.0

### ISSUE THREAD

**Issue by sleekweasel** [calabash/calabash-android#610]
I observe query() returning different values on repeated calls querying the same (static) screen.

Code like this: 
    wait_for { !query(@@own_profile_textview).empty? || scroll_down() }
    touch(@@own_profile_textview)

Sometimes fails in touch() with 'No such element' without the wait_for timing out; sometimes it fails on the first query, resulting in the top element scrolling off the top of the screen forever. I have also seen the 'Continue' button of a system query not being pressed.

I see similar Lollipop-related reports here: http://grokbase.com/t/gg/calabash-android/154wfzh9jc/query-flakiness-on-lolipop-devices and here: http://grokbase.com/t/gg/calabash-android/154qjkz3vk/problems-testing-on-nexus-6-queries-are-empty-sometimes

Although the second report connects the issue with on-screen animations, the screens I see this occurring on don't have animations running.

**Comment by sleekweasel** [comment]
I have a reproducible example of this:
1. Download Badoo from Google market
2. Sign in
3. Tap the top left menu button
4. Run this command in the console:
{} while query("* id:'drawerProfile_name'").count == 1
5. Wiggle your finger on the menu to scroll it up and down - making sure not to lose the username from the top.
6. The query returns null after about 40 seconds here: https://vid.me/lO3zfailing despite the view never vanishing from the screen.
7. I tried about 3 times to get this.

**Comment by TobiasRoikjer** [comment]
@sleekweasel I have released a new version of Calabash-Android that might fix this. Could you please try this gem: https://rubygems.org/gems/calabash-android/versions/0.5.15.coordinate.pre.fix2

**Comment by TobiasRoikjer** [comment]
I'm closing this issue due to lack of response. The issue appears to have been totally fixed for a while now (user can no longer reproduce).
Released in: https://rubygems.org/gems/calabash-android/versions/0.6.0
Fixed in: https://github.com/calabash/calabash-android-server/pull/7
