### ISSUE TITLE
"calabash-android run my_app.apk command does not initiate script execution.

### ISSUE THREAD

**Issue by vebhrocks** [calabash/calabash-android#611]
I am using calabash on Linux and when I hit the above command on terminal it shows some time in milliseconds i.e "272 KB/s (566732 bytes in 2.034s)" but later does not execute actual ".feature",  "steps_definitions" files. for this scenario I'm not even getting any error on terminal, I don't know why further execution get halt?
the terminal cursor keep waiting for further execution which never start.  
      As to care this issue I have tried below option.
      1. I close ".feature and calabash_steps.rb" files after every change.
      2. I check if my device is properly connect to my laptop with correct settings.
  I Google for this issue but didn't track the exact support. Can anyone help me out here.

Thanks in advance for the support.

**Comment by TobiasRoikjer** [comment]
@vebhrocks Please don't duplicate issues

**Comment by vebhrocks** [comment]
@jmoody : Can we have any solution on this? I'm facing this issue every time.
