### ISSUE TITLE
query() command doesn't work while running, but does from console

### ISSUE THREAD

**Issue by azelick** [calabash/calabash-android#613]
I am trying to adjust the value of a 'widget.numberPicker'. When I run the calabash-android console and send the command: "query("numberPicker", :setValue=>2)" the numberPicker in app adjusts appropriately. However when I am running the test "calabash-android run ....." the spinner query doesn't respond. 

I'm running gem version 0.5.14

**Comment by TobiasRoikjer** [comment]
This is most likely a timing issue, wait for the view to exist before querying.
