### ISSUE TITLE
Upgrading to newer cucumber gem?

### ISSUE THREAD

**Issue by JESii** [calabash/calabash-android#614]
Calabash gems (calabash-cucumber, calabash-iod, calabash-android) are all tied to cucumber 1.3.7 which is getting quite old (September 2014) -- the latest cucumber gem version is 2.0.2.

What are the plans for upgrading to current versions?

**Comment by jmoody** [comment]
The dependency is '~> 1.3.17' which means "any cucumber version >= 1.3.17 and < 1.4".

https://robots.thoughtbot.com/rubys-pessimistic-operator

We plan on updating to Cucumber 2.0 for Calabash iOS and Android 0.x.  I am not sure when we get to this.

Calabash 2.0 does not have cucumber as dependency.

**Comment by TobiasRoikjer** [comment]
@JESii The newst release of Calabash can run with any version of Cucumber

**Comment by JESii** [comment]
Thanks much; just what we were looking for.
