### ISSUE TITLE
Scroll functionality doesn't work in Android2.3 emulator

### ISSUE THREAD

**Issue by atcrao** [calabash/calabash-android#62]
Jonas is aware of this issue. 

The below scenario works on 2.3 device but not on 2.3 emulator.

Scenario: Accept the terms of agreement
    Then I should see "United States"
    Then I touch the "United States" text 

The step "Then I should see "United States"" should scroll the list view and click on the text "United States". But the scroll doesn't work.
As well I changed the country name to "Australia" which is visible on the screen. Even then the above scenario failed.

Note:- The same works on Android 2.2 and also on 2.3 device

**Comment by TobiasRoikjer** [comment]
Closing old issue. Unable to reproduce.
