### ISSUE TITLE
Is there a way to assert the app icon on the device home screen?

### ISSUE THREAD

**Issue by americapires1** [calabash/calabash-android#621]
Hi, 
Im using calabash android and I would like to know if there is a way i could check wether the app icon is present on the device home screen and whether I can tap on it to open it. I have been googling this and could not find anything. 

Thanks 
America

**Comment by TobiasRoikjer** [comment]
@americapires1 Calabash detects the launchable activity. This is the activity that will be opened when clicking the app icon. If Calabash can detect a launchable activity, your application should have an icon displayed.

You should verify that the AndroidManifest itself is correct using a different tool than Calabash :)
