### ISSUE TITLE
Device crashes and reboots when attempting to run Calabash on Android 6.0 Marshmallow

### ISSUE THREAD

**Issue by danbuckland** [calabash/calabash-android#625]
When attempting to run Calabash Android on a physical device and Android emulator running Android 6.0 (Marshmallow), the first step will fail with the following error:

`Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError)`

The device/emulator will then crash and reboot.

Adding this permission to my Android app does not seem to work as this permission is reserved for system apps. Possibly this is a permission the test server needs anyway.

**Comment by TobiasRoikjer** [comment]
@danbuckland I have noticed this on a Nexus 5 as well. It is a bug in Android M, and is simply surfaced  by Calabash. As seen in the stacktrace it is a NPE in ActivityManagerService, which is a core part of Android. It seems to have been acknowledged by the Android team: https://code.google.com/p/android-developer-preview/issues/detail?id=3081

Your exception has little to do with the actual issue, Android is simply telling you that your are trying to touch a view that is not owned by your application under test.

```shell
E/AndroidRuntime( 1614): *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
E/AndroidRuntime( 1614): java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IUiAutomationConnection.shutdown()' on a null object reference
E/AndroidRuntime( 1614): 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2026)
E/AndroidRuntime( 1614): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1614): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 1614): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/AndroidRuntime( 1614): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by TobiasRoikjer** [comment]
@danbuckland For now, I recommend using a Nexus 6 running M to test your application, as I have not seen the error on that device.

**Comment by danbuckland** [comment]
@TobiasRoikjer thanks for the reply and thorough explanation - hoping this is something that'll be fixed in the official release over the next few days. For the record and for anyone stumbling across this later, I'm on a Nexus 6 (physical device) running 6.0 (M Developer Preview 3) which is the latest.

**Comment by CalebMorris** [comment]
I have ran into this problem with it crashing the entire device and rebooting on the 5 and 6 running M (physical) and 5, 6, and 9 in the emulator.
