### ISSUE TITLE
What should we do when developer commit/push the new source code

### ISSUE THREAD

**Issue by hoangvm** [calabash/calabash-android#628]
Hi all !  
I'm a newbie of Calabash-Android. I would like to ask something as below  
1. Calabash-android has already installed successful and working fine with my project. 
2. IF my developer has implemented some function/features then push the new source code into GIT/SVN . Of course I have to pull it then run Automation test with new code.  
For make sure Calabash can be tested with new source code . WHAT should I do after pull new source code ? ( Install calabash-android again or setup somethings ??? )  

Please help me in this point. I'm very confusing...   
Thank you so much !

**Comment by TobiasRoikjer** [comment]
@hoangvm This is not an issue with Calabash-Android. I'll close this issue. My suggestion is to open a new topic on our google groups. https://groups.google.com/forum/#!forum/calabash-android

There should be plenty of previous topics and blogposts on this :)

**Comment by hoangvm** [comment]
I got it. Thank sir :)
