### ISSUE TITLE
Calabash-android can't find a lauchable activity if it is defined far down in AndroidManifest.xml

### ISSUE THREAD

**Issue by fabiomarinho** [calabash/calabash-android#633]
Found out that running the line 'launchable_activity_line = aapt_dump(app, "launchable-activity").first'
The activity was not listed. Then calabash raises "'launchable-activity' not found in aapt output".

When it then tries to parse using '`"#{Env.tools_dir}/aapt" dump xmltree "#{app}" AndroidManifest.xml`', it fails to find the activity in the following structure (I used the same command that calabash runs):
"""
E: activity (line=178)
        A: android:theme(0x01010000)=@0x7f09007b
        A: android:name(0x01010003)="com.kraftter.android.view.activities.SplashActivity_" (Raw: "com.kraftter.android.view.activities.SplashActivity_")
        A: android:screenOrientation(0x0101001e)=(type 0x10)0x1
        E: intent-filter (line=182)
          E: action (line=183)
            A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
          E: category (line=185)
            A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
"""

This is what calabash gives-me:

2015-10-23 15:02:38 - JDK found on PATH.
2015-10-23 15:02:38 - JDK found at: /home/vagrant/jdk
2015-10-23 15:02:38 - Android SDK found at: /home/vagrant/sdk
2015-10-23 15:02:38 - Trying to find launchable activity
2015-10-23 15:02:38 - Found tools directory at '/home/vagrant/sdk/build-tools/23.0.1'
ERROR getting 'android:icon' attribute: attribute is not a string value
2015-10-23 15:02:38 - Could not find launchable activity, trying to parse raw AndroidManifest. 'launchable-activity' not found in aapt output
2015-10-23 15:02:38 - Found tools directory at '/home/vagrant/sdk/build-tools/23.0.1'
2015-10-23 15:02:38 - Read intent filter
/var/lib/gems/1.9.1/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:75:in `rescue in main_activity': Could not find launchable activity (RuntimeError)
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:25:in `main_activity'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.12/bin/calabash-android-run.rb:20:in `calabash_run'
	from /var/lib/gems/1.9.1/gems/calabash-android-0.5.12/bin/calabash-android:85:in `<top (required)>'
	from /usr/local/bin/calabash-android:23:in `load'
	from /usr/local/bin/calabash-android:23:in `<main>'

I tried to move the activity definition to the beggining of my AndroidManifest.xml and it worked (It was working before, because the lauchable_activity was another one)!

It turned out that the command 'aapt_dump(app, "launchable-activity").first' was then showing the Activity:
"""
application-icon-640:'res/mipmap-xxhdpi-v4/ic_launcher.png'
application: label='Kraftter' icon='res/mipmap-mdpi-v4/ic_launcher.png'
application-debuggable
launchable-activity: name='com.kraftter.android.view.activities.SplashActivity_'  label='' icon=''
"""

**Comment by TobiasRoikjer** [comment]
You can specify the main activity yourself by setting the ENV variable MAIN_ACTIVITY.
or,
The Calabash test-server will automatically detect the main activity, so you can work around this by setting the ENV variable MAIN_ACTIVITY to some defined value, and starting the test-server using `start_test_server_in_background(main_activity: nil)` or similar.

**Comment by TobiasRoikjer** [comment]
But yes, this is a bug in Calabash caused by a bug in aapt.
