### ISSUE TITLE
Xam UITest CrossWalk support

### ISSUE THREAD

**Issue by paulpatarinski** [calabash/calabash-android#634]
I know this is probably not the correct place for this question, but given the close relationship between Xam UITest & Calabash and Issue #507. I wanted to check if there is support for CrossWalk with Xam UITest or at least plans for it. Right now app.Query(c => c.WebView()) returns an empty array. 

Cheers

**Comment by TobiasRoikjer** [comment]
This is not the right repository to report Xamarin.UITest issues.

Xamarin.UITest does support CrossWalk webviews as Calabash does, you are most likely not targeting the right view by using `c.WebView()`. Consider using a different matcher, the view is not of type android.webkit.WebView.
