### ISSUE TITLE
Get summary

### ISSUE THREAD

**Issue by gitwillian** [calabash/calabash-android#637]
Hello,
How can i get only theses '1 scenario (1 failed)' values by pretty or html format? Is it possible?

version 5.12
Tks

**Comment by TobiasRoikjer** [comment]
@gitwillian The Calabash github issues should be used to report issues with Calabash, and not for getting help. This question is better suited for our Google Groups. You are most likely running Calabash using Cucumber, you can find many examples of using a cucumber formatter. https://groups.google.com/forum/#!topic/cukes/Xl6ZOxJVXs4

Using the calabash-android run command, everything after the APK should be parsed as Cucumber parameters.
