### ISSUE TITLE
Can't Access "Checked" Property of Radio Button

### ISSUE THREAD

**Issue by vdayes** [calabash/calabash-android#638]
Hello,

When I go on Android Device Manager I can see the "Checked" property of Radio Buttons under Node Detail  (see attached)
![radio button 3mo](https://cloud.githubusercontent.com/assets/3486552/11051354/4bc2f3be-8703-11e5-9b85-1cd6e72353d8.png)

But in IRB query, the Checked property is not accessible.  (see attached)
![irb radio button 3mo](https://cloud.githubusercontent.com/assets/3486552/11051355/51e10f38-8703-11e5-8aaa-946ca3b57c10.png)

Is there some way I can assert whether or not Radio Buttons are checked?
Thank you

**Comment by marshallino16** [comment]
All properties aren't displayed, take a look at ViewMapper.java and edit it if you wanna have more properties. 

For now, you can query your radio button like this : ```query("CheckBox id:'rb3Month'",:checked)```

**Comment by vdayes** [comment]
Thank you - it worked!
