### ISSUE TITLE
Not an issue, only a question, don't know where else to ask.

### ISSUE THREAD

**Issue by vinvictor7** [calabash/calabash-android#642]
Hi all.

I want to ask whether these tests are for virtually all the android applications, or only for those apps that have compatible plugins and code designed according to calabash' standards/guidelines.

**Comment by marshallino16** [comment]
For questions, please use google group community :) 

But for your question, no, it's compatible with all apps.

**Comment by jmoody** [comment]
@marshallino16 Thanks.

**Comment by jmoody** [comment]
https://groups.google.com/forum/#!forum/calabash-android

**Comment by vinvictor7** [comment]
thanks @marshallino16 and @jmoody 
Please don't delete the question, it may help someone else. If you want to edit the question to a proper format, and delete this comment, I'd appreciate it.

**Comment by jmoody** [comment]
The GitHub issues are (should be?) reserved for bugs and feature requests.

We can't keep issues up just for documentation purposes.

The question is not deleted.  It is closed.

**Comment by jmoody** [comment]
I would also like to add that this is a valid question.
