### ISSUE TITLE
Could not execute command to start test server

### ISSUE THREAD

**Issue by magentann** [calabash/calabash-android#644]
What I do:
1. adb install -r my.apk (it's resigned)
2. calabash-android console my.apk
3. start_test_server_in_background in irb(main)

        irb(main):002:0> start_test_server_in_background
        RuntimeError: Could not execute command to start test server
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:635:in `start_test_server_in_background'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:133:in `start_test_server_in_background'
        from (irb):2
        from C:/Ruby193/bin/irb:12:in `<main>'
Use in work:
> ruby 1.9.3p551
> java version "1.7.0_79"
> Apache Ant™ version 1.9.6

Could you help me, please? How to start test server right? Thanks

**Comment by jmoody** [comment]
Something in the default .irbrc is not working.

My best guess is that at some point calabash-android or one of the gems it depends on is no longer compatible with ruby 1.9.3.

Can you update to ruby 2.1?

https://developer.xamarin.com/guides/testcloud/calabash/configuring/windows/installing-ruby/

**Comment by magentann** [comment]
Unfortunately, it doesn't help me...
Now I use ruby 2.1.7p400 and have these errors:

        RuntimeError: Could not execute command to start test server
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:651:in `start_test_server_in_background'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:135:in `start_test_server_in_background'
        from (irb):3
        from C:/Ruby21-x64/bin/irb:11:in `<main>'

**Comment by magentann** [comment]
Maybe somebody knows what to do..

**Comment by jmoody** [comment]
@TobiasRoikjer mentioned to me in another channel that you need to install the apk _and_ the test server.

**Comment by TobiasRoikjer** [comment]
There is no reason to use adb commands yourself in Calabash-Android. Just use the command `reinstall_apps`, which will install both the application and the test-server
