### ISSUE TITLE
Unable to perform orientation change in Calabash-Android

### ISSUE THREAD

**Issue by Aravin** [calabash/calabash-android#645]
While trying to change device orientation 

    perform_action('set_activity_orientation', 'landscape')

I am getting following error message.

     Action '["set_activity_orientation", "landscape"]' unsuccessful: Can not deserialize instance of java.lang.String out of START_ARRAY token at [Source: java.io.StringReader@3a70383e; line: 1, column: 2] (through reference chain: sh.calaba.instrumentationbackend.Command["command"]) (RuntimeError)

*Device Info*

- Windows 7 x64
- ruby 2.1.7p400
- calabash-android v 0.5.8

*Note*

Same command worked fine few days ago.

**Comment by TobiasRoikjer** [comment]
Could you please run adb logcat and post the output here?

**Comment by Aravin** [comment]
It is working now!

Previously I used

    LANDSCAPE="'set_activity_orientation', 'landscape'"
    perform_action(LANDSCAPE)

Now I using,

    perform_action('set_activity_orientation', 'landscape')

Working perfectly.
