### ISSUE TITLE
Calabash-cucumber/launcher (Loaderror) -- Cannot load such file

### ISSUE THREAD

**Issue by tjai** [calabash/calabash-android#648]
![image](https://cloud.githubusercontent.com/assets/16234386/11706054/5992b0a8-9f1b-11e5-9e46-6b5adc42db1c.png)

I'm seeing load issues in calabash in windows machine. The ruby version is same in gem env and through ruby -v. Please suggest.

**Comment by jmoody** [comment]
I don't know if this is actually the problem because I can't see what version of calabash-cucumber (AKA calabash-ios) you are using - Calabash-cucumber no longer supports ruby 1.9.3.  You should upgrade to ruby >= 2.0.

**Comment by TobiasRoikjer** [comment]
Calabash-Cucumber is the name for the Calabash-iOS gem. I does not work on Windows. It appears you are trying to run ios generated launch-hooks from Calabash-Android. The generated hook files in  iOS and Android are not compatible. Use `calabash-android generate` to build a working cucumber skeleton.
