### ISSUE TITLE
Embed is a Cucumber method and is not available in this console

### ISSUE THREAD

**Issue by GURVARINDER** [calabash/calabash-android#650]
Hey guys, 
I have just started using calabash-android 0.5.15 for our mobile projects. I've followed all the installation steps and everything seemed to be fine until i tried the following:
irb(main):004:0> query("id marked: 'sign_up_text'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map id marked: 'sign_up_text', query failed because: Unknown query: <invalid> with text: marked:

	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:855:in `screenshot_and_raise'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:1246:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:198:in `query'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'
Note: When i do query("*") i can see the element with id: 'sign_up_text'. Please let me know if you need any further information about this issue.

**Comment by TobiasRoikjer** [comment]
`query("id marked: 'sign_up_text'")`is not a valid query. There should be no space between marked: and the mark. Further, the query syntax is <class> <predicates> <direction> .... I don't think the name of the class you are looking for is "id". If you want to check against the id of any view use "* id:'...'". Marked is a special keyword looking for either id, contentDescription or text.

**Comment by GURVARINDER** [comment]
Thanks. The format of the query was the problem.
