### ISSUE TITLE
Add usage tracking

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-android#655]
As announced in the Calabash iOS 0.17.0 release notes:

### Usage Tracking

Staring in Calabash iOS 0.17.0, we are collecting usage statistics when an app is launched.  Usage tracking will be added to the next release of Calabash Android and Calabash 2.0.

**Why?**

We want to do a head count; how many people use Calabash?

There are a bunch of features in the pipeline and we don't know which are the most important to focus on.

**What is tracked?**

We are not collecting your name, email address, the name of your app, your IP address,
or any other identifying information.  This is an open source project so you can see for yourself what we information we are tracking.

**Can I turn tracking off?**

You can control what gets tracked using the following commands in the console:

```ruby
$ bundle exec calabash-android console
> disable_usage_tracking
Calabash will not collect usage information.
"none"

> enable_usage_tracking
Calabash will collect statistics using the 'system_info' rule.
"system_info"

> enable_usage_tracking("events")
Calabash will collect statistics using the 'events' rule.
"events"
```

**Comment by TobiasRoikjer** [comment]
I have closed this issue. If anyone has questions regarding this, feel free to comment on this issue.
