### ISSUE TITLE
perform_action(drag) function not dragging an element.

### ISSUE THREAD

**Issue by suresh02** [calabash/calabash-android#662]
perform_action(drag) function not dragging an element.... I want to swipe up an element please give me solution for this I am stuck in the middle

**Comment by TobiasRoikjer** [comment]
See https://developer.xamarin.com/guides/testcloud/calabash/working-with/gestures/

**Comment by suresh02** [comment]
Thanks for reply Tobias
def flick_up(options={})
  flick("* id:'content'", :up, options)
end

Can you tell me in this code what options refer to.. what all the values we can give in that
Can you explain with an example please
