### ISSUE TITLE
Swipe left is not working

### ISSUE THREAD

**Issue by gongmingqm10** [calabash/calabash-android#665]
Hi, I was stuck in a issue for a whole day when I write functional tests for Android tests. I found a strange fact: `Then I swipe left` is not working, while `Then I swipe right` is working. I assume it's caused by the view focus or scrollable scope. But when I tried as following:

```
    Then I wait for "Some Page" to appear
    Then I swipe left
    Then I swipe right
    Then I swipe left
    Then I swipe right
    Then I swipe left
```
And the fact is, the App could respond the `swipe right` operation, and nothing happened when `swipe left` called. I'm using the version `0.5.8`, and also tried the version `0.6.0.pre4`. Both are not working for my case.

Thanks.

**Comment by Sneha241** [comment]
hey maybe this will help chek this out https://developer.xamarin.com/guides/testcloud/calabash/working-with/gestures/ 

Also, this worked for me pan("* id:'element'", :right) 
try it out
