### ISSUE TITLE
Entering a data into edit text with same id in a page does not work

### ISSUE THREAD

**Issue by sanved** [calabash/calabash-android#668]
I have an application, in which data is loaded dynamically. Dynamically generated page consists of text filed of same id. There are around 5 text fields with same id.

I have entered text in a field1, clicked on next button on keyboard and navigated to the next field i.e field2. here when I try to enter a text in the field2, application is navigating to previous field i.e field1 anf typing text.

**Comment by TobiasRoikjer** [comment]
`enter_text` enters text in the first view found by the given query, that is expected behaviour. Are you looking for `keyboard_enter_text`?

**Comment by sanved** [comment]
How to enter text in every edit text field which have same id in a page? For example a age consists of 7 edit text boxes with ID R.id.edittext. How to enter text in all those 7 edit boxes?

**Comment by TobiasRoikjer** [comment]
https://github.com/calabash/calabash-android/wiki/05-Query-Syntax
