### ISSUE TITLE
Cannot scroll a Relative layout  - android calabash 

### ISSUE THREAD

**Issue by Sneha241** [calabash/calabash-android#669]
I am trying to scroll the relative layout (i.e the grey layout having checkboxes) and reach until all my checkboxes are complete 

![screenshot_2015-12-29-11-22-11]
(https://cloud.githubusercontent.com/assets/11473681/12034096/8342c88c-ae2c-11e5-8878-38b779e2a621.png)

. 
I did a lot of trial and error but none dint worked 
I tried the following 
1. scroll("android.view.View'", :down) - here i get a blank screen 
2. scroll("android.widget.RelativeLayout id:'sidedishesDialog'", :down) - calabash couldnt find the id sidedishesDialog (not sure which id to use) 
3. scroll("android.widget.RelativeLayout", :down) - this kind of scrolled down but the rest of my page was blank
![screenshot_2015-12-29-11-33-32](https://cloud.githubusercontent.com/assets/11473681/12033714/a0a40040-ae26-11e5-807f-ffc0be2378df.png)
i must basically scroll down and see this at  the end 

![screenshot_2015-12-29-11-36-16](https://cloud.githubusercontent.com/assets/11473681/12034132/e70d49fa-ae2c-11e5-8692-5c42e1a2bc8b.png)

Any solution would be appreciated 
my calabash-android version is 0.5.12.pre1

**Comment by TobiasRoikjer** [comment]
Scroll invokes a method on the view, if the view does not implement scroll methods (which relativelayout does not) then you can't scroll it. It is a non-user gesture or synthetic interaction. If you are not trying to optimise for speed, I suggest using gestures a user would be able to perform like swipes see https://developer.xamarin.com/guides/testcloud/calabash/working-with/gestures/.

If you are sure you want to scroll, look for views that inherit from android.widget.ScrollView or android.widget.AbsListView (you can query for those classes in a console to find the relevant views).
