### ISSUE TITLE
'start_test_server_in_background' takes some time to start the test server, but app launches earlier

### ISSUE THREAD

**Issue by jitihsk** [calabash/calabash-android#670]
Hi,
In my application I need to check some `pre-conditions` immediately on launch of the app. The problem `pre-conditions` are available only for couple of seconds.

The problem i am facing is, when the `start_test_server_in_background` in executed in `app_life_cycle_hooks.rb`, it takes lot of time to start the test server whereas the app is launched immediately.

Is it possible to start the app after the test server is started?
Also I see in function `start_test_server_in_background`, retry interval for checking test server is set to 3
```
          Retriable.retriable :tries => 10, :interval => 3 do
            log "Checking if instrumentation backend is ready"

            log "Is app running? #{app_running?}"
            ready = http("/ready", {}, {:read_timeout => 1})
            if ready != "true"
              log "Instrumentation backend not yet ready"
              raise "Not ready"
            else
              log "Instrumentation backend is ready!"
            end
          end
```

Can that be reduced to `0.5` or `1`?

**Comment by TobiasRoikjer** [comment]
Yes, I think that is a very good idea. Great job noticing this!

**Comment by TobiasRoikjer** [comment]
As for the actual issue:
"In my application I need to check some pre-conditions immediately on launch of the app. The problem pre-conditions are available only for couple of seconds."

Testing against something that is timing sensitive is generally not a good idea. It will lead to fragile tests. Calabash makes no promises for being within a certain timing window, especially not during startup.

You should consider this:
 - Don't test for starting preconditions. Are they really that important? Your users can use your application anyway
 - When showing the loading screen, don't proceed until a backdoor is called.

**Comment by TobiasRoikjer** [comment]
Fixed in: https://github.com/calabash/calabash-android/pull/679
Released in: https://rubygems.org/gems/calabash-android/versions/0.6.1.pre1
