### ISSUE TITLE
CrossWalk version15: XWalkContentView isn't recognised as a valid web view

### ISSUE THREAD

**Issue by JennyGr** [calabash/calabash-android#672]
Hello,

I'm using calabash-android 0.5.15 and till now for Android versions < 4.4 our application was using CrossWalk version 13. To identify the web views I was using in my queries something like this:
**query("org.xwalk.core.internal.XWalkContent css:'*'")**.
The developer updated the CrossWalk to version 15 and now I use in my queries this:
**query("org.xwalk.core.internal.XWalkContentView css:'*'")**.

I get this error though:
Embed is a Cucumber method and is not available in this console.
RuntimeError: map XWalkContentView css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.xwalk.core.internal.XWalkContentView is not recognized a valid web view.

	from /Users/jenny/.calabash/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:855:in `screenshot_and_raise'
	from /Users/jenny/.calabash/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:1246:in `map'
	from /Users/jenny/.calabash/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:198:in `query'
	from (irb):26
	from /Users/jenny/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'

**Comment by JennyGr** [comment]
Is there any progress on this issue?

**Comment by TobiasRoikjer** [comment]
I would appreciate if someone in the community could create an APK using the latest version of crosswalk and upload it.

**Comment by jmoody** [comment]
@TobiasRoikjer Can you point us to some docs?

**Comment by jmoody** [comment]
We just need an .apk that uses the latest version of crosswalk.

**Comment by JennyGr** [comment]
I have a test .apk where I can reproduce this issue. Where can I send it? It's too big to attach it here.

**Comment by jmoody** [comment]
@JennyGr That is good news.

We can discuss options and share a link (privately) on Gitter.

https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by TobiasRoikjer** [comment]
You are also welcome to send the apk as an email to me at tobias@xamarin.com :)

**Comment by JennyGr** [comment]
Any progress with this? Was the test-app helpful?

**Comment by jmoody** [comment]
@JennyGr 

Thanks for the app.  Tobias is reviewing.

**Comment by TobiasRoikjer** [comment]
@JennyGr Could you please try this release [0.6.0.prelatestcrosswalk](https://rubygems.org/gems/calabash-android/versions/0.6.0.prelatestcrosswalk). You can just write that as the version in your gemfile.

It is a build or this PR https://github.com/calabash/calabash-android-server/pull/13

**Comment by JennyGr** [comment]
Hello,

Sorry for the really late response, but it was very busy lately. I tested the fix, but it doesn't solve the issue.
I installed the 0.6.0.prelatestcrosswalk version and reinstalled the test server (reinstall_test_server)
This what I get in my console:

irb(main):005:0> query("*")
[
    [ 0] {
                     "class" => "com.android.internal.policy.impl.PhoneWindow$DecorView",
                       "tag" => nil,
               "description" => "com.android.internal.policy.impl.PhoneWindow$DecorView{339422bf V.E..... R....... 0,0-1080,1920}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1920,
               "width" => 1080,
                   "y" => 0,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 960
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 1] {
                     "class" => "android.widget.LinearLayout",
                       "tag" => nil,
               "description" => "android.widget.LinearLayout{37632d8c V.E..... ........ 0,0-1080,1776}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1776,
               "width" => 1080,
                   "y" => 0,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 888
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 2] {
                     "class" => "android.widget.FrameLayout",
                       "tag" => nil,
               "description" => "android.widget.FrameLayout{1f87fcea V.E..... ........ 0,75-1080,1776}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1701,
               "width" => 1080,
                   "y" => 75,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 925
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 3] {
                     "class" => "android.support.v7.widget.ActionBarOverlayLayout",
                       "tag" => nil,
               "description" => "android.support.v7.widget.ActionBarOverlayLayout{22f22bdb V.E..... ........ 0,0-1080,1701 #7f0e0040 app:id/decor_content_parent}",
                        "id" => "decor_content_parent",
                   "visible" => true,
                      "rect" => {
              "height" => 1701,
               "width" => 1080,
                   "y" => 75,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 925
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 4] {
                     "class" => "android.support.v7.widget.ContentFrameLayout",
                       "tag" => nil,
               "description" => "android.support.v7.widget.ContentFrameLayout{30db9678 V.E..... ........ 0,168-1080,1701 #1020002 android:id/content}",
                        "id" => "content",
                   "visible" => true,
                      "rect" => {
              "height" => 1533,
               "width" => 1080,
                   "y" => 243,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 5] {
                     "class" => "android.widget.LinearLayout",
                       "tag" => nil,
               "description" => "android.widget.LinearLayout{e27d151 V.E..... ........ 0,0-1080,1533}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1533,
               "width" => 1080,
                   "y" => 243,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 6] {
                     "class" => "org.xwalk.core.XWalkView",
                       "tag" => nil,
               "description" => "org.xwalk.core.XWalkView{1e60fdb6 V.E..... ........ 48,48-1032,1485 #7f0e0051 app:id/webview}",
                        "id" => "webview",
                   "visible" => true,
                      "rect" => {
              "height" => 1437,
               "width" => 984,
                   "y" => 291,
                   "x" => 48,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 7] {
                     "class" => "org.xwalk.core.internal.XWalkViewBridge",
                       "tag" => nil,
               "description" => "org.xwalk.core.internal.XWalkViewBridge{2d5daab7 V.E..... ........ 0,0-984,1437 #7f0e0051 app:id/webview}",
                        "id" => "webview",
                   "visible" => true,
                      "rect" => {
              "height" => 1437,
               "width" => 984,
                   "y" => 291,
                   "x" => 48,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 8] {
                     "class" => "org.xwalk.core.internal.XWalkContent$1",
                       "tag" => nil,
               "description" => "org.xwalk.core.internal.XWalkContent$1{1b6fa224 V.E..... ........ 0,0-984,1437}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1437,
               "width" => 984,
                   "y" => 291,
                   "x" => 48,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [ 9] {
                     "class" => "android.view.SurfaceView",
                       "tag" => nil,
               "description" => "android.view.SurfaceView{3dc7318d V.E..... ........ 0,0-984,1437}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1437,
               "width" => 984,
                   "y" => 291,
                   "x" => 48,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [10] {
                     "class" => "org.xwalk.core.internal.XWalkContentView",
                       "tag" => nil,
               "description" => "org.xwalk.core.internal.XWalkContentView{1ef73f42 VFE...C. .F...... 0,0-984,1437}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 1437,
               "width" => 984,
                   "y" => 291,
                   "x" => 48,
            "center_x" => 540,
            "center_y" => 1009
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [11] {
                     "class" => "android.support.v7.widget.ActionBarContainer",
                       "tag" => nil,
               "description" => "android.support.v7.widget.ActionBarContainer{33983b53 V.ED.... ........ 0,0-1080,168 #7f0e0041 app:id/action_bar_container}",
                        "id" => "action_bar_container",
                   "visible" => true,
                      "rect" => {
              "height" => 168,
               "width" => 1080,
                   "y" => 75,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 159
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [12] {
                     "class" => "android.support.v7.widget.Toolbar",
                       "tag" => nil,
               "description" => "android.support.v7.widget.Toolbar{f16bc90 V.E..... ........ 0,0-1080,168 #7f0e0042 app:id/action_bar}",
                        "id" => "action_bar",
                   "visible" => true,
                      "rect" => {
              "height" => 168,
               "width" => 1080,
                   "y" => 75,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 159
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [13] {
                     "class" => "android.widget.TextView",
                       "tag" => nil,
               "description" => "android.widget.TextView{1825989 V.ED.... ........ 48,43-404,124}",
                        "id" => nil,
                      "text" => "WebviewTest",
                   "visible" => true,
                      "rect" => {
              "height" => 81,
               "width" => 356,
                   "y" => 118,
                   "x" => 48,
            "center_x" => 226,
            "center_y" => 158
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [14] {
                     "class" => "android.view.View",
                       "tag" => nil,
               "description" => "android.view.View{29d311bc V.ED.... ........ 0,0-1080,75 #102002f android:id/statusBarBackground}",
                        "id" => "statusBarBackground",
                   "visible" => true,
                      "rect" => {
              "height" => 75,
               "width" => 1080,
                   "y" => 0,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 37
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
    [15] {
                     "class" => "android.view.View",
                       "tag" => nil,
               "description" => "android.view.View{11ae0545 V.ED.... ........ 0,1776-1080,1920 #1020030 android:id/navigationBarBackground}",
                        "id" => "navigationBarBackground",
                   "visible" => true,
                      "rect" => {
              "height" => 144,
               "width" => 1080,
                   "y" => 1776,
                   "x" => 0,
            "center_x" => 540,
            "center_y" => 1848
        },
                   "enabled" => true,
        "contentDescription" => nil
    }
]
irb(main):006:0> query("org.xwalk.core.internal.XWalkContentView css:'*'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map org.xwalk.core.internal.XWalkContentView css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.xwalk.core.internal.XWalkContentView is not recognized a valid web view.

	from /Users/jenny/.calabash/gems/calabash-android-0.6.0.prelatestcrosswalk/lib/calabash-android/operations.rb:867:in `screenshot_and_raise'
	from /Users/jenny/.calabash/gems/calabash-android-0.6.0.prelatestcrosswalk/lib/calabash-android/operations.rb:1260:in `map'
	from /Users/jenny/.calabash/gems/calabash-android-0.6.0.prelatestcrosswalk/lib/calabash-android/operations.rb:204:in `query'
	from (irb):6
	from /Users/jenny/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):007:0>

**Comment by TobiasRoikjer** [comment]
@JennyGr You have to use the class `org.xwalk.core.internal.XWalkContent$1` or similar :)

**Comment by JennyGr** [comment]
True :smile: 
I'm gonna update to 0.6.0.prelatestcrosswalk officially 

Thanks a lot!
