### ISSUE TITLE
`Cucumber::Ast` no longer exists. (cucumber 2.3.0)

### ISSUE THREAD

**Issue by fkeegan** [calabash/calabash-android#673]
After upgrading to cucumber 2.3.0 on my Gemfile (using calabash-android 0.6.0) I'm getting the following error:

`Cucumber::Ast` no longer exists. These classes have moved into the `Cucumber::Core::Ast` namespace, but may not have the same API. (RuntimeError)
 ./features/support/app_installation_hooks.rb:8:in `Before'
 App did not start (RuntimeError)
 ./features/support/app_life_cycle_hooks.rb:5:in `Before'

Which is similar to https://github.com/calabash/calabash-android/issues/479 but the difference is cucumber version 2.3.0 is not a beta version.

Thanks.

**Comment by TobiasRoikjer** [comment]
You should update your hooks or use the "new" skeleton in calabash. (`calabash-android gen`).

**Comment by dharamveerSinghRajpoot** [comment]
Hi Team,  

i'm getting above error with Cucumber + 2.0, i have tried with multiple cucumber gem + 2.0 but no luck, It is working fine till cucumber 1.3.20.

Please let me know if any one have any suggestion.
Thanks in Advance.
