### ISSUE TITLE
More than one launchable activity in AndroidManifest

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-android#674]
Hi I have issue with calabash-android 
if I try run 
`calabash console app.apk`
i get error like 
```
/user/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/calabash-android-0.6.0/lib/calabash-android/helpers.rb:45:in `block in main_activity': More than one launchable activity in AndroidManifest (RuntimeError)
``` 

i take a look on output for `lines` in `helpers.rb`
and find something like 
```
...
A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
E: activity-alias (line=527)
...
A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
E: activity (line=533)
```

so basically it is same launch activity from my point of view but calabash failing to start with such data 

possible workaround for helpers.rb:
```
    duplicate_line = ''

    # puts lines
    lines.each_with_index do |line, index|


      match = line.match(regex)

      unless match.nil?
        if duplicate_line == '' || duplicate_line.nil?
          duplicate_line = line
        else
          if duplicate_line != line
             raise 'More than one launchable activity in AndroidManifest' unless indicator_line.nil?
          end
        end
        indicator_line = index
      end
    end
```
can create pull request if needed

**Comment by kaorijp** [comment]
Do you have any update for this issue?

**Comment by ark-konopacki** [comment]
@kaorijp no updates for that issue it is rare situation and i already add workaround

**Comment by kaorijp** [comment]
@ark-konopacki 
Other error is appeared 

RuntimeError: App did not start
from ..../calabash-android/operations.rb:662:in `block in start_test_server_in_background`

**Comment by TobiasRoikjer** [comment]
Calabash-Android 0.8.0 tries to obtain the main activity on the server not through the client. This should no longer be an issue.
