### ISSUE TITLE
Can't install apk using calabash

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#675]
Hai 

I am using the calabash version 0.5.14 and facing a problem on apk installation using calabah. I have mentioned the error below

[undefined method `last' for #<Enumerator:0x00000001b20380> (NoMethodError)
 /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:314:in `install_app'
 /var/lib/gems/1.9.1/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:104:in `install_app']

Note:
- Once I get this error then I can't use both 'adb install' and 'playstore install'
- Error for adb install - "Failure [Install_failed_insufficient_storage]"
- Error for Playstore install - "xxx can't be installed. Try again. and if the problem continues, get help troubleshooting. (Error code: -506)"
- Removing other apks to free some space also didn't work.
- However when I restart the device - I can install apk using calabash. Then after a certain amount of installation (for eg: 400-500) using calabash I end up with the same error.

It seems as a device storage issue. I am thinking that the uninstall using calabash doesn't actually removes everything of that apk - something is stored somewhere?.

Is it anything else I have to look for to fix this issue. Thanks

**Comment by TobiasRoikjer** [comment]
You stacktrace looks very strange, hvad you modified the Calabash source code?

About the real issue: Unfortunately there is nothing we can do to avoid this. It is a bug in Android. Restarting does indeed seem to fix the issue. Perhaps stopping the app before uninstalling helps?
