### ISSUE TITLE
usage tracking: replace user_id with distinct_id 

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-android#676]
### Motivation

MixPanel prefers distinct_id for indexing.

**Comment by TobiasRoikjer** [comment]
@jmoody Should we not just *add*  distinct_id as well?

**Comment by jmoody** [comment]
I don't have a strong feeling either way.  

The relay server is now adding the distinct_id using the user_id field.

**Comment by TobiasRoikjer** [comment]
@jmoody Can you close?

**Comment by jmoody** [comment]
The change has not been made.

Reopening.

**Comment by jmoody** [comment]
Fixed.
