### ISSUE TITLE
Using setText from a query parses number strings to numbers.

### ISSUE THREAD

**Issue by rKrums** [calabash/calabash-android#677]
Hi. Just updated to calabash-android v0.6.0.

Noticed, that when using setText for text fields, if the string contains only numbers, it's parsed to a number, and can not be set with setText.

So what I did
calabash-adnroid v0.6.0

```
query("* id:'pin'",setText:"0000")
query("* id:'pin'",:setText =>"0000")

Got this:
[
    [0] {
                 "error" => nil,
         "receiverClass" => "com.company.foo",
        "receiverString" => "com.company.foo}",
            "methodName" => "InvocationOp[setText, arguments = [0000]]"
    }
]
```

Tried to do queries like

```
num = 0000
temp = num.to_s
query("* id:'pin'",:setText =>num)
```

and so on
Didn't found any way to get the string to be passed to setText
Adding an alphabetic character to the string, passes the argument to setText. For example "000a"

Downgrading to 0.5.8 did the trick. Every query with setText worked.

**Comment by jmoody** [comment]
@rKrums Thanks for the detailed report.  Please use GitHub markdown formatting for code blocks in the future.  "```"

**Comment by TobiasRoikjer** [comment]
Fixed in: https://github.com/calabash/calabash-android-server/pull/14
Released in: https://rubygems.org/gems/calabash-android/versions/0.6.1.pre1
