### ISSUE TITLE
Web view queries are crashing

### ISSUE THREAD

**Issue by rKrums** [calabash/calabash-android#678]
Hi. Just updated to calabash-android v0.6.0.

```
query("webView css:'**'")
Embed is a Cucumber method and is not available in this console.

RuntimeError: map webView css:'*', query failed because: java.util.concurrent.ExecutionException: 
java.lang.RuntimeException: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not
deserialize instance of java.util.HashMap out of START_ARRAY token
```

Version 0.5.14 works fine.

**Comment by TobiasRoikjer** [comment]
`query("webView css:'**'")` is not a valid css selector. Do you mean query("webView css:'*'") ?

**Comment by rKrums** [comment]
Yes I did mean with one star. GitHub tried to format something in there, when I added one wildcard

**Comment by TobiasRoikjer** [comment]
Alright. Could you please post the stacktrace in `adb logcat`. If possible, can you email me the application you are testing so I can reproduce?

**Comment by rKrums** [comment]
I will do that, if I encounter something similar again, because it's now working for me with 0.5.14, and I can not afford to spend time trying to reproduce this at the moment.

**Comment by TobiasRoikjer** [comment]
@rKrums I would appreciate the apk if you can email it, tobias@xamarin.com
