### ISSUE TITLE
Warning in abase.rb:86 'method_missing' (Given/When/Then) is deprecated

### ISSUE THREAD

**Issue by rKrums** [calabash/calabash-android#682]
I am using calabash-android version 0.5.14

I am receiving this warning from abase.rb

I do not know if it's an issue, but I would like to know where it comes from, and why.

The exact error:
`WARNING: Using 'Given/When/Then' in step definitions is deprecated, use 'step' to call other steps instead:/usr/local/lib/ruby/gems/2.3.0/gems/calabash-android-0.5.14/lib/calabash-android/abase.rb:86:in 'method_missing'`

**Comment by jmoody** [comment]
Are you calling Cucumber Steps inside other Steps?

**Comment by rKrums** [comment]
I am, I'm calling them using
macro("I do something")

I found, that the warning is not displayed, when calling 
step("I do something")

But was concerned, why it is displaying the abase.rb instead of my file.

**Comment by jmoody** [comment]
abase.rb uses method_missing to route calls to pages.

**Comment by rKrums** [comment]
So I must use step() instead of macro() ?

**Comment by jmoody** [comment]
Yes.

But I would recommend doing neither. Calling Steps from Steps is not a good practice in my opinion.

**Comment by rKrums** [comment]
That's a solution I found that fits for me as we are following gherkin for .feature files, and we try to use as less steps as possible for each scenario to keep feature files business readable, and then the steps contain a lot of actions, and not always they share the same background. 

You recommend defining the actions over and over again in each step?

Thank you for your time!

**Comment by jmoody** [comment]
I recommend getting out of the step definition as fast a possible and into a page or into a World module.

```
module YourApp
  module Dashboard

    def complex_action_you_do_many_times

    end

    def another_action_with_lots_of_steps

     end
  end
end

World(YourApp::Dashboard)

Then(^/I do something complicated/$) do
  complex_action_you_do_many_times
  another_action_with_lots_steps
end
```

This video is good.  It is behind a password site, but registration is free.

* http://goo.gl/RFo6ZN

**Comment by rKrums** [comment]
Thank you for help and your time!
