### ISSUE TITLE
Investigate delay before instruments backend is 'ready'

### ISSUE THREAD

**Issue by Devneval** [calabash/calabash-android#685]
There is sometimes a short delay before the instruments backend is 'ready'. It would be good to understand the reason why it happens in the specific case (please request) and possibly general reason this might happen.

In the specific case of the example app. There is an external influence which navigates from one page to another which results in the initial page being transient. It is worth mentioning it is not recommended to implement a test which relies on a transient elements but there are some cases this might be required. On occasion the external influence navigates away from the initial page before instruments have 'started'.

Example app and extended information available. Please request.

**Comment by TobiasRoikjer** [comment]
We are as fast as possible with the recent changes
