### ISSUE TITLE
Not able to query any webview elements on Android

### ISSUE THREAD

**Issue by vmani00c** [calabash/calabash-android#687]
Hi.. On querying webview, I get blank results []. I tried all the below query options and getting blank response. Please help

query("webView css:'#header'")
query("webView css:'.js-current-repository'")
query("webView css:'a'")
query("cordovaWebView css:'#header'")
query("cordovaWebView css:'.js-current-repository'")
query("cordovaWebView css:'a'")

query("SystemWebView css:'#header'")
query("SystemWebView css:'.js-current-repository'")
query("SystemWebView css:'a'")
query('UIWebView')

query("WLWebView css:'*'")

**Comment by vmani00c** [comment]
To add, it is an browser inside the app and I am not able to query any elements in that browser.

**Comment by TobiasRoikjer** [comment]
Use `query("*")` to find the name of your webview.

**Comment by otamas94** [comment]
I have the same problem, and 'query("*")' is not returning a blank result also. Any other solution to find out how to get the page elements from an inner browser (Google Chrome) with calabash?

**Comment by lessercodes** [comment]
I have the same problem too.
