### ISSUE TITLE
Touch the OverflowMenuButton

### ISSUE THREAD

**Issue by adrielcafe** [calabash/calabash-android#697]
Hi guys,
I'm trying to press/touch the overflow button (image below).
I've tried the step "Then I press the menu key" but didn't work.
The OverflowMenuButton doesn't have an id.
![Overflow Menu](http://i.stack.imgur.com/vTM3K.png)

Thanks in advance!

**Comment by adrielcafe** [comment]
Also tried the step 'Then I select "Edit" from the menu', gave this error:
`Timeout waiting for elements: DropDownListView * marked:'Edit' (Calabash::Android::WaitHelpers::WaitError)`

**Comment by TobiasRoikjer** [comment]
Calabash only supports testing applications that are running the calabash test-server. You can only test applications that you are installing yourself. You cannot automate google play store, as it is pre-installed.

**Comment by adrielcafe** [comment]
Sorry for the confusion, this image was for illustration only. 
The real app I'm testing is this:
![Real App](https://dl.dropboxusercontent.com/u/98073648/Screenshot_20160308-105128.jpg)

I managed to touch the button this way. It's not the best solution but it works.
```ruby
Then /^I open the overflow menu$/ do
	perform_action('click_on_screen', 95, 5)
end
```

**Comment by TobiasRoikjer** [comment]
@adrielcafe I suggest just `query("*")` and try to locate your element in the console. The query system is powerful, and you can locate it by doing something like `query("* {x < 300}")`. (do not, however, use this as your final query). The item probably has a unique id or contentDescription.

https://github.com/calabash/calabash-android/wiki/05-Query-Syntax

**Comment by adrielcafe** [comment]
Thanks @TobiasRoikjer, i'll try that!

**Comment by adrielcafe** [comment]
Found it!
It didn't has id or contentDescription.
```ruby
irb(main):009:0> query("android.support.v7.widget.ActionMenuView")
[
    [0] {
                     "class" => "android.support.v7.widget.ActionMenuView",
                       "tag" => nil,
               "description" => "android.support.v7.widget.ActionMenuView{20c13e5 V.E...... ........ 936,0-1080,168}",
                        "id" => nil,
                   "visible" => true,
                      "rect" => {
              "height" => 168,
               "width" => 144,
                   "y" => 75,
                   "x" => 936,
            "center_x" => 1008,
            "center_y" => 159
        },
                   "enabled" => true,
        "contentDescription" => nil
    }
]
```
But I found another way to touch him:
`tap_when_element_exists("android.support.v7.widget.ActionMenuView index:0")`

As always there is only one OverflowMenuButton/ActionMenuView on screen, I believe that this is the best solution.
Do you agree?

**Comment by TobiasRoikjer** [comment]
@adrielcafe gestures will always perform on the first view found, so no need to specify index.

And yes, this is indeed the best solution!

**Comment by adrielcafe** [comment]
Nice! Thanks again @TobiasRoikjer!

**Comment by TobiasRoikjer** [comment]
You're welcome :)

**Comment by PriyalSayonetech** [comment]
Hope this could help you [ https://stackoverflow.com/questions/45727560/how-to-touch-the-overflow-button-in-calabash-android](url)
