### ISSUE TITLE
calabash run fails after upgrading to 0.7.1

### ISSUE THREAD

**Issue by xcjiang** [calabash/calabash-android#698]
it works very well on 0.6.0, but after upgrading to 0.7.1, it fails every time.

> No test server found for this combination of app and calabash version. Recreating test server.
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:188:in ``': No such file or directory - C:\Program Files\Java\jdk1
.8.0_60/bin/keytool.exe -v -printcert -J"-Dfile.encoding=utf-8" -file "C:/Users/xuanchen/AppData/Local/Temp/d20160319-5240-1l5c5m7/META-INF/CERT.RSA" (Err
no::ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:169:in `chdir'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:169:in `block in fingerprint_from_apk'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:168:in `fingerprint_from_apk'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/bin/calabash-android-build.rb:2:in `calabash_build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/lib/calabash-android/helpers.rb:106:in `build_test_server_if_needed'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/bin/calabash-android-run.rb:16:in `calabash_run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.1/bin/calabash-android:84:in `<top (required)>'
        from C:/Ruby22-x64/bin/calabash-android:23:in `load'
        from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'

**Comment by TobiasRoikjer** [comment]
Please don't post in multiple places: https://groups.google.com/forum/#!topic/calabash-android/T25q3KMOKII

We should have the discussion here.

**Comment by xcjiang** [comment]
I have figured it out, my keytool's path is **C:\Program Files\Java\jdk1 .8.0_60/bin/keytool.exe** , you can see there is a blank between Program and Files. so all you have to do is add double quotes to **Calabash::Android::Dependencies.keytool_path**

**Comment by TobiasRoikjer** [comment]
@xcjiang Thanks!

**Comment by TobiasRoikjer** [comment]
@xcjiang Upgrading to 0.7.2 should fix this issue.
