### ISSUE TITLE
wait_for_element_exists on webViews fails fast (Client-specific)

### ISSUE THREAD

**Issue by jsbakker** [calabash/calabash-android#706]
I have seen many similar issues dating back the past two years, but this specific issue I'm experiencing  was working in previous versions, and has recently broken.

I am not using Cordova for my app (I am using Xamarin), but a small yet important workflow in my app uses an embedded WebView. I have written the Calabash tests for this app and have successfully ran them on-device from a Windows machine for a couple of months now. When it was time to put them on a CI server running OS X this problem started (the Calabash version on which I wrote the tests is older than the most current version).

It seems that calls like `wait_for_element_exists("webView css:'#emailInput'")` used to work, but now it doesn't even wait; it will fail fast with the error:

> map webView css:'#emailInput', query failed because: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
>        (RuntimeError)

In the IRB shell, this call will function properly. I can even successfully call `enter_text` on this WebView using the same query string. However, when running this from the Gherkin scenario step-level, it always fails because it never waits for (what I'm guessing) the DOM to be available. If I put in a hard coded step `And I wait for 10 seconds` before the WebView query then it will work (not surprisingly). In addition, when I do add that wait and successfully automate the WebView controls, if this triggers a new page load within the same WebView, the same issue arises next time you try a query, and this additional wait must be put in after every page load before the first query.

The `server_version` and `client_version` are both reporting as 0.7.2 on the (problematic) OS X machine. The (working) Windows machine was on 0.6.0 of calabash-android. I updated the Windows machine to calabash-android 0.7.2 and sure enough, the tests stopped working.

The Android devices I've tested on are a Nexus 7 2nd gen running 5.1.1 and a Nexus 5 running 6.0.1.

Thanks.
Long-time Calabash user, first time complainer, Jeff.

**Comment by TobiasRoikjer** [comment]
@jsbakker Thank you for a very detailed error report. I have release 0.7.3.pre3 which aims to fix this. Could you please try that? I believe this is solved by this PR https://github.com/calabash/calabash-android-server/pull/21.

**Comment by jsbakker** [comment]
@TobiasRoikjer Thank you for the quick turnaround. I have confirmed that my tests with the WebView queries are now passing again using the calabash-android 0.7.3.pre3 gem. It is working on both the Windows client and the OS X client.

**Comment by TobiasRoikjer** [comment]
Released in 0.7.3. https://groups.google.com/forum/#!topic/calabash-android/n30CmBAlqLI

@jsbakker thank you for the bug report!
