### ISSUE TITLE
View Actions Failing after Replacing Data Set in RecyclerView Adapter

### ISSUE THREAD

**Issue by wokkaflokka** [calabash/calabash-android#707]
At the request of @TobiasRoikjer, I am replicating an issue filed in the calabash-android Google Group. [The issue is described here.](https://groups.google.com/d/msg/calabash-android/-CDfNr_hqCU/gSCS4twqCAAJ)

Thanks,
Emery

**Comment by TobiasRoikjer** [comment]
@wokkaflokka Thank you.
Possibly related to https://github.com/calabash/calabash-android/issues/690

**Comment by TobiasRoikjer** [comment]
@wokkaflokka I do not have the time to debug this. Would it be possible for you to send me an APK to reproduce this? You can send it to me in an email

**Comment by wokkaflokka** [comment]
@TobiasRoikjer I will provide a simple apk that outlines this issue. It may take me a few days to get around to it but it's officially on my list now.

Thanks,
E

**Comment by TobiasRoikjer** [comment]
@wokkaflokka Thank you! I appreciate it

**Comment by wokkaflokka** [comment]
@TobiasRoikjer FYI I did most of the demo today, just need to add one more thing and then provide a test harness. Will ping back tomorrow when done.

**Comment by wokkaflokka** [comment]
@TobiasRoikjer I provided a sample app + test harness here: https://github.com/wokkaflokka/calabash-rv-test

Notably, my test harness is not failing. I went ahead and revisited the initial test that was failing, and will report back here if it's working now. I'm certainly hoping that is not the case, as it will force me to re-evaluate my own sanity... ;)

**Comment by TobiasRoikjer** [comment]
@wokkaflokka Any update?

**Comment by wokkaflokka** [comment]
Probably worth closing this ticket as "Cannot Reproduce"

**Comment by TobiasRoikjer** [comment]
Alright thank you. Feel free to comment if it happens again.
