### ISSUE TITLE
Long Swipe on app

### ISSUE THREAD

**Issue by anishtim** [calabash/calabash-android#709]
Hi,

I'm trying to swipe from left to right on my app launch, using the predefined swipe feature (Then /^I scroll down$/) does not seem to work completely since, it swipes half way and returns to the same screen rather than going to the next screen.

I have tried, perform_action('drag',x1,x2,y1,y2), but with no help, does the same thing. 

any other way i could do this? Help.

**Comment by TobiasRoikjer** [comment]
Use `pan_down` or similar
