### ISSUE TITLE
Steps are undefined after upgrading to v0.7.3

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#710]
Hai,

I was using calabash-android version 0.6.0 and the scripts were successful and once after upgrading to v0.7.3 scripts started failing. It says steps are undefined even though all the steps were defined in a ruby file inside step_definitions folder.

```
Error:
You can implement step definitions for undefined steps with these snippets:
Given(/^I select country "([^"]*)"$/) do |arg1|
  pending # Write code here that turns the phrase above into concrete actions
end

The step defined in my .rb file is
- Then /^I select country "([^\"]*)"$/ do |xxx|
```

Is it something else I have to change in order to make this work or any other feature has been introduced in v0.7.3

Regards,
DineshKumar.

**Comment by DineshKumar7** [comment]
Found that the issue is with cucumber - I have uninstalled the cucumber v2.3.3 and re installed cucumber v1.3.20 and it works. Any idea what changes I have to do if I need to use the latest cucumber version?.

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 This is a Cucumber, issue not a Calabash issue.
