### ISSUE TITLE
Trying to run default test "no implicit conversion of nil into String (TypeError)"

### ISSUE THREAD

**Issue by noved210** [calabash/calabash-android#717]
Im trying to run a Cordova/Ionic application with Calabash tests. I have setup the default ionic project "tabs" and the default test with calabash (I know it will fail the steps but I want it to fail). When I run calabash-sandbox and do calabash-android setup and calabash-android. Looking at the code in the features/support/app_installation_hook.rb file it looks like I haven't properly linked up the .apk to the test when running cucumber. Also when I try to do "start_test_server_in_background" I get an error.

Error from running cucumber

[tbd@calabash-sandbox]$ cd platforms/android/
[tbd@calabash-sandbox]$ cucumber
Feature: Login feature

  Scenario: As a valid user I can log into my app # features/my_first.feature:3
  no implicit conversion of nil into String (TypeError)
  ./features/support/app_installation_hooks.rb:18:in `Before'
  no implicit conversion of nil into String (TypeError)
  ./features/support/app_life_cycle_hooks.rb:5:in `Before'
    When I press "Login"                          # calabash-android-0.7.2/lib/calabash-android/steps/press_button_steps.rb:17
    Then I see "Welcome to coolest app ever"      # calabash-android-0.7.2/lib/calabash-android/steps/assert_steps.rb:5

Failing Scenarios:
cucumber features/my_first.feature:3 # Scenario: As a valid user I can log into my app

1 scenario (1 failed)
2 steps (2 skipped)
0m0.900s

Error from console

[tbd@calabash-sandbox]$ calabash-android console /Users/tbd/Documents/myApp/platforms/android/build/outputs/apk/android-debug-unaligned.apk 

>'irb(main):002:0> start_test_server_in_background
android.util.AndroidException: INSTRUMENTATION_FAILED: com.ionicframework.myapp920638.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
	at com.android.commands.am.Am.runInstrument(Am.java:1093)
	at com.android.commands.am.Am.onRun(Am.java:371)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:100)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
RuntimeError: App did not start
	from /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:662:in `block in start_test_server_in_background'
	from /Users/tbd/.calabash/sandbox/Gems/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /Users/tbd/.calabash/sandbox/Gems/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:661:in `start_test_server_in_background'
	from /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:143:in `start_test_server_in_background'
	from (irb):2
	from /Users/tbd/.calabash/sandbox/Rubies/2.1.6-p336/bin/irb:11:in `<main>'

I'm not really sure if this is an ionic issue or a calabash configuration issue. Some guidance would be appreciated. I'm new to both calabash and ionic.

System info

[tbd@calabash-sandbox]$ calabash-android version
0.7.2

**Comment by TobiasRoikjer** [comment]
You should run reinstall_apps

**Comment by noved210** [comment]
That was it! Thank you so much!!
