### ISSUE TITLE
Issue with no implicit conversion of nil into String (TypeError) when running cucumber command

### ISSUE THREAD

**Issue by noved210** [calabash/calabash-android#720]
Having an issue running my tests using the cucumber command and I get this error:

[tbd@calabash-sandbox]$ cucumber 
Feature: Login feature

Scenario: As a valid user I can log into my app, thanks # features/my_first.feature:3
no implicit conversion of nil into String (TypeError)
./features/support/app_installation_hooks.rb:18:in Before' no implicit conversion of nil into String (TypeError) ./features/support/app_life_cycle_hooks.rb:5:inBefore'
Given The app has loaded # features/step_definitions/calabash_steps.rb:3

Failing Scenarios:
cucumber features/my_first.feature:3 # Scenario: As a valid user I can log into my app, thanks

1 scenario (1 failed)
1 step (1 skipped)
0m0.674s

I've tried specifying the App path using a command like this: APP_PATH=/Users/tbd/Desktop/master/platforms/android/build/outputs/apk/swept.apk

I'm not really sure what's going on but I can tell that it's because the application path isn't being set. I'm just not sure where to go from here :/

**Comment by noved210** [comment]
This is what the .rb file looks like for me

require 'calabash-android/management/app_installation'

AfterConfiguration do |config|
  FeatureMemory.feature = nil
end

Before do |scenario|
  scenario = scenario.scenario_outline if scenario.respond_to?(:scenario_outline)

  feature = scenario.feature
  if FeatureMemory.feature != feature || ENV['RESET_BETWEEN_SCENARIOS'] == '1'
    if ENV['RESET_BETWEEN_SCENARIOS'] == '1'
      log 'New scenario - reinstalling apps'
    else
      log 'First scenario in feature - reinstalling apps'
    end

    uninstall_apps
    install_app(ENV['TEST_APP_PATH'])
    install_app(ENV['APP_PATH'])
    FeatureMemory.feature = feature
    FeatureMemory.invocation = 1
  else
    FeatureMemory.invocation += 1
  end
end

FeatureMemory = Struct.new(:feature, :invocation).new

**Comment by TobiasRoikjer** [comment]
Please post the full stacktrace http://stackoverflow.com/a/3232892/4547279

**Comment by noved210** [comment]
[tbd@calabash-sandbox]$ cucumber features/my_first.feature -b
Feature: Login feature

  Scenario: As a valid user I can log into my app, thanks # features/my_first.feature:3
  no implicit conversion of nil into String (TypeError)
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/helpers.rb:13:in `exist?'
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/helpers.rb:13:in `package_name'
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:122:in `uninstall_apps'
  /Users/tbd/Desktop/master/platforms/android/features/support/app_installation_hooks.rb:18:in `block in <top (required)>'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_hook.rb:15:in `invoke'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/runtime/before_hooks.rb:21:in `block (2 levels) in before_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:31:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `each'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
  /Users/tbd/.calabash/sandbox/Gems/bin/cucumber:23:in `load'
  /Users/tbd/.calabash/sandbox/Gems/bin/cucumber:23:in `<main>'
  /Users/tbd/.calabash/sandbox/Gems/bin/ruby_executable_hooks:15:in `eval'
  /Users/tbd/.calabash/sandbox/Gems/bin/ruby_executable_hooks:15:in `<main>'
  no implicit conversion of nil into String (TypeError)
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/helpers.rb:13:in `exist?'
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/helpers.rb:13:in `package_name'
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:640:in `start_test_server_in_background'
  /Users/tbd/.calabash/sandbox/Gems/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:143:in `start_test_server_in_background'
  /Users/tbd/Desktop/master/platforms/android/features/support/app_life_cycle_hooks.rb:5:in `block in <top (required)>'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_hook.rb:15:in `invoke'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/runtime/before_hooks.rb:21:in `block (2 levels) in before_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:56:in `skip'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:27:in `skip'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:129:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `each'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `call'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:11:in `test_case'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
  /Users/tbd/.calabash/sandbox/Gems/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
  /Users/tbd/.calabash/sandbox/Gems/bin/cucumber:23:in `load'
  /Users/tbd/.calabash/sandbox/Gems/bin/cucumber:23:in `<main>'
  /Users/tbd/.calabash/sandbox/Gems/bin/ruby_executable_hooks:15:in `eval'
  /Users/tbd/.calabash/sandbox/Gems/bin/ruby_executable_hooks:15:in `<main>'
    Given The app has loaded                              # features/step_definitions/calabash_steps.rb:3

Failing Scenarios:
cucumber features/my_first.feature:3 # Scenario: As a valid user I can log into my app, thanks

1 scenario (1 failed)
1 step (1 skipped)
0m1.000s

**Comment by TobiasRoikjer** [comment]
the error message is not great, but it is because you need to supply APP_PATH and TEST_APP_PATH as env variables.

**Comment by TobiasRoikjer** [comment]
If you are unsure on how to run using Cucumber, just use calabash-android run

**Comment by noved210** [comment]
Thank you very much for the quick feedback and help!

**Comment by TobiasRoikjer** [comment]
You bet :)
