### ISSUE TITLE
Remove `done` from operations; conflicts with cucumber 2.0 `done`

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-android#722]
Related:
- https://groups.google.com/forum/#!topic/calabash-android/gtWjxL5dfI8
- KeyboardHelpers#done clobbers the Cucumber 2.1 method #done [#976](https://github.com/calabash/calabash-ios/issues/976)

Source:

https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/operations.rb#L1041

**Comment by TobiasRoikjer** [comment]
@jmoody Another reason to consider having some other scope than global for the calabash methods
