### ISSUE TITLE
Query Crosswalk-Webview in Calabash 0.7.3

### ISSUE THREAD

**Issue by sueess** [calabash/calabash-android#725]
I don't figure out how to query the crosswalk webview. Am I using the right selector?

Version 0.7.3
Crosswalk: Crosswalk 18

`irb(main):009:0> query("org.xwalk.core.internal.XWalkContentView css:'*'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map org.xwalk.core.internal.XWalkContentView css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: org.xwalk.core.internal.XWalkContentView.XWalkContentViewApi23 is not recognized a valid web view.`

**Comment by TobiasRoikjer** [comment]
You are not targeting the right selector :) I don't know which one is correct, but try querying for all classes and pick the right one :) Perhaps "org.xwalk.core.internal.XWalkContentView" is too broad.

**Comment by sueess** [comment]
Ok, I queried for ALL classes --> query("*") 
```
"class" => "com.android.internal.policy.PhoneWindow$DecorView"
"class" => "android.widget.LinearLayout"
"class" => "android.widget.FrameLayout"
"class" => "org.crosswalk.engine.XWalkCordovaView"
"class" => "org.xwalk.core.internal.XWalkViewBridge"
"class" => "org.xwalk.core.internal.XWalkContent$2"
"class" => "android.view.SurfaceView"
"class" => "org.xwalk.core.internal.XWalkContentView$XWalkContentViewApi23"
"class" => "android.view.View"
```

...and tried to query all resulting views:

```
query("android.widget.LinearLayout css:'*'")
query("android.widget.FrameLayout css:'*'")
query("org.xwalk.core.internal.XWalkViewBridge css:'*'")
query("org.xwalk.core.internal.XWalkContent$2 css:'*'")
query("android.view.SurfaceView css:'*'")
query("org.xwalk.core.internal.XWalkContentView$XWalkContentViewApi23 css:'*'")
query("android.view.View css:'*'")

Results of the commands above:
RuntimeError: map android.view.View css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.internal.policy.PhoneWindow.DecorView is not recognized a valid web view.

---

query("org.crosswalk.engine.XWalkCordovaView css:'*'")

Results of the command above:
RuntimeError: map org.crosswalk.engine.XWalkCordovaView css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
```

I don't see any "right" one? Or what am I doing wrong?

**Comment by TobiasRoikjer** [comment]
@sueess 
```
query("org.crosswalk.engine.XWalkCordovaView css:'*'")

Results of the command above:
RuntimeError: map org.crosswalk.engine.XWalkCordovaView css:'*', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
```

That seems like a bug in calabash, could you please post the full stacktrace from `adb logcat`?

**Comment by sueess** [comment]
```
06-03 17:26:06.074 30280-974/? W/System.err: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:67)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:52)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:68)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
06-03 17:26:06.074 30280-974/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-03 17:26:06.074 30280-974/? W/System.err: Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-03 17:26:06.074 30280-974/? W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
06-03 17:26:06.074 30280-974/? W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:178)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:63)
06-03 17:26:06.074 30280-974/? W/System.err: 	... 8 more
06-03 17:26:06.074 30280-974/? W/System.err: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:89)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:73)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryMatcher.call(UIQueryMatcher.java:23)
06-03 17:26:06.074 30280-974/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-03 17:26:06.074 30280-974/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-03 17:26:06.074 30280-974/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-03 17:26:06.074 30280-974/? W/System.err:     at android.os.Looper.loop(Looper.java:158)
06-03 17:26:06.074 30280-974/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7229)
06-03 17:26:06.074 30280-974/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-03 17:26:06.074 30280-974/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-03 17:26:06.074 30280-974/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-03 17:26:06.074 30280-974/? W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer$XWalkContent.<init>(WebContainer.java:276)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer$XWalkContent.getXWalkContentForView(WebContainer.java:270)
06-03 17:26:06.074 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:100)
06-03 17:26:06.084 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:46)
06-03 17:26:06.084 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.actions.webview.QueryHelper.executeAsyncJavascriptInWebContainer(QueryHelper.java:88)
06-03 17:26:06.084 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateForWebContainer(UIQueryASTWith.java:194)
06-03 17:26:06.084 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.access$100(UIQueryASTWith.java:23)
06-03 17:26:06.084 30280-974/? W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:87)
06-03 17:26:06.084 30280-974/? W/System.err: 	... 10 more
```

**Comment by salamalejkum** [comment]
Have the same issue.

**Comment by TobiasRoikjer** [comment]
@sueess Could you send me an APK to reproduce?

**Comment by sueess** [comment]
I sent it to you. Many thanks for a feedback!

**Comment by sueess** [comment]
Any news?

**Comment by OskJonsdottir** [comment]
Same issue here with calabash 0.7.3 and crosswalk 20.50.533.3. Works fine with crosswalk 15.44.384.13

**Comment by OskJonsdottir** [comment]
A typical stack trace: 
`      map XWalkCordovaView css:'a' {textContent CONTAINS 'LOG IN'}, query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       (RuntimeError)
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:869:in `screenshot_and_raise'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/wait_helpers.rb:123:in `handle_error_with_options'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/wait_helpers.rb:52:in `rescue in wait_for'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/wait_helpers.rb:38:in `wait_for'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/wait_helpers.rb:97:in `wait_for_elements_exist'
      /tmp/scratchHy57AH.scratch/featuresU9OMSJ/features/step_definitions/azoomee_steps.rb:9:in `block in <top (required)>'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/core_ext/instance_exec.rb:48:in `instance_exec'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/core_ext/instance_exec.rb:48:in `block in cucumber_instance_exec'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/core_ext/instance_exec.rb:69:in `cucumber_run_with_backtrace_filtering'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/core_ext/instance_exec.rb:36:in `cucumber_instance_exec'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_step_definition.rb:97:in `invoke'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/step_match.rb:25:in `invoke'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_invocation.rb:60:in `invoke'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_invocation.rb:38:in `accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:106:in `block in visit_step'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:105:in `visit_step'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_collection.rb:19:in `block in accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_collection.rb:18:in `each'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/step_collection.rb:18:in `accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:100:in `block in visit_steps'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:99:in `visit_steps'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:15:in `block in execute'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:83:in `block (2 levels) in with_hooks'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:99:in `before_and_after'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:82:in `block in with_hooks'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:120:in `call'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/language_support/language_methods.rb:9:in `block in around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/language_support/language_methods.rb:97:in `call'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/language_support/language_methods.rb:97:in `execute_around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/language_support/language_methods.rb:8:in `around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:119:in `block (2 levels) in around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:123:in `call'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:123:in `around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:94:in `around'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:81:in `with_hooks'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:13:in `execute'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario.rb:32:in `block in accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario.rb:79:in `with_visitor'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/scenario.rb:31:in `accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:58:in `block in visit_feature_element'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:57:in `visit_feature_element'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.rb:38:in `block in accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.rb:37:in `each'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/feature.rb:37:in `accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/features.rb:28:in `block in accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/features.rb:17:in `each'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/features.rb:17:in `each'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/features.rb:27:in `accept'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:49:in `run!'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:47:in `execute!'
      /home/rwx/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.19/bin/cucumber:13:in `<top (required)>'
      /home/rwx/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `load'
      /home/rwx/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `<main>'
      features/kidmode.feature:7:in `When I wait for the initial page'`

**Comment by OskJonsdottir** [comment]
Same issue here, seems to happen with crosswalk 20.50.533.3, but not with 15.44.384.13.

**Comment by OskJonsdottir** [comment]
A typical stack trace...
```
06-16 14:57:57.737 20621-20886/com.tinizine.azoomee W/System.err: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:67)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:52)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:68)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err: Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:93)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:177)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:63)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err: 	... 8 more
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:89)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:73)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryMatcher.call(UIQueryMatcher.java:23)
06-16 14:57:57.738 20621-20886/com.tinizine.azoomee W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at android.os.Looper.loop(Looper.java:194)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5637)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer$XWalkContent.<init>(WebContainer.java:276)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer$XWalkContent.getXWalkContentForView(WebContainer.java:270)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:100)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:46)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.actions.webview.QueryHelper.executeAsyncJavascriptInWebContainer(QueryHelper.java:88)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateForWebContainer(UIQueryASTWith.java:194)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.access$100(UIQueryASTWith.java:23)
06-16 14:57:57.739 20621-20886/com.tinizine.azoomee W/System.err:     at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$Matcher.matchForUIObject(UIQueryASTWith.java:87)
```

**Comment by OskJonsdottir** [comment]
This happens with a selector that is not '*' in my case:

```
 map XWalkCordovaView css:'a' {textContent CONTAINS 'LOG IN'}, query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
```

**Comment by OskJonsdottir** [comment]
This seems to be an issue of calabash-android-server specifically.

The problem is due to the way the method isCrossWalkContentClass() in the class WebContainer decides whether the view is a crosswalk webview or not. The code of the method reads

```
    private static boolean isCrossWalkContentClass(Class<?> clz) {
        return superClassEquals(clz, "org.xwalk.core.internal.XWalkContent") ||
                superClassEquals(clz, "org.xwalk.core.internal.XWalkContent$1");
    }
```

Apparently in recent versions of Crosswalk (>18) the content class is actually ```org.xwalk.core.internal.XWalkContent$2```, so that method returns false for the actual content class. The constructor of the inner class WebContainer.XWalkContent relies on the above method to decide whether it has found the View object that holds the contents in Crosswalk. It traverses down the hierarchy of Views of the Activity expecting to find one for which the above method returns true. 

```
        private XWalkContent(View view) {
            xWalkContent = view;

            while (!isCrossWalkContentClass(xWalkContent.getClass())) {
                xWalkContent = getChildOf((View)xWalkContent);
            }
```

The problem is that in our case the method never returns true, so at some point we reach the bottom of the hierarchy and the method getChildOf() returns null for the current view we are testing. In the next iteration, getClass() is applied to a null reference, and an exception is raised.

I've created a pull request that fixes this problem, at least when I try to run my tests locally. 

https://github.com/calabash/calabash-android-server/pull/26

@TobiasRoikjer, can you please take a look and let me know if you think my approach is reasonable?

Cheers.

**Comment by TobiasRoikjer** [comment]
@OskJonsdottir Thank you for an excellent PR and an extremely good writeup. Your help is greatly appreciated!

I have commented on your PR

**Comment by sueess** [comment]
Thanks guys for solving this problem. Is there any pre-release I can get with this fix?

**Comment by twavis** [comment]
Awesome job on the fix. Just wondering when it will be pushed out?

Thanks!

**Comment by TobiasRoikjer** [comment]
@sueess @twavis There is an 0.8.0.pre2 out

**Comment by sueess** [comment]
Nice...it works perfect! Thanks again!
