### ISSUE TITLE
Unable to read text from hybrid app with org.apache.cordova.CordovaWebView

### ISSUE THREAD

**Issue by govindanarayana** [calabash/calabash-android#727]
While trying to automate an hybrid app which is using org.apache.cordova.CordovaWebView.
I am able to get the list of elements of the app using query('CordovaWebView css"*"')
but when i try to read or get the text typed in any text box i dont get any result as below is the output of the query command i tried.

_### irb(main):094:0> query("CordovaWebView xpath:'//input' {html CONTAINS 'UserCorporateId'}")
[
    [0] {
              "class" => "login-input-style ng-valid-maxlength ng-dirty ng-valid-parse ng-touched ng-valid ng-valid-requ
ired",
           "nodeType" => "ELEMENT_NODE",
                 "id" => "login-form",
        "textContent" => "",
               "html" => "<input ng-model=\"fields.finacleUserCorporateId\" class=\"login-input-style ng-valid-maxlength
 ng-dirty ng-valid-parse ng-touched ng-valid ng-valid-required\" type=\"text\" id=\"login-form\" clear-warning=\"fields.
finacleUserCorporateId\" ng-blur=\"myProfile.rememberUserID.focusShift();\" autocorrect=\"off\" autocapitalize=\"none\"
ng-change=\"(myProfile.rememberUserID.rememberUser.length==0 || (myProfile.rememberUserID.rememberUser | filter:fields.f
inacleUserCorporateId).length ==0)?\n\t\t\t\t\t\t\tmyProfile.rememberUserID.autoCompleteChk='0':fields.finacleUserCorpor
ateId.length==0 ?\n\t\t\t\t\t\t\t myProfile.rememberUserID.autoCompleteChk='0':myProfile.rememberUserID.autoCompleteChk=
'1'\" maxlength=\"32\" required=\"\">",
               "rect" => {
                   "y" => 254,
                   "x" => 38,
            "center_x" => 172,
              "height" => 51,
               "width" => 269,
                 "top" => 166.78125,
                "left" => 28.75,
            "center_y" => 279
        },
           "nodeName" => "INPUT",
            "webView" => "NoResourceEntry-100"
    }
]_

Let me know if i need to try some other way to read the text from this INPUT element?
when i use UIAUTOMATORVIEWER the same element is getting identified in automatorviewer as android.widget.EditText class element and content-desc shows the text i had typed.
Please help in reading text from this element in calabash-android.
I have calabash-android (0.6.0) gem.

_irb(main):106:0> classes("*")
[
    [0] "com.android.internal.policy.PhoneWindow$DecorView",
    [1] "android.widget.LinearLayout",
    [2] "android.widget.FrameLayout",
    [3] "org.apache.cordova.LinearLayoutSoftKeyboardDetect",
    [4] "org.apache.cordova.CordovaWebView"
]_

**Comment by TobiasRoikjer** [comment]
In HTML forms, it is not the text that is set, but the "value". You can obtain this using javascript. See this as an example https://github.com/calabash/calabash-android/blob/master/ruby-gem/api/features/steps/shared_keyboard.rb#L20
