### ISSUE TITLE
Unable to scroll down CordovaWebView screen

### ISSUE THREAD

**Issue by govindanarayana** [calabash/calabash-android#728]
I am trying to scroll down a screen which a CordovaWebView.
Below is the output on the calabash android console

_irb(main):060:0> scroll_down
[
    [0] " < VOID >" 

but nothing happens on the application screen on the device/emulator.

Kindly help

**Comment by TobiasRoikjer** [comment]
Scrolling on Cordova WebViews may not be supported, as scrolling is not a synthetic human interaction, but a programmatic one. I suggest using gestures like `pan_up`
