### ISSUE TITLE
No implicit conversion

### ISSUE THREAD

**Issue by shubzinator** [calabash/calabash-android#730]
I am getting the following trying to run a demo test:

no implicit conversion of nil into String (TypeError)
  ./features/support/app_installation_hooks.rb:18:in `Before'
  no implicit conversion of nil into String (TypeError)
  ./features/support/app_life_cycle_hooks.rb:5:in `Before'`

Please, help.

**Comment by TobiasRoikjer** [comment]
Please search before opening an issue. There are many results for `no implicit conversion of nil into String "calabash-android"`
