### ISSUE TITLE
App Did Not Start on First Scenario

### ISSUE THREAD

**Issue by michaelsabo** [calabash/calabash-android#739]
Since our company upgraded to El Capitan, we've been noticing that our first scenario always fails with App Did Not Start error when running locally (CI environment is not impacted). After doing some debugging I learned that if I increased the retriable to 200 in **start_test_server_in_background**, this eliminated the problem. The main difference between our Macbooks and CI environment, is that our Macbooks have FileVault turned on. We've seen similar issues with the calabash-ios gem as well after upgrading to El Capitan, I suspect because that OS release had significant security upgrades. 

Do you think it would be reasonable for me to make a Pull Request that allows the **start_test_server_in_background** method to take in an option allowing us to set the number of tries for that block. 

I imagine it would look something like this in the launch hook:

```
start_test_server_in_background({app_launch_tries: 200})
```

And in the [operations.rb ](https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/operations.rb#L671)

```
app_tries = env_options['app_launch_tries'] || 100

Retriable.retriable :tries => app_tries, :interval => 0.1 do
      raise "App did not start" unless app_running?
 end
```

Any comments or discussion is appreciated. 

Mike

**Comment by TobiasRoikjer** [comment]
I think this addition is very reasonable, does increasing the app launch tries fix the issue on the computer? @jmoody what is your opinion?

**Comment by michaelsabo** [comment]
@TobiasRoikjer Yes, it fixes the issue for our Macbooks. I should add that we are using the latest 15inch Macbook Pro's with 16gb memory. 

We also receive the App Did Not Start on the next scenario after calling **clear_app_data**, so this would also help fix those failures. It seems that the initial launch after install or deleting of app data, increases the amount of time for the app launch. I used [ruby-prof](https://github.com/ruby-prof/ruby-prof) to analyze the **start_test_server_in_background** and it shows the thread sleeping for the 10 second retriable block. 

I checked the spec folder and didn't find any tests for the Device class, so not sure if you would like me to add tests for this PR. I assume these tests would need to make use of rspec's test double if we were to add any. 

Mike

**Comment by andrelugomes** [comment]
I have a similar ISSUE whern call start_test_server_in_background on first scenario.

`App did not start (RuntimeError)
  ./features/support/app_life_cycle_hooks.rb:7:in `Before'
`
maybe this improvement solve my problem

**Comment by TobiasRoikjer** [comment]
This has been implemented

**Comment by andrelugomes** [comment]
@TobiasRoikjer witch version? because I using  calabash-android-0.8.4 and nothing. Or was it a different implementation?

**Comment by TobiasRoikjer** [comment]
There are many reasons why this error occurs, see `adb logcat` for the details

**Comment by andrelugomes** [comment]
In my case, that occurs because app realy not is running. It takes to long.

`
Before do |scenario|
  #start_test_server_in_background({app_launch_tries: 300})

  max_retries = 3
  begin
  	start_test_server_in_background
  rescue 
  	retry unless default_device.app_running? or (max_retries -= 1).zero?
  end 
end
`

I solved retrying start test server
