### ISSUE TITLE
Injecting to another application requires INJECT_EVENTS

### ISSUE THREAD

**Issue by ShraddhaGadesha** [calabash/calabash-android#749]
Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError) I am getting error when i write Then I press view with id "button1" in my test case in android 5.1 and 4.3

**Comment by TobiasRoikjer** [comment]
You are likely touching coodinates that are obscured by the keyboard or another application that is not the application under test

**Comment by raj284** [comment]
i am also seeing this in some devices. Any solution to fix this?

**Comment by srinukodi** [comment]
Hi @TobiasRoikjer 
I have a screen on which i have only one button and when i try to click on that button, i am getting the below exception.
**Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError)**

calabash-android version : 0.9.0
emulator version : API 25

Can you please let me know the solution as you have closed the issue in above thread.

**Comment by gowrojisunil** [comment]
Any update on this issue ? i see this issue when  i enter the url in the Edittext box.
