### ISSUE TITLE
Cannot resign the .apk file -  No MD5 fingerprint found

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#752]
Hai, 
        I am getting an error while trying to resign the .apk file. Please check on the below error.

/var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/helpers.rb:198:in `extract_md5_fingerprint': No MD5 fingerprint found: (RuntimeError)
 Alias name: androiddebugkey
Creation date: 2016 Jul 17
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Android Debug, O=Android, C=US
Issuer: CN=Android Debug, O=Android, C=US
Serial number: 117c5a8a
Valid from: Sun Jul 17 01:33:01 EDT 2016 until: Thu Dec 03 00:33:01 EST 2043
Certificate fingerprints:
	 SHA1: 2A:E4:9D:AA:C5:5A:AA:09:2F:D2:02:6A:53:B9:C1:5D:BB:E9:DE:5D
	 SHA256: 68:FB:7E:25:8A:63:5A:B8:DD:0E:FB:D4:A2:0D:F0:9C:9B:CC:B3:54:22:34:2F:80:A6:00:BB:4D:BE:6A:2F:B7
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: RSA (2048)
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: DF 66 8D 51 7D BA 0C D6   10 D9 DC 06 90 97 5A 23  .f.Q..........Z#
0010: C6 B0 9E 26                                        ...&
]
]

	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/java_keystore.rb:41:in `initialize'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/java_keystore.rb:80:in `new'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/java_keystore.rb:80:in `read_keystore_with_default_password_and_alias'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/java_keystore.rb:99:in `get_keystores'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/helpers.rb:157:in `sign_apk'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/helpers.rb:118:in `block in resign_apk'
	from /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/lib/calabash-android/helpers.rb:112:in `resign_apk'
	from /var/lib/gems/2.3.0/gems/calabash-android-0.8.0/bin/calabash-android:127:in `<top (required)>'
	from /usr/local/bin/calabash-android:23:in `load'
	from /usr/local/bin/calabash-android:23:in `<main>'

Calabash android version - 0.8
Ruby version - 2.3.1
Java - java-9-openjdk-amd64

**Comment by TobiasRoikjer** [comment]
I suggest downgrading to a java-8 SDK

**Comment by DineshKumar7** [comment]
I have downloaded java-8 sdk and have added the path to JAVA_HOME. However I am still getting the same error. Is anything else I have too look for?.

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 How did you create the keystore?

**Comment by DineshKumar7** [comment]
I used the below command to generate it inside .android folder. 

expect -c 'spawn keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -validity 14000 ; expect "What is your first and last name?" ; send "Android Debug\n" ; expect "What is the name of your organizational unit?" ; send "Android\n" ; expect "What is the name of your organization?" ; send "\n" ; expect "What is the name of your City or Locality?" ; send "\n" ; expect "What is the name of your State or Province?" ; send "\n" ; expect "What is the two-letter country code for this unit?" ; send "US\n" ; expect "Is CN=Android Debug, OU=Android, O=Unknown, L=Unknown, ST=Unknown, C=US correct?" ; send "yes\n" ; interact'

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 What OS are you running?

**Comment by DineshKumar7** [comment]
Please check on the below details. Thanks

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by DineshKumar7** [comment]
Hai any update on the above issue. Thanks

**Comment by DineshKumar7** [comment]
Closing this issue as the issue is resolved after completely removing java from the system (http://askubuntu.com/questions/84483/how-to-completely-uninstall-java) and and reinstalling the java-8 jdk. 

Once after re installation of java - MD5 certificate is created on generating debug keystore.
