### ISSUE TITLE
Cucumber#done is being clobbered by Operations#done

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-android#753]
I think the correct solution is to remove #done from the Operations API - it is `ni`.

https://github.com/calabash/calabash-ios/issues/976

Reported by @iushakov in Gitter.

**Comment by TobiasRoikjer** [comment]
A PR that removes this will be merged immediately

**Comment by jamespullar** [comment]
I believe this is resolved per https://github.com/calabash/calabash-android/issues/722
