### ISSUE TITLE
keyboard_enter_text broken on api 24

### ISSUE THREAD

**Issue by major-laslo** [calabash/calabash-android#754]
On API 24 (both emulator and device), keyboard_enter_text("text") fails with:

Action 'keyboard_enter_text' unsuccessful: java.lang.NoSuchFieldException: No field mServedInputConnection in class Landroid/view/inputmethod/InputMethodManager; (declaration of 'android.view.inputmethod.InputMethodManager' appears in /system/framework/framework.jar:classes2.dex) (RuntimeError)

The same failure happens on native (edittext) and webview input fields.

This is on a Nexus 5X Nougat Developer Preview 5

**Comment by TobiasRoikjer** [comment]
Upgrade your version of Calabash.

**Comment by gabrielpaulino** [comment]
What the solution to the problem?

**Comment by major-laslo** [comment]
As Tobias responded, there was a new version of calabash that supported API 24.

**Comment by gabrielpaulino** [comment]
I updated my calabash but still this error continues with this API. I'm using one last version. What version of support for this API?
