### ISSUE TITLE
keyboard_enter_text misbehave on api23

### ISSUE THREAD

**Issue by Mahasemamtan** [calabash/calabash-android#755]
On API 23 (both emulator and device), keyboard_enter_text"text" enters only ONE digit. 
On API 22 works fine on emulator, but on real device, only 1 digit is entered. 

There is no error message, no way to track this down.
Only way to enter more then 1 digits is using for loop, witch is terribly slow.

**Comment by TobiasRoikjer** [comment]
What version of Calabash are you using?

**Comment by Mahasemamtan** [comment]
It is 0.7.3, upgraded to 0.8.0. On api 22 works, on api 23 and api 24 it enters only first digit.

**Comment by TobiasRoikjer** [comment]
You should disable any auto correction on the keyboard

**Comment by Mahasemamtan** [comment]
Yup, just tried. Still one digit only. Tired on Galaxy S6 edge+, 6.0.1.

**Comment by TobiasRoikjer** [comment]
Could you send me the APK to reproduce?

**Comment by Mahasemamtan** [comment]
Sorry for slow response.
Can't send you .apk file, im not the owner. But anyways, while trying to make an demo .apk to send you, with input field that makes problems for me, I found out that it is about our css or something that disables calabash from entering text in it. Still looking for issue.
Anyways, thank you all.

**Comment by Mahasemamtan** [comment]
Hello again,
Just an info for all of you, might be useful..
We tracked down the problem for calabash not entering more then 1 digits in the input field.
We are having angular binding validation in this format: 
this.value = this.value.replace(/[^0-9.]/g, '');
With that line, calabash enters only first digit.
