### ISSUE TITLE
Test is marked as passed despite failure in hook

### ISSUE THREAD

**Issue by Spitigala** [calabash/calabash-android#756]
I have a number of tests with tagged hooks that run at the end to do some database checks. When there is a failure within the hook, I see from the logs that an error is raised and the scenario is marked as failed. However, the generated cucumber-junit XML report does not show any failures and marks the test as passed. I'm not sure if this is a bug or if my configuration is incorrect. How can I get a hook failure to count as a test failure in the report?

Using `'calabash-android' gem "0.6.0"`

**Comment by TobiasRoikjer** [comment]
This is a Cucumber question, you should post it in the Cucumber help pages. You can specify which version of Cucumber to use in your Gemfile.
