### ISSUE TITLE
Scroll_down is not working on `android.support.v7.widget.RecyclerView`

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#762]
I am trying to use `scroll_down` on App screen which has `android.support.v7.widget.RecyclerView` and it resulted in error.

Calabash version - 0.8.0

**Comment by TobiasRoikjer** [comment]
You are reporting an issue without supplying any information. We cannot debug this for you.

**Comment by DineshKumar7** [comment]
Hai, Please check on the below details for the error.

irb(main):003:0> scroll_down
Calabash::Android::WaitHelpers::WaitError: Could not find any scrollable views
	from /var/lib/gems/2.0.0/gems/calabash-android-0.8.0/lib/calabash-android/operations.rb:1098:in `rescue in find_scrollable_view'
	from /var/lib/gems/2.0.0/gems/calabash-android-0.8.0/lib/calabash-android/operations.rb:1081:in `find_scrollable_view'
	from /var/lib/gems/2.0.0/gems/calabash-android-0.8.0/lib/calabash-android/operations.rb:1107:in `scroll_down'


Note: That the view of the screen is - `android.support.v7.widget.RecyclerView`

**Comment by TobiasRoikjer** [comment]
just tell Calabash which view you are looking to scroll, e.g. ` scroll_down("android.support.v7.widget.RecyclerView")`

**Comment by DineshKumar7** [comment]
Thanks a lot on quick reply. It worked on specifying the view.

**Comment by ldasilvaNZ11** [comment]
DineshKumar7,

Can you share how you implemented your scroll_down to work?

This is what I am trying to call:

*And I scroll down until I find "textViewQuestionsLabel"*


This is my code to execute my call:


> *When(/^I scroll down until I find "([^"]*)"$/) do |arg1|*
> *  scroll_to("TextView id:'#{arg1}'")**end*

**Comment by DineshKumar7** [comment]
Hai ldasilvaNZ11
       I use scroll("android.support.v7.widget.RecyclerView", :down) - It is just to scroll down, where the class:"android.support.v7.widget.RecyclerView" is my screen view. However seeing on your implementation, you are trying to scroll down until you find your element identifier. May be the info on this link will be helpful for you - https://github.com/calabash/calabash-android/blob/master/migrating_to_calabash_0.5.md.
