### ISSUE TITLE
version of calabash-android

### ISSUE THREAD

**Issue by Galileo1** [calabash/calabash-android#763]
Hey, 

I m quite new to calabash android and I have it going on my machine and the version that I have is 0.8.
I am more reliant on the canned step definition at the moment and mostly refer to this github repo (https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/canned_steps.md ). But sometimes the canned steps doesn't work.I wonder if there is a difference in the implementation of step-def here in documentation and the actual installation??
How can I verify that as the steps sometime doesn't work?

Thanks

**Comment by TobiasRoikjer** [comment]
You should always run using bundler to ensure you are using the right version. The predefined steps are generally deprecated, and we always recommend you write you own steps that are suitex for your particular tests.
