### ISSUE TITLE
pressing button not working...

### ISSUE THREAD

**Issue by ldasilvaNZ11** [calabash/calabash-android#764]
I have two scenarios below, where scenario 1 works, BUT scenario 2 doesn't. When comes time to do the step <And I press "Items I'm selling"> the app doesn't press the button.

1-
Scenario: As a valid user I can log into my app via List an item screen
   When I see "Browse categories"
   And I press "Navigate up"
   Then I scroll down
   And I press "List an item"
2-
Scenario: As a valid user I can log into my app via Items I'm selling screen
   When I see "Browse categories"
   And I press "Navigate up"
   Then I scroll down
   And I press "Items I'm selling"
  
I have checked the <"Items I'm selling"> text matches exactly the text which is returned to see each element id from android device monitor. So my only guess is that <"Items I'm selling"> have more characters than <"List an item"> therefore it breaks on step 2 but not on step 1?

Any thoughts, or has anyone encountered similar issue before?

**Comment by ldasilvaNZ11** [comment]
Thanks, I have tried to test it but actions happen way to fast to notice anything. I can see it clicking on certain places but definitely not working for every single touch performed.

I have set my testing device for:

 settings > developer options > then under 'input' I have checked the 'show touches' box

**Comment by TobiasRoikjer** [comment]
You can have Android display the previously touched coordinates as well, that option is right besides it.

We can't really use these issues for Calabash support, so I will close this
