### ISSUE TITLE
Getting runtime error - System services not available to Activities before onCreate()

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#766]
Hai,
 
   I am seeing the below error for the condition - wait_for(:timeout => 60) { element_does_not_exist("* id:'splash_progress'")}

`Error is - map * id:'splash_progress', query failed because: System services not available to Activities before onCreate()
       (RuntimeError)`

This is the first time I am seeing this issue - `System services not available to Activities before onCreate()`. It would be really great if someone provide some info on how to fix this. Thanks.

Calabash-Android version - 0.8.0

**Comment by TobiasRoikjer** [comment]
Please provide all information when creating issues. Especially the stacktrace from adb logcat.

**Comment by DineshKumar7** [comment]
Hai, 

This is what I get in the adb logcat. 

`W/System.err( 3388): 	at sh.calaba.instrumentationbackend.utils.WindowManagerWrapper.getWindowManagerFromContext(WindowManagerWrapper.java:32)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.utils.WindowManagerWrapper.fromContext(WindowManagerWrapper.java:22)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.getRootViews(UIQueryUtils.java:201)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.automation.CalabashAutomationEmbedded.getRootViews(CalabashAutomationEmbedded.java:32)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.automation.CalabashAutomationEmbedded.getRootViews(CalabashAutomationEmbedded.java:13)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.InstrumentationBackend.getRootViews(InstrumentationBackend.java:55)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.query.Query.rootViews(Query.java:172)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:56)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:575)
W/System.err( 3388): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
`

**Comment by krimsonas** [comment]
I am having same issue. This happens randomly on my test runs. What might hint you to the right direction is that in one of the crash screenshots it happened on animation from one view to another

**Comment by TobiasRoikjer** [comment]
This is a bug in Calabash-Android, and will be fixed by next patch release.

**Comment by TobiasRoikjer** [comment]
https://github.com/calabash/calabash-android-server/pull/32
