### ISSUE TITLE
Lots of "Invalid date/time in zip entry" warnings with the latest android gradle plugin

### ISSUE THREAD

**Issue by jonasfa** [calabash/calabash-android#769]
The fix is available in the related library and described in: https://github.com/rubyzip/rubyzip/issues/112#issuecomment-83734033

**Comment by TobiasRoikjer** [comment]
I don't really see the issue here, Calabash-Android depends on some rubyzip 1.x https://github.com/calabash/calabash-android/blob/master/ruby-gem/calabash-android.gemspec#L35

I don't think it is a good idea to further restrict the version we depend on.

**Comment by jonasfa** [comment]
It's reproducible with `com.android.tools.build:gradle:2.2.0-beta2` + gradle 2.14.1.
The issue is gone when I use `2.1.2` + gradle 2.10.

**Comment by TobiasRoikjer** [comment]
Calabash-Android is a Ruby framework, and though it might be invoked through a gradle script, it has nothing to do with it. I am glad your issue is resolved.

**Comment by jonasfa** [comment]
My issue is not resolved and and I've never said calabash is invoked through a gradle script.

The issue is reproducible with APKs *generated by gradle*.

**Comment by jonasfa** [comment]
Which is the only officially supported way to generate APKs, by the way.

**Comment by jonasfa** [comment]
Downgrading is not an acceptable solution.

**Comment by TobiasRoikjer** [comment]
@jonasfa Alright. I still don't think it is a good idea to further restrict the version of rubyzip we depend on, especially since it is just warnings.

In your Gemfile, you can set the version of rubyzip you want to use to the latest 1.x version which removes the warnings.

**Comment by jonasfa** [comment]
@TobiasRoikjer it's more than **2.000 lines of warnings** in my case, and just force-upgrading rubyzip doesn't suppress the warnings, as described in the link I've provided in my first comment.

**Comment by ivan-fedorov** [comment]
I also have faced with this problem. Android project uses com.android.tools.build:gradle:2.2.0.
calabash-android version is 0.8.1
rubyzip in Gemfile.lock is set to rubyzip (~> 1.1)
When I run `bundle exec calabash-android console MyApp.apk` is see lots of messages 'Invalid date/time in zip entry'

**Comment by nadzeya** [comment]
I also have it in logs :(
calabash-android (0.8.2)

**Comment by garyjohnson** [comment]
Also having this issue. Haven't been able to try 1.2.0 because fastlane forces us into 1.1.x, unfortunately.

**Comment by olefriis** [comment]
In all fairness, it seems like it's the newest Android build tools that are generating APKs with omitted time stamps. Try to simply `unzip` an APK from the command line. I get files with the date `Dec 31  1979`.

However, as that is a fact of life, I agree that it would be nice if Calabash wouldn't bitch too much about it. How about doing

```ruby
Zip.warn_invalid_date = false if Zip.respond_to? :warn_invalid_date=
```

somewhere? I'm just not sure where that line would fit best. https://github.com/calabash/calabash-android/blob/da4e52ee53eca8024c11b461a3ed43551b271fdf/ruby-gem/lib/calabash-android/helpers.rb near the top?

**Comment by TobiasRoikjer** [comment]
@olefriis https://github.com/calabash/calabash-android/pull/779. This PR silences warnings only when Calabash uses it

**Comment by TobiasRoikjer** [comment]
Rubyzip is silenced in 0.8.3

**Comment by olefriis** [comment]
@TobiasRoikjer: 👍 (And kudos for super nice test coverage as well!)
