### ISSUE TITLE
evaluate_javascript() throws an error in calabash-android(0.7.2)

### ISSUE THREAD

**Issue by sureshraj1992** [calabash/calabash-android#775]
evaluate_javascript() method thorws error while executing the test suite in AWS device farm.

**Error message**
undefined method `map' for nil:NilClass (NoMethodError)

gems/ruby-2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb: 1234 :in `evaluate_javascript'

**Comment by TobiasRoikjer** [comment]
Please upgrade to the latest version
