### ISSUE TITLE
Unable to get web elements in android app 

### ISSUE THREAD

**Issue by raj284** [calabash/calabash-android#777]
My android app has payment options. So when i tap on pay it opens a web view where i have to enter the card details and pay. 

I am trying to identify the elements in web view but command is not returning any elements. I have used following commands:

query("webView css:'#header'")
query("webView css:'*'")
query("SystemWebView css:'#header'")

Please help me. There is no enough documentation is available regarding this. do i need any specific setup?

**Comment by TobiasRoikjer** [comment]
Likely the class is not webView nor SystemWebView. query("*") and find the right view.

**Comment by raj284** [comment]
@TobiasRoikjer  it is advanced webview. but i am not able to query;


 [ 6] {
                     "class" => "com.practo.fabric.ui.AdvancedWebView",
                       "tag" => nil,
               "description" => "com.practo.fabric.ui.AdvancedWebView{b64fc31 VFEDHVC.. .F...... 0,196-1440,2308 #7f0c0215 app:id/wv_main}",
                        "id" => "wv_main",
                   "visible" => true,
                      "rect" => {
              "height" => 2112,
               "width" => 1440,
                   "y" => 280,
                   "x" => 0,
            "center_x" => 720,
            "center_y" => 1336
        },
                   "enabled" => true,
        "contentDescription" => nil
    },
