### ISSUE TITLE
0.8.3 crashing from fingerprint_from_apk

### ISSUE THREAD

**Issue by zanzaben** [calabash/calabash-android#780]
When I updated to 0.8.3 any test I tried to run would crash within seconds. I have reverted back to 0.8.2 for now. If you need any other info I will be glad to help. 

Here is the command line I am running and the output. 
`
C:\git\mcc\AutomatedTests\test_home>bundle exec parallel_calabash -a "..\apks\MCCNotes-7337.apk" --phone_profile phone_parallel --tablet_profile tablet_parallel --group-by-scenarios  -o '--tags ~@in_progress --tags @testing --tags ~@pending_defect '

*******************************
 1 DEVICES FOUND:
146e9c31
SM_G935V
false
146e9c31_
*******************************
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
  Running with 1 threads: [["features/Login.feature:16"]]
0>> Command: (SET "AUTOTEST=1") & (SET "ADB_DEVICE_ARG=146e9c31") & (SET "DEVICE_INFO=SM_G935V") & (SET "TEST_PROCESS_NUMBER=1") & (SET "TOTAL_PROCESS_COUNT=1") & (SET "SCREENSHOT_PATH=146e9c31_") & calabash-android run ..\apks\MCCNotes-7337.apk --tags ~@in_progress --tags @testing --tags ~@pending_defect   -p phone_parallel features/Login.feature:16
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/lib/calabash-android/helpers.rb:173:in `block (2 levels) in fingerprint_from_apk': uninitialized constant Calabash::Utils (NameError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/lib/calabash-android/helpers.rb:169:in `chdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/lib/calabash-android/helpers.rb:169:in `block in fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/lib/calabash-android/helpers.rb:168:in `fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/bin/calabash-android-build.rb:2:in `calabash_build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/lib/calabash-android/helpers.rb:106:in `build_test_server_if_needed'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/bin/calabash-android-run.rb:16:in `calabash_run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.8.3/bin/calabash-android:85:in `<top (required)>'
        from C:/Ruby200-x64/bin/calabash-android:22:in `load'
        from C:/Ruby200-x64/bin/calabash-android:22:in `<main>'
0> No test server found for this combination of app and calabash version. Recreating test server.

****** PROCESS 0 COMPLETED ******

[0]
All threads complete

************ FINAL SUMMARY ************

Took 0 Minutes, 5.62 Seconds
Parallel run complete`

**Comment by TobiasRoikjer** [comment]
parallel_calabash is not a gem maintained or developed by the Calabash team. We do not support the gem.

**Comment by TobiasRoikjer** [comment]
For now, this issue can be solved simply by running bundle exec calabash-android build <apk> before running

**Comment by TobiasRoikjer** [comment]
Should be fixed in 0.8.4

**Comment by zanzaben** [comment]
0.8.4 fixed it. Thanks.
