### ISSUE TITLE
Clear_app_data not working in a before hook 

### ISSUE THREAD

**Issue by zanzaben** [calabash/calabash-android#784]
calling clear_app_data in a before hook does not always clear the data, It will only clear it sometimes and other times it won't and it seems to work of fail completely at random.  However having clear_app_data in an after hook works correctly every time. 

I have found a workaround by putting a sleep(1) in the before hook right after clear_app_data

Here are my hooks. 
After('@clear_data_after') do
  log "Clearing App Data"
  clear_app_data
end

Before('@clear_data, @clear_data_before') do |scenario|
  log "Clearing App Data "
  clear_app_data
  sleep(1)
  start_test_server_in_background
end

**Comment by TobiasRoikjer** [comment]
I added a sleep 2 in the clear_app_data method, released in 0.9.0
