### ISSUE TITLE
Problem querying the webview value that has forward slash in it

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#788]
Hai, can someone please look into the below error and let me know how I can overcome this. Thanks

`query("webView css:'button[name=home/office]'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map webView css:'button[name=home/office]', query failed because: sh.calaba.instrumentationbackend.query.ast.InvalidUIQueryException: Exception while running query: button[name=home/office]. SyntaxError: Failed to execute 'querySelectorAll' on 'Document': 'button[name=home/office]' is not a valid selector.`

WebView details:

`{
                "class" => "button-style no-padding left flex-grow max-width-phone side-margins",
             "nodeType" => "ELEMENT_NODE",
                   "id" => "",
        "calSavedIndex" => 0,
                 "html" => "<button class=\"button-style no-padding left flex-grow max-width-phone side-margins\" name=\"home/office\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1\"><div class=\"space-medium\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.0\"></div><div class=\"pure-g delivery-option-hor-2\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1\"><div class=\"pure-u-1-5 full-width tablet-center-ls block\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1.0\"><img class=\"select-delivery-option-icon vertical-align\" src=\"assets/images/icon_geotag_medium.png\" alt=\"icon\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1.0.0\"></div><div class=\"pure-u-3-5 body tablet-vert-m  full-width tablet-center-ls block\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1.1\">Home/office address</div><div class=\"pure-u-1-5 right tablet-invisible-ls block\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1.2\"><i class=\"arrow-active\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.1.2.0\"></i></div></div><div class=\"space-medium\" data-reactid=\".0.0.3.0.$=1$//selectDeliveryOption/=010.0.0.1.1.0:$0.1.2\"></div></button>",
          "textContent" => "Home/office address",
                 "rect" => {
                   "y" => 1008,
                   "x" => 90,
            "center_x" => 540,
              "height" => 210,
               "width" => 900,
                 "top" => 256,
                "left" => 30,
            "center_y" => 1113
        },`

Calabash version - 0.8.2
Ruby 2.3
System - Ubuntu 16.04

**Comment by TobiasRoikjer** [comment]
That is not a valid CSS selector. Put quotes around the value of the attribute selector.
