### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jakubbloksa** [calabash/calabash-android#811]
Hi,
I have seen this [thread](https://github.com/calabash/calabash-android/issues/365?_pjax=%23js-repo-pjax-container)

And I have similar problem. But nobody answered my question there, so I am opening new issue.
When I am trying to run tests from cmd with:
`calabash-android.bat run apkpath --name product-tests -p android`

It starts the testing...
Most of the times all of the tests pass, but other times it fails during testing with "Invalid byte sequence in UTF-8" error.
Can the problem be the additional `--name` parameter?

Version of my calabash-android is 0.7.3

**Comment by TobiasRoikjer** [comment]
Try updating to the latest version

**Comment by jakubbloksa** [comment]
I have tried... no effect.
Now I have calabash-android 0.9.0 and cucumber 2.4.0

**Comment by sherbhachu** [comment]
I think I had this problem a while back, what version of Ruby are you using?

I think my problem was that there was a gem being used in our project and I
found that when I upgraded from ruby 2.2.0 to ruby 2.3.0 it was ok.

Try having a go with RVM and get both versions installed and see what
happens.

**Comment by jakubbloksa** [comment]
I have tried both ruby 2.2.0 (2.2.5p319) and 2.3.0 (2.3.3p222)... same result
Also I am using windows, so no RVM, I have used Rubyinstaller

**Comment by jakubbloksa** [comment]
Right now I am getting different encoding error. I have some special characters used in my features and step_definitions (.rb files), but I have saved all these files with utf-8 encoding in my editor. Can be my system language involved in this problem?

error:
`incompatible character encodings: UTF-8 and CP852 (Encoding::CompatibilityError)
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb:288:in `_special'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb:271:in `cdata!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:132:in `block (2 levels) in build_testcase'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:130:in `block in build_testcase'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:123:in `build_testcase'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:63:in `on_after_test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `block in notify'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `notify'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/event_bus_report.rb:28:in `after_test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
C:/Ruby23/bin//cucumber:23:in `load'
C:/Ruby23/bin//cucumber:23:in `<main>'`

**Comment by TobiasRoikjer** [comment]
^That is a Cucumber error, it does not stem from Calabash and does not seem to be the result of any error in the (very little) communication Calabash does to Cucumber.
