### ISSUE TITLE
Calabash not installing on high sierra

### ISSUE THREAD

**Issue by asworm** [calabash/calabash-android#841]
Hi guys 

I am running mac High Sierra 
and running this:
$ curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash
will output this:
ERROR: calabash-sandbox only runs on macOS El Cap and Sierra

tried to find help for this, but my only thought is that this is to new to have any feedback on the issue.

my only concern is if there is any know issue with calabash and the new OS.

**Comment by jmoody** [comment]
We are no longer supporting the install tool.

> my only concern is if there is any know issue with calabash and the new OS.

There is no known issues with High Sierra.
