### ISSUE TITLE
Connection refused after turning wifi off via adb commands

### ISSUE THREAD

**Issue by Alikaraki95** [calabash/calabash-android#852]
So i'm trying to avoid creating a backdoor to turn wifi on/off, i searched a bit and found adb commands that do this, and they work.

Thing is , once i turn wifi off and get back to my app, i get this error

> Connection refused - Connection refused - Connection refused - connect(2) for "127.0.0.1" port 34781 (127.0.0.1:34781) (Errno::ECONNREFUSED)

Even tho i'm connected via usb, why can't i reconnect to the server ? Am i missing something ?

i tried running start_test_server_in_background and it also fails.. my app just won't reopen or if it does, it gives Connection refused error.

Any help would be appreciated.

**Comment by jmoody** [comment]
The client (gem) is trying to connect to the Test Server on the device via HTTP.

**Comment by Alikaraki95** [comment]
@jmoody Thanks for the quick response. Any idea on how do i fix this ?

**Comment by jmoody** [comment]
There is no fix.  Calabash Android and iOS are client/server applications over HTTP.

**Comment by Alikaraki95** [comment]
in other words, it's impossible to use it after turning off wifi ?
