### ISSUE TITLE
Cannot take screenshot with Android 8.1

### ISSUE THREAD

**Issue by akwkong** [calabash/calabash-android#853]
On a Nexus 5X running Android 8.1 with calabash-android 0.9.2, I am seeing these logs when trying to take a screenshot:

1> 01:46:07 E/Screenshot: Unsupported protocol: 2
Could not take screenshot
java.lang.NullPointerException
	at sh.calaba.screenshot.ScreenshotTaker.saveImage(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)

**Comment by abardallis** [comment]
@akwkong Any luck since? I'm seeing the exact same issue on my end with a Google Pixel 2 XL running Android 8.0 with calabash-android 0.9.0.

```
12:41:14 E/Screenshot: Unsupported protocol: 2
Could not take screenshot
java.lang.NullPointerException
	at sh.calaba.screenshot.ScreenshotTaker.saveImage(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)
```

No issues on any devices that are running Android 7 and earlier.

**Comment by akwkong** [comment]
Unfortunately, no luck still. That is interesting that you are seeing the issue with Android 8.0 on your Pixel 2 XL though. I remember it working on the Nexus 5X when it was running Android 8.0. Only when I updated it to Android 8.1 did screenshots stop working.

**Comment by landenlabs2** [comment]
I am having the same problem, screencap hangs on nexus 5x, 8.1.0

**Comment by abardallis** [comment]
@landenlabs2 – Does the whole test execution hang or do you just see the NullPointerException we both referenced above and the test keeps going? 

I’m going to try via a calabash console to manually execute the actual command sent to the device to take the screenshot and see what I can find out.

**Comment by mc-android-developer** [comment]
I think it's the same solution as here: https://github.com/xSAVIKx/AndroidScreencast/issues/46

**Comment by wuyaxin** [comment]
me too

**Comment by abardallis** [comment]
Nice – thanks @mc-android-developer 

For what it's worth, I also found that adding `SCREENSHOT_VIA_USB="false"` at runtime resolved the error. 

Example:
`calabash-android run path/to/apk.apk -p android SCREENSHOT_VIA_USB="false"`

May be more ideal to have the most up to date Android SDK Tools, however.

**Comment by AndreyMitsyk** [comment]
Issues has been resolved. Calabash-android "0.9.5" will include all required fixes.
