### ISSUE TITLE
Can’t support Flutter

### ISSUE THREAD

**Issue by lanzhu1993** [calabash/calabash-android#909]
Hello, Calabash-android can't support flutter ,if support flutter ,I think this test project will  Popular

Here is my test script：

Scenario: 应用启动后打开主界面                                # features/my_first.feature:3
    Then I wait for 2 seconds                         # calabash-android-0.9.9/lib/calabash-android/steps/progress_steps.rb:10
    Then I see "一休哥"                                  # calabash-android-0.9.9/lib/calabash-android/steps/assert_steps.rb:5
      Timeout waiting for elements: * {text CONTAINS[c] '一休哥'} (Calabash::Android::WaitHelpers::WaitError)
      features/my_first.feature:5:in `Then I see "一休哥"'
    And I see "突然想到的"                                 # calabash-android-0.9.9/lib/calabash-android/steps/assert_steps.rb:5
    When I press "一休哥"                                # calabash-android-0.9.9/lib/calabash-android/steps/press_button_steps.rb:17
    Then I see "一休哥"                                  # calabash-android-0.9.9/lib/calabash-android/steps/assert_steps.rb:5
    When I enter "一休哥，最近怎样" into input field number 1 # calabash-android-0.9.9/lib/calabash-android/steps/enter_text_steps.rb:9
    And I press "发送"                                  # calabash-android-0.9.9/lib/calabash-android/steps/press_button_steps.rb:17

**Comment by venky9885** [comment]
Does it support for flutter,plaese help me guys
