### ISSUE TITLE
How to run scenario again if it fails?

### ISSUE THREAD

**Issue by davidvavra** [calabash/calabash-android#918]
We have some test flakiness and it would help a lot if I could configure Calabash to run the same scenario again if it fails and really fail only for the second time. Any ideas how to approach this? I tried playing around with app_life_cycle_hooks.rb and launching Cucumber in after scenario step. But no luck.

**Comment by sherbhachu** [comment]
If you are using cucumber to drive the tests, then I'd suggest you use the
'retry' capability

**Comment by davidvavra** [comment]
Oh, I didn't know about this cucumber feature. Thanks a lot!
